import type { DepartmentDef } from "../types";

export const business_intelligence: DepartmentDef = {
  id: "business_intelligence",
  name: "Business Intelligence",
  nameBn: "বুদ্ধিমত্তা ও গবেষণা",
  icon: "📊",
  description: "Market research, competitive intelligence, data analytics, knowledge management",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "market_research",
      name: "Market Research",
      nameBn: "মার্কেট রিসার্চ",
      department: "business_intelligence",
      description: "Analyze market sectors, pain points, opportunities",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "student_market_analyzer", name: "Student Market Analyzer", nameBn: "ছাত্র বাজার বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes student sector market",
          descriptionBn: "ছাত্র সেক্টর বাজার বিশ্লেষণ করে",
          expertise: "You analyze student market: demographics, spending power, needs (tuition/courses/gadgets), part-time income desire, digital literacy.",
          promptTemplate: "Analyze student market. Segment: university/college/school. Needs, income potential, pain points. Bangladesh context. Opportunity assessment. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 80, when: "true",
        },
        {
          id: "homemaker_market_analyzer", name: "Homemaker Market Analyzer", nameBn: "গৃহিণী বাজার বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes homemaker sector market",
          descriptionBn: "গৃহিণী সেক্টর বাজার বিশ্লেষণ করে",
          expertise: "You analyze homemaker market: time availability, income desire, home-based business interest, network size, trust factors.",
          promptTemplate: "Analyze homemaker market. Demographics, income needs, time availability, home business interest. Bangladesh socio-cultural context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 75, when: "true",
        },
        {
          id: "job_holder_analyzer", name: "Job Holder Analyzer", nameBn: "চাকরিজীবী বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes employed professional sector",
          descriptionBn: "চাকরিজীবী সেক্টর বিশ্লেষণ করে",
          expertise: "You analyze job holders: income level, free time, side hustle interest, investment capacity, network size.",
          promptTemplate: "Analyze job holder market. Income brackets, side hustle interest, available hours, investment capacity. Bangladesh job market context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 70, when: "true",
        },
        {
          id: "business_owner_analyzer", name: "Business Owner Analyzer", nameBn: "ব্যবসায়ী বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes business owner sector",
          descriptionBn: "ব্যবসায়ী সেক্টর বিশ্লেষণ করে",
          expertise: "You analyze business owners: business type, revenue, expansion interest, network value, B2B potential.",
          promptTemplate: "Analyze business owner market. Business types, revenue range, expansion interest, partnership potential. Bangladesh SME context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 65, when: "true",
        },
        {
          id: "freelancer_analyzer", name: "Freelancer Analyzer", nameBn: "ফ্রিল্যান্সার বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes freelancer sector",
          descriptionBn: "ফ্রিল্যান্সার সেক্টর বিশ্লেষণ করে",
          expertise: "You analyze freelancers: skill type, income stability, platform dependency, growth need, community interest.",
          promptTemplate: "Analyze freelancer market. Skills, income patterns, growth needs, community interest. Bangladesh freelancing context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 60, when: "true",
        },
        {
          id: "unemployed_analyzer", name: "Unemployed Analyzer", nameBn: "বেকার বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes unemployed sector",
          descriptionBn: "বেকার সেক্টর বিশ্লেষণ করে",
          expertise: "You analyze unemployed: education level, financial pressure, motivation, skill gap, entrepreneur interest.",
          promptTemplate: "Analyze unemployed market. Demographics, financial needs, motivation level, entrepreneur interest. Bangladesh job market. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 55, when: "true",
        },
        {
          id: "rural_analyzer", name: "Rural Analyzer", nameBn: "গ্রামীণ বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes rural Bangladesh market",
          descriptionBn: "গ্রামীণ বাংলাদেশ বাজার বিশ্লেষণ করে",
          expertise: "You analyze rural market: income sources, mobile penetration, digital literacy, community trust, logistics challenges.",
          promptTemplate: "Analyze rural market. Income sources, mobile usage, digital literacy, trust factors, logistics. Bangladesh rural context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 50, when: "true",
        },
        {
          id: "urban_analyzer", name: "Urban Analyzer", nameBn: "শহুরে বিশ্লেষক",
          department: "business_intelligence", team: "market_research",
          description: "Analyzes urban Bangladesh market",
          descriptionBn: "শহুরে বাংলাদেশ বাজার বিশ্লেষণ করে",
          expertise: "You analyze urban market: income levels, digital adoption, competition, lifestyle, spending patterns.",
          promptTemplate: "Analyze urban market. Income, digital adoption, competition, lifestyle. Bangladesh urban context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 50, when: "true",
        },
        {
          id: "pain_point_miner", name: "Pain Point Miner", nameBn: "পেইন পয়েন্ট মাইনার",
          department: "business_intelligence", team: "market_research",
          description: "Mines pain points from customer conversations",
          descriptionBn: "গ্রাহক কথোপকথন থেকে পেইন পয়েন্ট বের করে",
          expertise: "You analyze conversations to extract pain points: financial, trust, time, skill, result, commitment, competition.",
          promptTemplate: "Mine pain points from: {{text}}. Identify primary pain. Category: financial/trust/time/skill/result/commitment. Evidence. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "opportunity_detector", name: "Opportunity Detector", nameBn: "সুযোগ শনাক্তকারী",
          department: "business_intelligence", team: "market_research",
          description: "Identifies new business opportunities",
          descriptionBn: "নতুন ব্যবসায়িক সুযোগ চিহ্নিত করে",
          expertise: "You identify opportunities: underserved segments, emerging needs, partnerships, new categories, expansion areas.",
          promptTemplate: "Detect opportunities: market={{market}}, trends={{trends}}. 3 opportunities + potential impact + effort level. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "true",
        },
      ],
    },
    {
      id: "competitive_intelligence",
      name: "Competitive Intelligence",
      nameBn: "প্রতিযোগিতামূলক বুদ্ধিমত্তা",
      department: "business_intelligence",
      description: "Track competitors, market trends, pricing",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "competitor_tracker", name: "Competitor Tracker", nameBn: "প্রতিযোগী ট্র্যাকার",
          department: "business_intelligence", team: "competitive_intelligence",
          description: "Monitors competitor activities",
          descriptionBn: "প্রতিযোগীদের কার্যক্রম পর্যবেক্ষণ করে",
          expertise: "You track competitors: pricing changes, new products, promotions, marketing, hiring, partnerships, reviews.",
          promptTemplate: "Competitor update: {{competitor}}, moves={{moves}}. Impact on us. Recommended response: ignore/watch/act. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "true",
        },
        {
          id: "market_trend_analyzer", name: "Market Trend Analyzer", nameBn: "বাজার ট্রেন্ড বিশ্লেষক",
          department: "business_intelligence", team: "competitive_intelligence",
          description: "Analyzes market trends and shifts",
          descriptionBn: "বাজারের ট্রেন্ড ও পরিবর্তন বিশ্লেষণ করে",
          expertise: "You analyze trends: emerging products, seasonal patterns, consumer behavior, regulatory changes, technology shifts.",
          promptTemplate: "Analyze trends: industry={{industry}}, timeframe={{time}}. Key trends, impact, recommended actions. Bangladesh context. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["nemotron-3-ultra"],
          tier: 1, priority: 85, when: "true",
        },
        {
          id: "pricing_strategist", name: "Pricing Strategist", nameBn: "মূল্য কৌশলবিদ",
          department: "business_intelligence", team: "competitive_intelligence",
          description: "Recommends pricing strategies",
          descriptionBn: "মূল্য নির্ধারণ কৌশল সুপারিশ করে",
          expertise: "You recommend pricing: market-based, value-based, penetration, premium. Consider competitor pricing, customer segments, margins.",
          promptTemplate: "Recommend pricing: product={{product}}, competitors={{competitors}}, costs={{costs}}. Strategy + recommended price + reasoning. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 80, when: "true",
        },
        {
          id: "product_gap_finder", name: "Product Gap Finder", nameBn: "পণ্য ফাঁক শনাক্তকারী",
          department: "business_intelligence", team: "competitive_intelligence",
          description: "Finds gaps in the product line",
          descriptionBn: "পণ্য লাইনে ফাঁক খুঁজে বের করে",
          expertise: "You find gaps: competitor products we don't offer, customer needs unmet, market segments underserved, feature gaps.",
          promptTemplate: "Find product gaps: our products={{ours}}, competitors={{theirs}}, needs={{needs}}. Gap analysis + suggestions. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 75, when: "true",
        },
        {
          id: "swot_analyzer", name: "SWOT Analyzer", nameBn: "SWOT বিশ্লেষক",
          department: "business_intelligence", team: "competitive_intelligence",
          description: "Performs SWOT analysis",
          descriptionBn: "SWOT (শক্তি-দুর্বলতা-সুযোগ-হুমকি) বিশ্লেষণ করে",
          expertise: "You perform SWOT: Strengths, Weaknesses, Opportunities, Threats. Actionable insights from each quadrant.",
          promptTemplate: "SWOT analysis: company={{company}}, market={{market}}. Strengths, Weaknesses, Opportunities, Threats. Strategic recommendations. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 70, when: "true",
        },
      ],
    },
    {
      id: "data_analytics",
      name: "Data Analytics",
      nameBn: "ডাটা এনালাইটিক্স",
      department: "business_intelligence",
      description: "Analyze sales, growth, conversion, retention",
      primaryModel: "nemotron-3-super",
      fallbackModels: ["gpt-5.4-mini", "deepseek-v4-flash-free"],
      agents: [
        {
          id: "sales_analyst", name: "Sales Analyst", nameBn: "সেলস এনালাইস্ট",
          department: "business_intelligence", team: "data_analytics",
          description: "Analyzes sales performance data",
          descriptionBn: "সেলস পারফরম্যান্স ডাটা বিশ্লেষণ করে",
          expertise: "You analyze sales: daily/weekly/monthly trends, product performance, channel effectiveness, growth rate.",
          promptTemplate: "Sales analysis: period={{period}}, total={{total}}, top={{top}}, growth={{growth}}%. Trends, insights, recommendations. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "true",
        },
        {
          id: "member_growth_analyst", name: "Member Growth Analyst", nameBn: "সদস্য বৃদ্ধি বিশ্লেষক",
          department: "business_intelligence", team: "data_analytics",
          description: "Analyzes member growth patterns",
          descriptionBn: "সদস্য বৃদ্ধির প্যাটার্ন বিশ্লেষণ করে",
          expertise: "You analyze member growth: new signups, activation rate, source effectiveness, demographic trends, growth velocity.",
          promptTemplate: "Member growth: new={{new}}, active={{active}}, source={{source}}, growth={{growth}}%. Trends + suggestions. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 80, when: "true",
        },
        {
          id: "conversion_funnel_analyst", name: "Conversion Funnel Analyst", nameBn: "কনভার্সন ফানেল বিশ্লেষক",
          department: "business_intelligence", team: "data_analytics",
          description: "Analyzes conversion funnel stages",
          descriptionBn: "কনভার্সন ফানেল স্টেজ বিশ্লেষণ করে",
          expertise: "You analyze funnel: visit→lead→interested→purchase→repeat. Drop-off points, improvement opportunities, conversion rate optimization.",
          promptTemplate: "Funnel analysis: visitors={{v}}, leads={{l}}, interested={{i}}, purchased={{p}}, repeat={{r}}. Drop-offs, bottlenecks, fixes. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 75, when: "true",
        },
        {
          id: "retention_analyst", name: "Retention Analyst", nameBn: "রিটেনশন এনালাইস্ট",
          department: "business_intelligence", team: "data_analytics",
          description: "Analyzes member retention rates",
          descriptionBn: "সদস্য ধরে রাখার হার বিশ্লেষণ করে",
          expertise: "You analyze retention: weekly/monthly retention, churn rate, at-risk segments, retention drivers, win-back effectiveness.",
          promptTemplate: "Retention: period={{period}}, rate={{rate}}%, churn={{churn}}%. At-risk segments, retention drivers, recommendations. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 70, when: "true",
        },
        {
          id: "roi_calculator", name: "ROI Calculator", nameBn: "ROI ক্যালকুলেটর",
          department: "business_intelligence", team: "data_analytics",
          description: "Calculates return on investment",
          descriptionBn: "বিনিয়োগের উপর রিটার্ন গণনা করে",
          expertise: "You calculate ROI: campaign ROI, member lifetime value, acquisition cost, channel profitability, program effectiveness.",
          promptTemplate: "Calculate ROI. Investment={{investment}}, return={{return}}, period={{period}}. ROI={{roi}}%. Analysis + recommendations. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 65, when: "true",
        },
        {
          id: "predictive_modeler", name: "Predictive Modeler", nameBn: "পূর্বাভাস মডেলার",
          department: "business_intelligence", team: "data_analytics",
          description: "Forecasts future performance",
          descriptionBn: "ভবিষ্যত কর্মক্ষমতার পূর্বাভাস দেয়",
          expertise: "You forecast: next month sales, member growth, revenue, churn. Based on historical data, trends, seasonality.",
          promptTemplate: "Forecast: historical={{data}}, seasonality={{season}}, initiatives={{init}}. Projected: sales, members, revenue. Confidence: high/medium/low. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 60, when: "true",
        },
        {
          id: "report_compiler", name: "Report Compiler", nameBn: "রিপোর্ট কম্পাইলার",
          department: "business_intelligence", team: "data_analytics",
          description: "Compiles all data into comprehensive reports",
          descriptionBn: "সব ডাটা একত্রে বিস্তৃত রিপোর্ট তৈরি করে",
          expertise: "You compile reports: executive summary, key metrics, trends, challenges, recommendations. Professional format for stakeholders.",
          promptTemplate: "Compile report. Data: sales={{sales}}, members={{members}}, retention={{ret}}, growth={{growth}}. Executive summary + insights + recommendations. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "true",
        },
      ],
    },
    {
      id: "knowledge_management",
      name: "Knowledge Management",
      nameBn: "নলেজ ম্যানেজমেন্ট",
      department: "business_intelligence",
      description: "Mine conversations, auto-learn skills, update knowledge base",
      primaryModel: "nemotron-3-super",
      fallbackModels: ["gpt-5.4-mini", "deepseek-v4-flash-free"],
      agents: [
        {
          id: "conversation_miner", name: "Conversation Miner", nameBn: "কথোপকথন খননকারী",
          department: "business_intelligence", team: "knowledge_management",
          description: "Mines new knowledge from conversations",
          descriptionBn: "কথোপকথন থেকে নতুন জ্ঞান বের করে",
          expertise: "You analyze conversations for: new questions, emerging patterns, customer needs, product feedback, competitor mentions.",
          promptTemplate: "Mine conversation: {{text}}. Extract: new questions, patterns, needs, feedback, competitor mentions. Add to knowledge base. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 85, when: "true",
        },
        {
          id: "skill_auto_learner", name: "Skill Auto-Learner", nameBn: "স্কিল অটো-লার্নার",
          department: "business_intelligence", team: "knowledge_management",
          description: "Auto-creates skills from repeated questions (3+ times)",
          descriptionBn: "৩+ বার আসা প্রশ্ন থেকে স্বয়ংক্রিয়ভাবে স্কিল তৈরি করে",
          expertise: "You detect repeated questions: same question asked 3+ times → create skill. Save answer as cached response for instant reply.",
          promptTemplate: "Auto-learn skill. Question: {{question}} appeared {{count}} times. Answer: {{answer}}. Create skill? yes/no. If yes → save {{question}} = {{answer}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "true",
        },
        {
          id: "knowledge_base_updater", name: "Knowledge Base Updater", nameBn: "নলেজ বেস আপডেটার",
          department: "business_intelligence", team: "knowledge_management",
          description: "Updates knowledge base with new information",
          descriptionBn: "নতুন তথ্য দিয়ে নলেজ বেস আপডেট করে",
          expertise: "You update knowledge base: add new FAQs, update outdated answers, remove obsolete info, categorize correctly.",
          promptTemplate: "Update KB: {{newInfo}}. Category: {{category}}. Action: add/update/remove. Ensure accuracy, clarity, policy compliance. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "true",
        },
        {
          id: "cross_user_pattern_finder", name: "Cross-User Pattern Finder", nameBn: "ক্রস-ইউজার প্যাটার্ন ফাইন্ডার",
          department: "business_intelligence", team: "knowledge_management",
          description: "Finds common patterns across all users",
          descriptionBn: "সব ইউজারের মধ্যে কমন প্যাটার্ন খুঁজে বের করে",
          expertise: "You find patterns: common questions, shared pain points, similar objections, buying behavior clusters, demographic trends.",
          promptTemplate: "Find cross-user patterns. Data={{data}}. Top 3 patterns: pattern + frequency + insight. Actionable recommendations. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "true",
        },
        {
          id: "industry_researcher", name: "Industry Researcher", nameBn: "ইন্ডাস্ট্রি রিসার্চার",
          department: "business_intelligence", team: "knowledge_management",
          description: "Gathers industry knowledge from web/AI",
          descriptionBn: "ওয়েব/এআই থেকে ইন্ডাস্ট্রি জ্ঞান সংগ্রহ করে",
          expertise: "You research: industry news, best practices, regulatory updates, technology trends, market reports, success stories.",
          promptTemplate: "Research industry: {{topic}}. Findings: latest news, best practices, regulations, trends. Summarize for team. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 70, when: "true",
        },
      ],
    },
  ],
};
