import type { DepartmentDef } from "../types";

export const customer_experience: DepartmentDef = {
  id: "customer_experience",
  name: "Customer Experience",
  nameBn: "গ্রাহক অভিজ্ঞতা",
  icon: "🤝",
  description: "Customer support, feedback, premium service",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "customer_support",
      name: "Customer Support",
      nameBn: "গ্রাহক সাপোর্ট",
      department: "customer_experience",
      description: "First-line support, issue resolution, order tracking",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "faq_responder", name: "FAQ Responder", nameBn: "FAQ উত্তরদাতা",
          department: "customer_experience", team: "customer_support",
          description: "Answers common questions instantly from skill cache",
          descriptionBn: "সাধারণ প্রশ্নের স্কিল ক্যাশ থেকে তাৎক্ষণিক উত্তর দেয়",
          expertise: "You answer all FAQs: pricing, payment, delivery, returns, registration, products, commissions, policies.",
          promptTemplate: "Answer FAQ: {{question}}. Provide clear complete answer. Include relevant links. End with 'আরো কিছু জানতে চান?' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 100, when: "intent === 'general' || intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "order_status_checker", name: "Order Status Checker", nameBn: "অর্ডার স্ট্যাটাস চেকার",
          department: "customer_experience", team: "customer_support",
          description: "Checks and provides order status updates",
          descriptionBn: "অর্ডার স্ট্যাটাস চেক ও আপডেট দেয়",
          expertise: "You check order status: confirmed, processing, shipped, delivered. Provide ETA. Handle delays with transparency.",
          promptTemplate: "Check order {{orderId}}. Status: {{status}}, ETA: {{eta}}. If delayed → apologize + reason + new ETA. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 90, when: "intent === 'general'",
        },
        {
          id: "payment_issue_resolver", name: "Payment Issue Resolver", nameBn: "পেমেন্ট সমস্যা সমাধানকারী",
          department: "customer_experience", team: "customer_support",
          description: "Resolves payment-related issues",
          descriptionBn: "পেমেন্ট সংক্রান্ত সমস্যা সমাধান করে",
          expertise: "You resolve payment issues: failed transaction, wrong charge, double charge, refund not received, payment not reflected.",
          promptTemplate: "Resolve payment issue: {{issue}}. Verify with gateway, check details, initiate correction. Keep customer updated. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "product_info_provider", name: "Product Info Provider", nameBn: "পণ্য তথ্য প্রদানকারী",
          department: "customer_experience", team: "customer_support",
          description: "Provides detailed product information",
          descriptionBn: "পণ্যের বিস্তারিত তথ্য দেয়",
          expertise: "You know all products: features, price, benefits, usage, availability, specifications, comparisons.",
          promptTemplate: "Provide product info for {{product}}. Features, price BDT, benefits, how to use, availability. Be detailed but clear. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'product_inquiry'",
        },
        {
          id: "delivery_tracker", name: "Delivery Tracker", nameBn: "ডেলিভারি ট্র্যাকার",
          department: "customer_experience", team: "customer_support",
          description: "Tracks product delivery status",
          descriptionBn: "পণ্য ডেলিভারি স্ট্যাটাস ট্র্যাক করে",
          expertise: "You track deliveries: courier, tracking number, location, ETA, delivery confirmation, delay handling.",
          promptTemplate: "Track delivery: courier={{courier}}, tracking={{tracking}}. Status: {{status}}, ETA={{eta}}. If delayed: apologize + new ETA. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "intent === 'general'",
        },
        {
          id: "return_exchange_handler", name: "Return/Exchange Handler", nameBn: "রিটার্ন/এক্সচেঞ্জ হ্যান্ডলার",
          department: "customer_experience", team: "customer_support",
          description: "Handles product returns and exchanges",
          descriptionBn: "পণ্য ফেরত ও বিনিময় পরিচালনা করে",
          expertise: "You handle returns: check policy, reason, condition, initiate return, arrange pickup, process refund/replacement.",
          promptTemplate: "Handle return: order={{orderId}}, reason={{reason}}. Check period, guide steps, inform timeline. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 70, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "refund_processor", name: "Refund Processor", nameBn: "রিফান্ড প্রসেসর",
          department: "customer_experience", team: "customer_support",
          description: "Processes refund requests",
          descriptionBn: "রিফান্ড রিকোয়েস্ট প্রসেস করে",
          expertise: "You process refunds: verify eligibility, calculate amount, initiate refund, notify customer, confirm completion.",
          promptTemplate: "Process refund: order={{orderId}}, amount={{amount}}, method={{method}}. Steps: verify → process → notify → confirm. Timeline: 5-7 days. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'complaint' || intent === 'general'",
        },
      ],
    },
    {
      id: "feedback_improvement",
      name: "Feedback & Improvement",
      nameBn: "ফিডব্যাক ও উন্নয়ন",
      department: "customer_experience",
      description: "Collect feedback, analyze sentiment, improve",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "feedback_collector", name: "Feedback Collector", nameBn: "ফিডব্যাক সংগ্রহকারী",
          department: "customer_experience", team: "feedback_improvement",
          description: "Collects customer feedback after interactions",
          descriptionBn: "ইন্টারঅ্যাকশনের পর গ্রাহকের ফিডব্যাক সংগ্রহ করে",
          expertise: "You collect feedback: post-purchase, post-support, post-onboarding. Use NPS + open-ended questions. Friendly timing.",
          promptTemplate: "Ask for feedback. NPS: '0-10 স্কেলে রেট দিন?' Follow-up: 'কী ভালো লাগলো?' Keep short. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 90, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "sentiment_analyzer", name: "Sentiment Analyzer", nameBn: "ভাব বিশ্লেষক",
          department: "customer_experience", team: "feedback_improvement",
          description: "Analyzes feedback sentiment in depth",
          descriptionBn: "ফিডব্যাকের ভাব গভীরভাবে বিশ্লেষণ করে",
          expertise: "You analyze sentiment: positive, neutral, negative, mixed. Extract themes: price, service, support, product, delivery.",
          promptTemplate: "Analyze feedback: {{feedback}}. Sentiment: positive/neutral/negative/mixed. Themes, urgency, suggested action. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 85, when: "true",
        },
        {
          id: "complaint_categorizer", name: "Complaint Categorizer", nameBn: "অভিযোগ ক্যাটাগরাইজার",
          department: "customer_experience", team: "feedback_improvement",
          description: "Categorizes complaints by type and severity",
          descriptionBn: "অভিযোগের ধরন ও তীব্রতা অনুসারে শ্রেণীবদ্ধ করে",
          expertise: "You categorize: product quality, delivery, payment, service, communication, technical. Severity: P1-P4.",
          promptTemplate: "Categorize complaint: {{text}}. Category: product/delivery/payment/service/tech. Severity: P1(urgent) to P4(minor). Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'complaint'",
        },
        {
          id: "improvement_suggester", name: "Improvement Suggester", nameBn: "উন্নতি প্রস্তাবকারী",
          department: "customer_experience", team: "feedback_improvement",
          description: "Suggests process improvements from feedback",
          descriptionBn: "ফিডব্যাক থেকে প্রক্রিয়া উন্নতির প্রস্তাব দেয়",
          expertise: "You identify patterns in feedback, suggest actionable improvements: process changes, training needs, feature requests.",
          promptTemplate: "Suggest improvements. Feedback pattern: {{pattern}}. Top 3 suggestions: problem → solution → impact. Prioritize. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "true",
        },
        {
          id: "nps_calculator", name: "NPS Calculator", nameBn: "NPS ক্যালকুলেটর",
          department: "customer_experience", team: "feedback_improvement",
          description: "Calculates and tracks Net Promoter Score",
          descriptionBn: "Net Promoter Score গণনা ও ট্র্যাক করে",
          expertise: "You calculate NPS: Promoters (9-10) - Detractors (0-6) = NPS. Track trends, segment, suggest improvements.",
          promptTemplate: "NPS: promoters={{p}}, passives={{pa}}, detractors={{d}}. Score={{nps}}. Trend. Segments. Top 3 improvements. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 70, when: "true",
        },
        {
          id: "review_responder", name: "Review Responder", nameBn: "রিভিউ প্রতিউত্তরকারী",
          department: "customer_experience", team: "feedback_improvement",
          description: "Auto-responds to reviews (thank you/sorry)",
          descriptionBn: "রিভিউতে অটো রিপ্লাই (ধন্যবাদ/দুঃখিত)",
          expertise: "You respond to reviews: positive → thank you, negative → apologize + offer fix, neutral → thank for feedback.",
          promptTemplate: "Respond to review: rating={{rating}}, text={{text}}. Positive: thank + appreciate. Negative: apologize + offer resolution. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 60, when: "true",
        },
      ],
    },
    {
      id: "premium_experience",
      name: "Premium Experience",
      nameBn: "প্রিমিয়াম অভিজ্ঞতা",
      department: "customer_experience",
      description: "Personalized greetings, tone adjustment, surprises",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "greeting_personalizer", name: "Greeting Personalizer", nameBn: "গ্রিটিং পার্সোনালাইজার",
          department: "customer_experience", team: "premium_experience",
          description: "Greets based on name, religion, language",
          descriptionBn: "নাম, ধর্ম, ভাষা অনুসারে গ্রিটিং দেয়",
          expertise: "You personalize greetings: Assalamu Alaikum for Muslims, Namaskar for Hindus, Hello for English. Use customer name.",
          promptTemplate: "Personalize greeting. Name={{name}}, religion={{religion}}, language={{language}}. Use appropriate greeting. Warm and respectful. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'greeting'",
        },
        {
          id: "tone_adjuster", name: "Tone Adjuster", nameBn: "টোন এডজাস্টার",
          department: "customer_experience", team: "premium_experience",
          description: "Adjusts response tone based on customer mood",
          descriptionBn: "গ্রাহকের মুড অনুসারে টোন এডজাস্ট করে",
          expertise: "You adjust tone: angry → calm + empathetic, happy → energetic + warm, sad → gentle + supportive, neutral → professional + friendly.",
          promptTemplate: "Adjust tone for mood={{mood}}. Guidelines: angry→calm, happy→energetic, sad→gentle, neutral→friendly. Mirror their energy. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "true",
        },
        {
          id: "surprise_delight_creator", name: "Surprise & Delight Creator", nameBn: "আশ্চর্য ও আনন্দ সৃষ্টিকারী",
          department: "customer_experience", team: "premium_experience",
          description: "Creates delightful surprises for customers",
          descriptionBn: "গ্রাহকদের জন্য আনন্দদায়ক চমক তৈরি করে",
          expertise: "You create surprises: unexpected discount, bonus gift, birthday wish, loyalty reward, upgrade, personalized video message.",
          promptTemplate: "Create surprise. Customer={{name}}, occasion={{occasion}}. Surprise type: gift/discount/bonus. Make it feel special. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 80, when: "true",
        },
        {
          id: "anniversary_reminder", name: "Anniversary Reminder", nameBn: "বার্ষিকী স্মারক",
          department: "customer_experience", team: "premium_experience",
          description: "Sends joining anniversary wishes",
          descriptionBn: "জয়েনিং অ্যানিভার্সারি উইশ পাঠায়",
          expertise: "You track and celebrate: membership anniversary, first purchase anniversary, first referral anniversary, rank anniversary.",
          promptTemplate: "Send anniversary wish. Member={{name}}, anniversary={{type}}, years={{years}}. Warm congratulatory message. Mention their journey. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 70, when: "true",
        },
        {
          id: "premium_badge_notifier", name: "Premium Badge Notifier", nameBn: "প্রিমিয়াম ব্যাজ নোটিফায়ার",
          department: "customer_experience", team: "premium_experience",
          description: "Notifies premium members about their status",
          descriptionBn: "প্রিমিয়াম মেম্বারদের তাদের স্ট্যাটাস জানায়",
          expertise: "You notify premium members: their tier status, exclusive benefits, special access, priority support, VIP events.",
          promptTemplate: "Notify premium status. Member={{name}}, tier={{tier}}. Benefits: priority support, exclusive offers, special events. Make them feel valued. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 65, when: "true",
        },
        {
          id: "culture_respector", name: "Culture Respector", nameBn: "সংস্কৃতি সম্মানকারী",
          department: "customer_experience", team: "premium_experience",
          description: "Respects cultural norms and sensitivities",
          descriptionBn: "সাংস্কৃতিক নিয়ম ও সংবেদনশীলতা সম্মান করে",
          expertise: "You respect cultural norms: appropriate greetings by religion, modesty, family values, festival greetings (Eid/Puja), time sensitivity.",
          promptTemplate: "Apply cultural respect. Religion={{religion}}, occasion={{occasion}}. Use appropriate greeting, avoid sensitive topics, respect norms. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'greeting'",
        },
      ],
    },
  ],
};
