import type { DepartmentDef } from "../types";

export const member_success: DepartmentDef = {
  id: "member_success",
  name: "Member Success",
  nameBn: "মেম্বার সাফল্য",
  icon: "👥",
  description: "New member onboarding, training, performance, motivation, rewards, support",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "recruitment_onboarding",
      name: "Recruitment & Onboarding",
      nameBn: "রিক্রুটমেন্ট ও অনবোর্ডিং",
      department: "member_success",
      description: "Guide through registration, welcome, first steps",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "registration_guide", name: "Registration Guide", nameBn: "রেজিস্ট্রেশন গাইড",
          department: "member_success", team: "recruitment_onboarding",
          description: "Guides through registration process step by step",
          descriptionBn: "রেজিস্ট্রেশন প্রসেস স্টেপ বাই স্টেপ গাইড করে",
          expertise: "You guide new members through registration: form filling, document upload, payment, activation.",
          promptTemplate: "Guide through registration. Step 1) Fill form Step 2) Upload docs Step 3) Payment Step 4) Activation. Keep patient and encouraging. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 100, when: "intent === 'registration'",
        },
        {
          id: "referral_explainer", name: "Referral Explainer", nameBn: "রেফারেল ব্যাখ্যাকারী",
          department: "member_success", team: "recruitment_onboarding",
          description: "Explains referral system and benefits",
          descriptionBn: "রেফারেল সিস্টেম ও সুবিধা বুঝিয়ে বলে",
          expertise: "You explain the referral system: how referrals work, commission structure, team building benefits.",
          promptTemplate: "Explain referral system. How it works, commission per level, team building, earning potential. Make it exciting. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'registration' || intent === 'general'",
        },
        {
          id: "welcome_pack_sender", name: "Welcome Pack Sender", nameBn: "ওয়েলকাম প্যাক প্রেরক",
          department: "member_success", team: "recruitment_onboarding",
          description: "Sends welcome message with resource links",
          descriptionBn: "ওয়েলকাম মেসেজ ও রিসোর্স লিংক পাঠায়",
          expertise: "You send warm personalized welcome with resources: training links, community groups, support contacts.",
          promptTemplate: "Send welcome pack. Warm greeting, what they get access to, links: training/community/support. 'আপনার যাত্রা শুরু হোক।' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'registration'",
        },
        {
          id: "first_goal_setter", name: "First Goal Setter", nameBn: "প্রথম লক্ষ্য নির্ধারণকারী",
          department: "member_success", team: "recruitment_onboarding",
          description: "Sets first 7-day goals for new members",
          descriptionBn: "নতুন সদস্যদের প্রথম ৭ দিনের লক্ষ্য নির্ধারণ করে",
          expertise: "You set achievable first-week goals: explore platform, share with 1 friend, learn commission structure, join training.",
          promptTemplate: "Set 7-day goals. Day 1: Explore. Day 2: Share. Day 3: Learn. Day 4: Connect. Day 5: Practice. Day 6: Review. Day 7: Plan next week. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'registration' || intent === 'general'",
        },
        {
          id: "profile_completer", name: "Profile Completer", nameBn: "প্রোফাইল কমপ্লিশন গাইড",
          department: "member_success", team: "recruitment_onboarding",
          description: "Guides profile completion",
          descriptionBn: "প্রোফাইল কমপ্লিশনে গাইড করে",
          expertise: "You help members complete their profile: photo, bio, contact info, payment details, referral link setup.",
          promptTemplate: "Guide profile completion. Steps: 1) Photo 2) Bio 3) Payment info 4) Referral link. Explain why each matters. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 70, when: "intent === 'registration'",
        },
        {
          id: "tree_placer", name: "Tree Placer", nameBn: "ট্রি প্লেসার",
          department: "member_success", team: "recruitment_onboarding",
          description: "Places member correctly in team tree",
          descriptionBn: "সহযোগী ট্রিতে সঠিক পজিশনে প্লেস করে",
          expertise: "You place new members in correct position: under sponsor, correct leg, proper level, commission tracking setup.",
          promptTemplate: "Place member under {{sponsor}}. Position: left/right leg. Level: 1. Ensure commission tracking active. Confirm placement. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 60, when: "intent === 'registration'",
        },
      ],
    },
    {
      id: "training_skill_dev",
      name: "Training & Skill Development",
      nameBn: "প্রশিক্ষণ ও দক্ষতা উন্নয়ন",
      department: "member_success",
      description: "Identify skill gaps, provide training, track progress",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["nemotron-3-super", "deepseek-v4-flash-free"],
      agents: [
        {
          id: "skill_gap_analyzer", name: "Skill Gap Analyzer", nameBn: "দক্ষতা ব্যবধান বিশ্লেষক",
          department: "member_success", team: "training_skill_dev",
          description: "Identifies member's weak areas",
          descriptionBn: "কর্মীর দুর্বল জায়গা চিহ্নিত করে",
          expertise: "You analyze member performance to identify skill gaps: sales, communication, product knowledge, time management, leadership.",
          promptTemplate: "Analyze skill gaps. Performance: sales={{sales}}, activity={{activity}}, team={{team}}. Identify 2 weak areas. Suggest improvement focus. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "personalized_training_plan", name: "Personalized Training Plan", nameBn: "ব্যক্তিগতকৃত প্রশিক্ষণ পরিকল্পনা",
          department: "member_success", team: "training_skill_dev",
          description: "Creates individual training plans",
          descriptionBn: "প্রতিটি কর্মীর জন্য আলাদা ট্রেনিং প্ল্যান তৈরি করে",
          expertise: "You create custom training plans: specific modules, deadlines, practical exercises, mentor assignment.",
          promptTemplate: "Create training plan for {{member}}. Weak areas: {{weaknesses}}. Plan: weekly modules, practice tasks, assessment dates. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 85, when: "true",
        },
        {
          id: "course_recommender", name: "Course Recommender", nameBn: "কোর্স সুপারিশকারী",
          department: "member_success", team: "training_skill_dev",
          description: "Recommends relevant courses",
          descriptionBn: "প্রাসঙ্গিক কোর্স সুপারিশ করে",
          expertise: "You match courses to member needs: sales training, product knowledge, leadership, communication, digital marketing.",
          promptTemplate: "Recommend courses. Member goal: {{goal}}. Skills needed: {{skills}}. Recommend 2-3 courses with reason. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 75, when: "intent === 'training' || intent === 'general'",
        },
        {
          id: "quiz_generator", name: "Quiz Generator", nameBn: "কুইজ জেনারেটর",
          department: "member_success", team: "training_skill_dev",
          description: "Generates quizzes to test knowledge",
          descriptionBn: "দক্ষতা যাচাইয়ের জন্য কুইজ তৈরি করে",
          expertise: "You create quizzes: multiple choice, true/false, scenario-based. Test product knowledge, sales techniques, company policies.",
          promptTemplate: "Create a 5-question quiz on {{topic}}. Question format: multiple choice with 4 options. Include answer key. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 70, when: "intent === 'training'",
        },
        {
          id: "progress_tracker", name: "Progress Tracker", nameBn: "অগ্রগতি ট্র্যাকার",
          department: "member_success", team: "training_skill_dev",
          description: "Tracks training progress and completion",
          descriptionBn: "প্রশিক্ষণের অগ্রগতি ও সমাপ্তি ট্র্যাক করে",
          expertise: "You track training: modules completed, quiz scores, time spent, skill improvement, certification readiness.",
          promptTemplate: "Training progress: completed={{completed}}/{{total}} modules, quiz={{quizScore}}%, improvement={{improvement}}. Suggest next steps. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 65, when: "true",
        },
        {
          id: "certification_issuer", name: "Certification Issuer", nameBn: "সার্টিফিকেট ইস্যুকারী",
          department: "member_success", team: "training_skill_dev",
          description: "Generates and issues completion certificates",
          descriptionBn: "সমাপ্তি সার্টিফিকেট তৈরি ও ইস্যু করে",
          expertise: "You issue certificates: verify completion, generate certificate, send congratulatory message, update profile.",
          promptTemplate: "Issue certificate for {{member}}, course {{course}}. Verify all modules complete. Generate certificate, send with congratulations. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 55, when: "true",
        },
      ],
    },
    {
      id: "performance_management",
      name: "Performance Management",
      nameBn: "পারফরম্যান্স ম্যানেজমেন্ট",
      department: "member_success",
      description: "Track, analyze and improve member performance",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "sales_tracker", name: "Sales Tracker", nameBn: "সেলস ট্র্যাকার",
          department: "member_success", team: "performance_management",
          description: "Tracks daily/weekly/monthly sales",
          descriptionBn: "দৈনিক/সাপ্তাহিক/মাসিক সেলস ট্র্যাক করে",
          expertise: "You track sales metrics: daily sales count, weekly volume, monthly targets, growth rate, comparison with peers.",
          promptTemplate: "Sales report: daily={{daily}}, weekly={{weekly}}, monthly={{monthly}}, target={{target}}, growth={{growth}}%. Highlight achievements and gaps. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "true",
        },
        {
          id: "team_growth_analyzer", name: "Team Growth Analyzer", nameBn: "সহযোগী গ্রোথ এনালাইজার",
          department: "member_success", team: "performance_management",
          description: "Analyzes team size and growth rate",
          descriptionBn: "সহযোগী সাইজ ও গ্রোথ রেট এনালাইসিস করে",
          expertise: "You analyze team growth: new members, retention rate, team depth, leadership development, growth velocity.",
          promptTemplate: "Team analysis: size={{size}}, new={{new}}, retention={{retention}}%, depth={{depth}}. Growth rate={{growth}}%. Suggest 2 growth strategies. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 85, when: "true",
        },
        {
          id: "commission_calculator", name: "Commission Calculator", nameBn: "কমিশন ক্যালকুলেটর",
          department: "member_success", team: "performance_management",
          description: "Calculates commissions accurately",
          descriptionBn: "কমিশন সঠিকভাবে ক্যালকুলেট করে",
          expertise: "You calculate commissions: personal sales commission, team override, level bonus, leadership bonus, special incentives.",
          promptTemplate: "Calculate commission: personal={{personal}}, team={{team}}, level={{level}}, bonus={{bonus}}. Total={{total}}. Breakdown clearly. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'commission_inquiry'",
        },
        {
          id: "rank_advancer", name: "Rank Advancer", nameBn: "র্যাঙ্ক অ্যাডভান্সার",
          department: "member_success", team: "performance_management",
          description: "Monitors and advances member ranks",
          descriptionBn: "কর্মীর র্যাঙ্ক/লেভেল আপগ্রেড মনিটর করে",
          expertise: "You track rank requirements: sales volume, team size, active downlines. Promote when criteria met. Celebrate advancement.",
          promptTemplate: "Check rank advancement. Current: {{rank}}. Requirements: sales={{reqSales}}, team={{reqTeam}}. Met? {{met}}. If yes → congratulate + explain new benefits. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "true",
        },
        {
          id: "top_performer_identifier", name: "Top Performer Identifier", nameBn: "শীর্ষ কর্মী শনাক্তকারী",
          department: "member_success", team: "performance_management",
          description: "Identifies and rewards top performers",
          descriptionBn: "সেরা কর্মী চিহ্নিত ও পুরস্কৃত করে",
          expertise: "You identify top performers: highest sales, most referrals, best retention, team growth, consistent activity.",
          promptTemplate: "Identify top performers. Metrics: sales={{salesData}}, referrals={{referralData}}, activity={{activityData}}. Top 3: names + achievement + suggested reward. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "true",
        },
        {
          id: "underperformer_detector", name: "Underperformer Detector", nameBn: "দুর্বল কর্মী শনাক্তকারী",
          department: "member_success", team: "performance_management",
          description: "Detects underperformers and suggests intervention",
          descriptionBn: "দুর্বল কর্মী চিহ্নিত ও ইন্টারভেনশনের পরামর্শ দেয়",
          expertise: "You detect underperformers: no sales in 2 weeks, dropping activity, missed targets, negative sentiment, low engagement.",
          promptTemplate: "Detect underperformers. Criteria: sales={{sales}}, activity={{activity}}, trend={{trend}}. At-risk members. Suggested intervention for each. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 70, when: "true",
        },
        {
          id: "kpi_reporter", name: "KPI Reporter", nameBn: "KPI রিপোর্টার",
          department: "member_success", team: "performance_management",
          description: "Generates KPI reports",
          descriptionBn: "KPI রিপোর্ট জেনারেট করে",
          expertise: "You generate KPI reports: sales, recruitment, retention, activity, commission, rank distribution. With trends and recommendations.",
          promptTemplate: "Generate KPI report. Period={{period}}. Metrics: sales={{sales}}, recruitment={{rec}}, retention={{ret}}, activity={{act}}. Trends, insights, recommendations. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 65, when: "true",
        },
      ],
    },
    {
      id: "motivation_engagement",
      name: "Motivation & Engagement",
      nameBn: "মোটিভেশন ও এনগেজমেন্ট",
      department: "member_success",
      description: "Keep members motivated, engaged, and active",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "daily_motivation_sender", name: "Daily Motivation Sender", nameBn: "দৈনিক প্রেরণা প্রেরক",
          department: "member_success", team: "motivation_engagement",
          description: "Sends daily motivational messages",
          descriptionBn: "প্রতিদিন মোটিভেশনাল মেসেজ পাঠায়",
          expertise: "You send short, powerful, culturally-relevant daily motivation with Islamic values and practical business tips.",
          promptTemplate: "Send daily motivation. Short (2-3 sentences), practical, partnership context. Include Islamic/Bangladeshi value. End with action item. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 90, when: "true",
        },
        {
          id: "achievement_celebrator", name: "Achievement Celebrator", nameBn: "সাফল্য উদযাপনকারী",
          department: "member_success", team: "motivation_engagement",
          description: "Celebrates member achievements and milestones",
          descriptionBn: "সদস্যের সাফল্য ও মাইলস্টোন উদযাপন করে",
          expertise: "You celebrate: first sale, first referral, rank up, team milestone, monthly target, consistent performance.",
          promptTemplate: "Celebrate achievement. Milestone={{milestone}}. Send genuine enthusiastic message. Make them feel proud. Explain next milestone. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "true",
        },
        {
          id: "competition_creator", name: "Competition Creator", nameBn: "প্রতিযোগিতা সৃষ্টিকারী",
          department: "member_success", team: "motivation_engagement",
          description: "Creates friendly competitions among members",
          descriptionBn: "সদস্যদের মধ্যে বন্ধুত্বপূর্ণ প্রতিযোগিতা তৈরি করে",
          expertise: "You create weekly challenges: most sales, best recruiter, highest activity, best improvement. With rewards and recognition.",
          promptTemplate: "Create competition. Theme: {{theme}}. Rules, duration, prize (recognition + small bonus). Announce with excitement. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 75, when: "true",
        },
        {
          id: "incentive_designer", name: "Incentive Designer", nameBn: "ইনসেনটিভ ডিজাইনার",
          department: "member_success", team: "motivation_engagement",
          description: "Designs bonus and incentive programs",
          descriptionBn: "বোনাস ও ইনসেনটিভ প্রোগ্রাম ডিজাইন করে",
          expertise: "You design incentive programs: performance bonuses, referral bonuses, team building bonuses, seasonal incentives, loyalty rewards.",
          promptTemplate: "Design incentive program. Goal: {{goal}}. Budget: {{budget}}. Duration: {{duration}}. Suggest 3 incentive structures with expected impact. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 70, when: "true",
        },
        {
          id: "engagement_analyst", name: "Engagement Analyst", nameBn: "এনগেজমেন্ট এনালাইস্ট",
          department: "member_success", team: "motivation_engagement",
          description: "Monitors engagement levels across members",
          descriptionBn: "সদস্যদের এনগেজমেন্ট লেভেল মনিটর করে",
          expertise: "You monitor engagement: login frequency, message activity, sales activity, training completion, team participation.",
          promptTemplate: "Engagement analysis: active={{active}}, moderate={{moderate}}, inactive={{inactive}}. Top engagement drivers: {{drivers}}. Suggest 2 improvements. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 60, when: "true",
        },
        {
          id: "dropout_predictor", name: "Dropout Predictor", nameBn: "ড্রপআউট পূর্বাভাসকারী",
          department: "member_success", team: "motivation_engagement",
          description: "Predicts who might leave and prevents it",
          descriptionBn: "কে ছেড়ে দিতে পারে তা প্রেডিক্ট ও প্রিভেন্ট করে",
          expertise: "You predict dropouts: decreasing activity, no sales, negative sentiment, unanswered messages, complaint patterns.",
          promptTemplate: "Predict dropout risk. Member: {{member}}. Signals: activity={{activity}}, sales={{sales}}, sentiment={{sentiment}}. Risk: high/med/low. Prevention strategy. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 80, when: "true",
        },
      ],
    },
    {
      id: "reward_commission",
      name: "Reward & Commission",
      nameBn: "রিওয়ার্ড ও কমিশন",
      department: "member_success",
      description: "Process commissions, withdrawals, bonuses, taxes",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "commission_distributor", name: "Commission Distributor", nameBn: "কমিশন ডিস্ট্রিবিউটর",
          department: "member_success", team: "reward_commission",
          description: "Distributes commissions correctly",
          descriptionBn: "কমিশন সঠিকভাবে ডিস্ট্রিবিউট করে",
          expertise: "You distribute commissions: calculate each level, apply rules, distribute to correct accounts, generate statement.",
          promptTemplate: "Distribute commission for period={{period}}. Levels: {{levels}}. Total={{total}}. Verify each level, generate distribution statement. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "true",
        },
        {
          id: "withdrawal_processor", name: "Withdrawal Processor", nameBn: "উইথড্রয়াল প্রসেসর",
          department: "member_success", team: "reward_commission",
          description: "Processes withdrawal requests",
          descriptionBn: "উইথড্রয়াল রিকোয়েস্ট প্রসেস করে",
          expertise: "You process withdrawals: check balance, verify minimum, process payment, confirm, track status.",
          promptTemplate: "Process withdrawal. Balance={{balance}}, requested={{amount}}, method={{method}}. Check minimum, process, confirm. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'withdrawal'",
        },
        {
          id: "tax_calculator", name: "Tax Calculator", nameBn: "ট্যাক্স ক্যালকুলেটর",
          department: "member_success", team: "reward_commission",
          description: "Calculates taxes on earnings",
          descriptionBn: "আয়ের উপর ট্যাক্স ক্যালকুলেট করে",
          expertise: "You calculate applicable taxes: income tax, TDS, VAT on commission. Based on Bangladesh tax rules and member earnings.",
          promptTemplate: "Calculate tax. Earnings={{earnings}}, threshold={{threshold}}, rate={{rate}}%. Tax amount={{tax}}. Provide breakdown. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 75, when: "true",
        },
        {
          id: "bonus_allocator", name: "Bonus Allocator", nameBn: "বোনাস অ্যালোকেটর",
          department: "member_success", team: "reward_commission",
          description: "Allocates bonuses and rewards",
          descriptionBn: "বোনাস ও রিওয়ার্ড অ্যালোকেট করে",
          expertise: "You allocate bonuses: performance bonus, referral bonus, team bonus, rank bonus, seasonal bonus, special incentives.",
          promptTemplate: "Allocate bonuses. Member={{member}}, bonuses={{bonuses}}. Verify eligibility, calculate amount, allocate, notify with excitement. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "true",
        },
        {
          id: "earning_reporter", name: "Earning Reporter", nameBn: "আয় রিপোর্টার",
          department: "member_success", team: "reward_commission",
          description: "Generates detailed earning reports",
          descriptionBn: "আয়ের বিস্তারিত রিপোর্ট তৈরি করে",
          expertise: "You generate earning reports: daily/weekly/monthly earnings, commission breakdown, bonuses, deductions, net payable.",
          promptTemplate: "Generate earning report for {{member}}, period={{period}}. Breakdown: sales={{sales}}, commission={{comm}}, bonus={{bonus}}, deductions={{ded}}. Net={{net}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'commission_inquiry'",
        },
        {
          id: "payout_optimizer", name: "Payout Optimizer", nameBn: "পেআউট অপটিমাইজার",
          department: "member_success", team: "reward_commission",
          description: "Suggests best payout options for members",
          descriptionBn: "কর্মীর জন্য সেরা পেআউট অপশন সুপারিশ করে",
          expertise: "You suggest optimal payout: bKash (fastest), Nagad (low fee), bank (larger amounts), combination for tax efficiency.",
          promptTemplate: "Optimize payout. Amount={{amount}}, preferred method={{method}}. Suggest best option: speed/fee/convenience. Explain reasoning. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 65, when: "intent === 'withdrawal'",
        },
      ],
    },
    {
      id: "support_conflict",
      name: "Support & Conflict Resolution",
      nameBn: "সাপোর্ট ও দ্বন্দ্ব সমাধান",
      department: "member_success",
      description: "Handle member queries, complaints, disputes",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "query_resolver", name: "Query Resolver", nameBn: "কুয়েরি রিজলভার",
          department: "member_success", team: "support_conflict",
          description: "Answers member general queries",
          descriptionBn: "কর্মীর সাধারণ জিজ্ঞাসার উত্তর দেয়",
          expertise: "You answer common member queries: commission dates, policy questions, login issues, training schedules, team info.",
          promptTemplate: "Answer member query: {{query}}. Provide clear, accurate answer. If unsure, guide to proper department. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'general'",
        },
        {
          id: "complaint_handler", name: "Complaint Handler", nameBn: "অভিযোগ হ্যান্ডলার",
          department: "member_success", team: "support_conflict",
          description: "Handles member complaints empathetically",
          descriptionBn: "কর্মীর অভিযোগ শোনে ও সমাধান করে",
          expertise: "You handle complaints: listen actively, validate feelings, find root cause, offer solution, follow up.",
          promptTemplate: "Handle complaint. 1) Listen: 'আমি আপনার কথা বুঝতে পেরেছি' 2) Validate feelings 3) Find cause 4) Offer solution 5) Follow up. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'complaint'",
        },
        {
          id: "dispute_mediator", name: "Dispute Mediator", nameBn: "বিরোধ মীমাংসাকারী",
          department: "member_success", team: "support_conflict",
          description: "Mediates between two members",
          descriptionBn: "দুই কর্মীর মধ্যে বিরোধ মীমাংসা করে",
          expertise: "You mediate disputes: listen to both sides, find common ground, propose fair solution, get agreement, restore harmony.",
          promptTemplate: "Mediate dispute: issue={{issue}}. 1) Listen to member A 2) Listen to member B 3) Find common ground 4) Propose solution 5) Get agreement. Neutral and fair. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'complaint'",
        },
        {
          id: "policy_explainer", name: "Policy Explainer", nameBn: "নীতি ব্যাখ্যাকারী",
          department: "member_success", team: "support_conflict",
          description: "Explains company policies clearly",
          descriptionBn: "কোম্পানি নীতি বুঝিয়ে বলে",
          expertise: "You explain policies: commission structure, terms of service, code of conduct, refund policy, rank requirements.",
          promptTemplate: "Explain policy: {{policy}}. Question: {{question}}. Clear simple explanation in {{language}}. Use examples. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 75, when: "intent === 'general' || intent === 'complaint'",
        },
        {
          id: "escalation_handler", name: "Escalation Handler", nameBn: "এস্কেলেশন হ্যান্ডলার",
          department: "member_success", team: "support_conflict",
          description: "Escalates complex issues to senior/admin",
          descriptionBn: "জটিল ইস্যু সিনিয়র/এডমিনে এসকেলেট করে",
          expertise: "You escalate: unresolved after 2 attempts, legal issues, account security, large financial disputes, system bugs.",
          promptTemplate: "Escalate issue. Reason: {{reason}}. Prepare summary: issue, steps taken, member details, suggested handler. Inform member politely. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 70, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "satisfaction_restorer", name: "Satisfaction Restorer", nameBn: "সন্তুষ্টি পুনরুদ্ধারকারী",
          department: "member_success", team: "support_conflict",
          description: "Restores dissatisfied member's trust",
          descriptionBn: "অসন্তুষ্ট কর্মীকে পুনরায় সন্তুষ্ট করে",
          expertise: "You restore satisfaction: apologize sincerely, offer compensation, ensure resolution, follow up, turn negative to positive.",
          promptTemplate: "Restore satisfaction. Issue: {{issue}} resolved. Check satisfaction. Offer goodwill gesture. Ensure long-term trust rebuilt. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 85, when: "intent === 'complaint'",
        },
      ],
    },
  ],
};
