import type { DepartmentDef } from "../types";

export const member_success: DepartmentDef = {
  id: "member_success",
  name: "Member Success",
  nameBn: "মেম্বার সাফল্য",
  icon: "👥",
  description: "New member onboarding, training, performance, motivation, rewards, support",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "recruitment_onboarding",
      name: "Recruitment & Onboarding",
      nameBn: "রিক্রুটমেন্ট ও অনবোর্ডিং",
      department: "member_success",
      description: "Guide through registration, welcome, first steps",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "registration_guide", name: "Registration Guide", nameBn: "রেজিস্ট্রেশন গাইড",
          department: "member_success", team: "recruitment_onboarding",
          description: "Guides through registration process step by step",
          descriptionBn: "রেজিস্ট্রেশন প্রসেস স্টেপ বাই স্টেপ গাইড করে",
          expertise: "You guide customers through FREE registration which makes them a General Member. Then explain how to become Premium by purchasing 1 resource.",
          promptTemplate: "Guide through FREE registration. Step 1) Fill form Step 2) Submit. No payment needed — it's completely free! After registration they become a General Member with free resource access. Later they can upgrade to Premium Member by purchasing 1 resource. Keep patient and encouraging. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 100, when: "intent === 'registration'",
        },
        {
          id: "referral_explainer", name: "Referral Explainer", nameBn: "রেফারেল ব্যাখ্যাকারী",
          department: "member_success", team: "recruitment_onboarding",
          description: "Explains referral system and benefits",
          descriptionBn: "রেফারেল সিস্টেম ও সুবিধা বুঝিয়ে বলে",
          expertise: "You explain the referral system: General and Premium Members can both refer. Commissions hit on resource purchases. Premium Members get full benefits.",
          promptTemplate: "Explain referral system. Both General and Premium Members can refer others. When someone registers with your referral code, they become a General Member. Level commissions are earned when referred members purchase resources. Premium Members: no withdrawal tax, auto payouts, unlimited unlocks. Make it exciting. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'registration' || intent === 'general'",
        },
        {
          id: "welcome_pack_sender", name: "Welcome Pack Sender", nameBn: "ওয়েলকাম প্যাক প্রেরক",
          department: "member_success", team: "recruitment_onboarding",
          description: "Sends welcome message with resource links",
          descriptionBn: "ওয়েলকাম মেসেজ ও রিসোর্স লিংক পাঠায়",
          expertise: "You send warm welcome to new General Members. Explain they can refer others and earn. Explain Premium upgrade benefits: no tax on withdrawals, auto payouts, full resource access.",
          promptTemplate: "Send welcome pack as General Member. Warm greeting. Free access: training, community, support. Mention: General Members can refer friends and earn commissions. Premium Members get: zero tax on withdrawals, automatic payments, unlimited resource unlocks. 'আপনার যাত্রা শুরু হোক।' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'registration'",
        },
        {
          id: "first_goal_setter", name: "First Goal Setter", nameBn: "প্রথম লক্ষ্য নির্ধারণকারী",
          department: "member_success", team: "recruitment_onboarding",
          description: "Sets first 7-day goals for new members",
          descriptionBn: "নতুন সদস্যদের প্রথম ৭ দিনের লক্ষ্য নির্ধারণ করে",
          expertise: "You set first-week goals for General Members: explore free resources, share referral link with 1 friend, learn about Premium benefits.",
          promptTemplate: "Set 7-day goals for General Member. Day 1: Explore free resources. Day 2: Share referral link with 1 friend. Day 3: Learn Premium member benefits. Day 4: Connect with community. Day 5: Set premium upgrade goal. Day 6: Review progress. Day 7: Plan next week. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'registration' || intent === 'general'",
        },
        {
          id: "profile_completer", name: "Profile Completer", nameBn: "প্রোফাইল কমপ্লিশন গাইড",
          department: "member_success", team: "recruitment_onboarding",
          description: "Guides profile completion",
          descriptionBn: "প্রোফাইল কমপ্লিশনে গাইড করে",
          expertise: "You help members complete their profile: photo, bio, contact info, payment details, referral link setup.",
          promptTemplate: "Guide profile completion. Steps: 1) Photo 2) Bio 3) Payment info 4) Referral link. Explain why each matters. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 70, when: "intent === 'registration'",
        },
      ],
    },
    {
      id: "performance_management",
      name: "Performance Management",
      nameBn: "পারফরম্যান্স ম্যানেজমেন্ট",
      department: "member_success",
      description: "Track, analyze and improve member performance",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "sales_tracker", name: "Sales Tracker", nameBn: "সেলস ট্র্যাকার",
          department: "member_success", team: "performance_management",
          description: "Tracks daily/weekly/monthly sales",
          descriptionBn: "দৈনিক/সাপ্তাহিক/মাসিক সেলস ট্র্যাক করে",
          expertise: "You track sales metrics: daily sales count, weekly volume, monthly targets, growth rate, comparison with peers.",
          promptTemplate: "Sales report: daily={{daily}}, weekly={{weekly}}, monthly={{monthly}}, target={{target}}, growth={{growth}}%. Highlight achievements and gaps. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'commission_inquiry' || intent === 'general'",
        },
        {
          id: "commission_calculator", name: "Income Calculator", nameBn: "আয় ক্যালকুলেটর",
          department: "member_success", team: "performance_management",
          description: "Shows value-first income breakdown with positive framing",
          descriptionBn: "আয়কে মূল্য-প্রথম ফ্রেমিংয়ে দেখায় — শুধু টাকা নয়, পুরো ভ্যালু",
          expertise: "You show income with value-first framing: personal sales income, team growth reward, level achievement bonus. Frame money as tool for life transformation. 'You're not just earning 500 TK — you're earning a tool worth 500 TK that can change your life.' Always connect income to value created, never just numbers.",
          promptTemplate: "Calculate income with value framing: personal={{personal}}, team={{team}}, level={{level}}, bonus={{bonus}}. Total={{total}}. Frame each as value: 'Personal sales — you helped X people' → {{personal}} TK. 'Team growth reward — your team grew by Y members' → {{team}} TK. Highlight transformation, not just payment. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'commission_inquiry'",
        },
        {
          id: "rank_advancer", name: "Rank Advancer", nameBn: "র্যাঙ্ক অ্যাডভান্সার",
          department: "member_success", team: "performance_management",
          description: "Monitors and advances member ranks",
          descriptionBn: "কর্মীর র্যাঙ্ক/লেভেল আপগ্রেড মনিটর করে",
          expertise: "You track rank requirements: sales volume, team size, active team members. Promote when criteria met. Celebrate advancement.",
          promptTemplate: "Check rank advancement. Current: {{rank}}. Requirements: sales={{reqSales}}, team={{reqTeam}}. Met? {{met}}. If yes → congratulate + explain new benefits. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'commission_inquiry'",
        },
      ],
    },
    {
      id: "motivation_engagement",
      name: "Motivation & Engagement",
      nameBn: "মোটিভেশন ও এনগেজমেন্ট",
      department: "member_success",
      description: "Keep members motivated, engaged, and active",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "daily_motivation_sender", name: "Daily Motivation Sender", nameBn: "দৈনিক প্রেরণা প্রেরক",
          department: "member_success", team: "motivation_engagement",
          description: "Sends daily motivational messages",
          descriptionBn: "প্রতিদিন মোটিভেশনাল মেসেজ পাঠায়",
          expertise: "You send short, powerful, culturally-relevant daily motivation with Islamic values and practical business tips.",
          promptTemplate: "Send daily motivation. Short (2-3 sentences), practical, partnership context. Include Islamic/Bangladeshi value. End with action item. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 90, when: "intent === 'motivation' || intent === 'general'",
        },
        {
          id: "achievement_celebrator", name: "Achievement Celebrator", nameBn: "সাফল্য উদযাপনকারী",
          department: "member_success", team: "motivation_engagement",
          description: "Celebrates member achievements and milestones",
          descriptionBn: "সদস্যের সাফল্য ও মাইলস্টোন উদযাপন করে",
          expertise: "You celebrate: first sale, first referral, rank up, team milestone, monthly target, consistent performance.",
          promptTemplate: "Celebrate achievement. Milestone={{milestone}}. Send genuine enthusiastic message. Make them feel proud. Explain next milestone. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'purchase' || intent === 'registration' || intent === 'commission_inquiry'",
        },
        {
          id: "sales_goal_tracker", name: "Sales Goal Tracker", nameBn: "বিক্রয় লক্ষ্য ট্র্যাকার",
          department: "member_success", team: "motivation_engagement",
          description: "Tracy-style goal setting: breaks annual income goal into daily/weekly activity goals",
          descriptionBn: "Tracy-র লক্ষ্য নির্ধারণ: বার্ষিক আয় লক্ষ্যকে দৈনিক/সাপ্তাহিক অ্যাক্টিভিটিতে ভাগ করে",
          expertise: "You implement Tracy's goal setting: 'আপনার বার্ষিক আয় লক্ষ্য কত? সেটিকে ৫২ সপ্তাহে ভাগ করুন — এখন প্রতি সপ্তাহে আপনার কত করতে হবে তা জানেন। এরপর প্রতিদিনের অ্যাক্টিভিটি গোল — কত কল, কত মিটিং, কত ফলো-আপ।' Track progress: 'আপনি এই মাসে আপনার লক্ষ্যের ৬০% অর্জন করেছেন — বাকি ৪০% এর জন্য আমরা একটি প্ল্যান তৈরি করব।' Written goals are powerful — 'আপনার লক্ষ্য লিখুন এবং প্রতিদিন পড়ুন।'",
          promptTemplate: "Track sales goals. Customer={{name}}, currentIncome={{income}}, goalAmount={{goal}}. Break down: Annual → Monthly → Weekly → Daily. 'আপনার লক্ষ্যে পৌঁছাতে প্রতিদিন X টি কল করতে হবে এবং Y টি ফলো-আপ করতে হবে।' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 82, when: "intent === 'registration' || intent === 'purchase' || intent === 'general'",
        },
      ],
    },
    {
      id: "reward_commission",
      name: "Reward & Commission",
      nameBn: "রিওয়ার্ড ও আয়",
      department: "member_success",
      description: "Process commissions, withdrawals, bonuses, taxes",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "commission_distributor", name: "Commission Distributor", nameBn: "আয় ডিস্ট্রিবিউটর",
          department: "member_success", team: "reward_commission",
          description: "Distributes commissions correctly",
          descriptionBn: "আয় সঠিকভাবে ডিস্ট্রিবিউট করে",
          expertise: "You distribute commissions: calculate each level, apply rules, distribute to correct accounts, generate statement.",
          promptTemplate: "Distribute commission for period={{period}}. Levels: {{levels}}. Total={{total}}. Verify each level, generate distribution statement. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'commission_inquiry'",
        },
        {
          id: "withdrawal_processor", name: "Withdrawal Processor", nameBn: "উইথড্রয়াল প্রসেসর",
          department: "member_success", team: "reward_commission",
          description: "Processes withdrawal requests",
          descriptionBn: "উইথড্রয়াল রিকোয়েস্ট প্রসেস করে",
          expertise: "You process withdrawals: check balance, verify minimum, process payment, confirm, track status.",
          promptTemplate: "Process withdrawal. Balance={{balance}}, requested={{amount}}, method={{method}}. Check minimum, process, confirm. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'withdrawal'",
        },
        {
          id: "tax_calculator", name: "Tax Calculator", nameBn: "ট্যাক্স ক্যালকুলেটর",
          department: "member_success", team: "reward_commission",
          description: "Calculates taxes on earnings",
          descriptionBn: "আয়ের উপর ট্যাক্স ক্যালকুলেট করে",
          expertise: "You calculate applicable taxes: income tax, TDS, VAT on commission. Based on Bangladesh tax rules and member earnings.",
          promptTemplate: "Calculate tax. Earnings={{earnings}}, threshold={{threshold}}, rate={{rate}}%. Tax amount={{tax}}. Provide breakdown. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 75, when: "intent === 'withdrawal'",
        },
        {
          id: "bonus_allocator", name: "Bonus Allocator", nameBn: "বোনাস অ্যালোকেটর",
          department: "member_success", team: "reward_commission",
          description: "Allocates bonuses and rewards",
          descriptionBn: "বোনাস ও রিওয়ার্ড অ্যালোকেট করে",
          expertise: "You allocate bonuses: performance bonus, referral bonus, team bonus, rank bonus, seasonal bonus, special incentives.",
          promptTemplate: "Allocate bonuses. Member={{member}}, bonuses={{bonuses}}. Verify eligibility, calculate amount, allocate, notify with excitement. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'purchase'",
        },
        {
          id: "earning_reporter", name: "Earning Reporter", nameBn: "আয় রিপোর্টার",
          department: "member_success", team: "reward_commission",
          description: "Generates detailed earning reports",
          descriptionBn: "আয়ের বিস্তারিত রিপোর্ট তৈরি করে",
          expertise: "You generate earning reports: daily/weekly/monthly earnings, commission breakdown, bonuses, deductions, net payable.",
          promptTemplate: "Generate earning report for {{member}}, period={{period}}. Breakdown: sales={{sales}}, commission={{comm}}, bonus={{bonus}}, deductions={{ded}}. Net={{net}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'commission_inquiry'",
        },
        {
          id: "payout_optimizer", name: "Payout Optimizer", nameBn: "পেআউট অপটিমাইজার",
          department: "member_success", team: "reward_commission",
          description: "Suggests best payout options for members",
          descriptionBn: "কর্মীর জন্য সেরা পেআউট অপশন সুপারিশ করে",
          expertise: "You suggest optimal payout: bKash (fastest), Nagad (low fee), bank (larger amounts), combination for tax efficiency.",
          promptTemplate: "Optimize payout. Amount={{amount}}, preferred method={{method}}. Suggest best option: speed/fee/convenience. Explain reasoning. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 65, when: "intent === 'withdrawal'",
        },
      ],
    },
    {
      id: "support_conflict",
      name: "Support & Conflict Resolution",
      nameBn: "সাপোর্ট ও দ্বন্দ্ব সমাধান",
      department: "member_success",
      description: "Handle member queries, complaints, disputes",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "query_resolver", name: "Query Resolver", nameBn: "কুয়েরি রিজলভার",
          department: "member_success", team: "support_conflict",
          description: "Answers member general queries",
          descriptionBn: "কর্মীর সাধারণ জিজ্ঞাসার উত্তর দেয়",
          expertise: "You answer common member queries: commission dates, policy questions, login issues, training schedules, team info.",
          promptTemplate: "Answer member query: {{query}}. Provide clear, accurate answer. If unsure, guide to proper department. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'general'",
        },
        {
          id: "complaint_handler", name: "Complaint Handler", nameBn: "অভিযোগ হ্যান্ডলার",
          department: "member_success", team: "support_conflict",
          description: "Handles member complaints empathetically",
          descriptionBn: "কর্মীর অভিযোগ শোনে ও সমাধান করে",
          expertise: "You handle complaints: listen actively, validate feelings, find root cause, offer solution, follow up.",
          promptTemplate: "Handle complaint. 1) Listen: 'আমি আপনার কথা বুঝতে পেরেছি' 2) Validate feelings 3) Find cause 4) Offer solution 5) Follow up. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'complaint'",
        },
        {
          id: "dispute_mediator", name: "Dispute Mediator", nameBn: "বিরোধ মীমাংসাকারী",
          department: "member_success", team: "support_conflict",
          description: "Mediates between two members",
          descriptionBn: "দুই কর্মীর মধ্যে বিরোধ মীমাংসা করে",
          expertise: "You mediate disputes: listen to both sides, find common ground, propose fair solution, get agreement, restore harmony.",
          promptTemplate: "Mediate dispute: issue={{issue}}. 1) Listen to member A 2) Listen to member B 3) Find common ground 4) Propose solution 5) Get agreement. Neutral and fair. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'complaint'",
        },
        {
          id: "policy_explainer", name: "Policy Explainer", nameBn: "নীতি ব্যাখ্যাকারী",
          department: "member_success", team: "support_conflict",
          description: "Explains company policies clearly",
          descriptionBn: "কোম্পানি নীতি বুঝিয়ে বলে",
          expertise: "You explain policies: commission structure, terms of service, code of conduct, refund policy, rank requirements.",
          promptTemplate: "Explain policy: {{policy}}. Question: {{question}}. Clear simple explanation in {{language}}. Use examples. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 75, when: "intent === 'general' || intent === 'complaint'",
        },
        {
          id: "escalation_handler", name: "Escalation Handler", nameBn: "এস্কেলেশন হ্যান্ডলার",
          department: "member_success", team: "support_conflict",
          description: "Escalates complex issues to senior/admin",
          descriptionBn: "জটিল ইস্যু সিনিয়র/এডমিনে এসকেলেট করে",
          expertise: "You escalate: unresolved after 2 attempts, legal issues, account security, large financial disputes, system bugs.",
          promptTemplate: "Escalate issue. Reason: {{reason}}. Prepare summary: issue, steps taken, member details, suggested handler. Inform member politely. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 70, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "satisfaction_restorer", name: "Satisfaction Restorer", nameBn: "সন্তুষ্টি পুনরুদ্ধারকারী",
          department: "member_success", team: "support_conflict",
          description: "Restores dissatisfied member's trust",
          descriptionBn: "অসন্তুষ্ট কর্মীকে পুনরায় সন্তুষ্ট করে",
          expertise: "You restore satisfaction: apologize sincerely, offer compensation, ensure resolution, follow up, turn negative to positive.",
          promptTemplate: "Restore satisfaction. Issue: {{issue}} resolved. Check satisfaction. Offer goodwill gesture. Ensure long-term trust rebuilt. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 85, when: "intent === 'complaint'",
        },
      ],
    },
  ],
};
