import type { DepartmentDef } from "../types";

export const negativity_detection: DepartmentDef = {
  id: "negativity_detection",
  name: "Negativity Detection & Sensitivity",
  nameBn: "নেতিবাচকতা সনাক্তকরণ ও সংবেদনশীলতা",
  icon: "⚠️",
  description: "Detects negative sentiment triggers in Bangladeshi context, advises other departments on safe wording, maintains knowledge base of cultural sensitivities",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "trigger_analysis",
      name: "Trigger Word Analysis",
      nameBn: "ট্রিগার শব্দ বিশ্লেষণ",
      department: "negativity_detection",
      description: "Identifies words and phrases that trigger negative reactions in Bangladeshi audience",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "mlm_trigger_detector", name: "Recruitment Trigger Detector", nameBn: "রিক্রুটমেন্ট ট্রিগার শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects recruitment, network marketing, team building related negative triggers",
          descriptionBn: "রিক্রুটমেন্ট, নেটওয়ার্ক মার্কেটিং, সহযোগী বিল্ডিং সংক্রান্ত নেতিবাচক ট্রিগার শনাক্ত করে",
          expertise: "You specialize in detecting words like recruitment, network marketing, chain marketing, multi-level that trigger strong negative reactions in Bangladesh.",
          promptTemplate: "Analyze the conversation for recruitment/network marketing negative triggers. Words like 'রিক্রুটমেন্ট', 'network marketing', 'multi-level', 'chain', 'pyramid' trigger extreme negativity in Bangladesh. If detected, flag with severity and suggest alternative wording. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 95, when: "intent === 'purchase' || intent === 'referral' || intent === 'registration'",
        },
        {
          id: "recruitment_trigger_detector", name: "Recruitment Trigger Detector", nameBn: "রিক্রুটমেন্ট ট্রিগার শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects negative triggers around member recruitment, joining, bringing people in",
          descriptionBn: "সদস্য বানানো, লোক ঢুকানো, জয়েন করানো সংক্রান্ত নেতিবাচক ট্রিগার শনাক্ত করে",
          expertise: "You detect when recruitment language triggers suspicion. 'লোক ঢুকানো', 'সদস্য বানানো', 'জয়েন করানো' are highly negative in Bangladeshi context due to recruitment scams.",
          promptTemplate: "Check for recruitment-related negative triggers. Phrases like 'লোক ঢুকানো', 'সদস্য বানানো', 'জয়েন করানো', 'bring people in', 'recruit members' trigger scam suspicion in Bangladesh. Flag and suggest positive alternatives like 'partner', 'join our team', 'grow together'. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 94, when: "intent === 'referral' || intent === 'registration' || intent === 'general'",
        },
        {
          id: "money_trigger_detector", name: "Money Trust Trigger Detector", nameBn: "টাকা বিশ্বাস ট্রিগার শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects negative triggers around money, payment, investment, commission",
          descriptionBn: "টাকা, পেমেন্ট, বিনিয়োগ, কমিশন সংক্রান্ত নেতিবাচক ট্রিগার শনাক্ত করে",
          expertise: "You detect money-related suspicion triggers. Bangladeshis are highly skeptical of advance payment, registration fees, investment promises, unrealistic commission claims.",
          promptTemplate: "Scan for money-related negative triggers: 'advance payment', 'registration fee', 'investment', 'guaranteed return', 'বিনিয়োগ', 'কমিশন', 'রেজিস্ট্রেশন ফি'. These trigger scam fear in Bangladesh. Flag severity and suggest trust-building alternatives. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 93, when: "intent === 'purchase' || intent === 'commission_inquiry' || intent === 'withdrawal'",
        },
        {
          id: "trust_betrayal_detector", name: "Trust Betrayal Detector", nameBn: "বিশ্বাসঘাতকতা শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects when customer feels trust has been betrayed — critical churn signal",
          descriptionBn: "গ্রাহক কখন বিশ্বাসঘাতকতা অনুভব করে তা চিহ্নিত করে — সমালোচনামূলক চার্ন সংকেত",
          expertise: "You detect trust betrayal signals: 'আপনি আগে অন্যরকম বলেছিলেন', 'আমাকে মিথ্যা বলা হয়েছে', 'আপনাদের কথা আর বিশ্বাস হয় না', 'এটা তো প্রতারণা'. These are HIGH urgency signals requiring immediate trust repair.",
          promptTemplate: "SCAN for trust betrayal signals. ALERT if detected: 'বিশ্বাস ভেঙে গেছে', 'আপনারা মিথ্যা বলেছেন', 'প্রতারণা', 'ধোঁকা', 'বিশ্বাসঘাতকতা'. Severity: CRITICAL/HIGH/MEDIUM/LOW. If CRITICAL or HIGH → immediate trust repair protocol. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 100, when: "intent === 'complaint' || intent === 'support' || intent === 'feedback'",
        },
        {
          id: "fear_escalation_detector", name: "Fear Escalation Detector", nameBn: "ভয় বৃদ্ধি শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects when customer's fear is escalating — critical distress signal",
          descriptionBn: "গ্রাহকের ভয় কখন বাড়ছে তা সনাক্ত করে — সমালোচনামূলক দুর্দশা সংকেত",
          expertise: "You detect fear escalation: from curiosity → to worry → to panic. 'হবে তো?' → 'আমি তো ভয় পাচ্ছি' → 'আমার টাকা নিয়ে কি হবে?' Escalating fear needs immediate calming + reassurance.",
          promptTemplate: "Detect fear escalation. Stage: initial_curiosity/worry/panic. Customer signs: 'হবে তো?' = worry, 'ভয় পাচ্ছি' = high, 'টাকা নিয়ে কি হবে' = panic. If panic → immediate reassurance protocol. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'price_inquiry' || intent === 'purchase' || intent === 'general'",
        },
      ],
    },
    {
      id: "conversation_analysis",
      name: "Conversation Sentiment Analysis",
      nameBn: "কনভারসেশন সেন্টিমেন্ট বিশ্লেষণ",
      department: "negativity_detection",
      description: "Analyzes full conversations for negative sentiment patterns and trust barriers",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b"],
      agents: [
        {
          id: "sentiment_negativity_scanner", name: "Sentiment Negativity Scanner", nameBn: "সেন্টিমেন্ট নেতিবাচকতা স্ক্যানার",
          department: "negativity_detection", team: "conversation_analysis",
          description: "Scans conversation history for negative sentiment patterns and trust barriers specific to Bangladesh",
          descriptionBn: "কনভারসেশন ইতিহাসে বাংলাদেশের প্রেক্ষাপটে নেতিবাচক সেন্টিমেন্ট প্যাটার্ন ও বিশ্বাসের বাধা খুঁজে বের করে",
          expertise: "You analyze conversation patterns to identify when a Bangladeshi customer is showing distrust, skepticism, or negativity about specific topics.",
          promptTemplate: "Analyze this conversation for negative sentiment patterns specific to Bangladesh. Look for: distrust ('বিশ্বাস হচ্ছে না', 'scam'), skepticism ('খুব ভালো লাগছে না'), fear ('ভয়', 'risk'), past bad experience ('আগে প্রতারিত'), comparison with scams ('রিক্রুটমেন্ট এর মত'). Return detected issues with severity. Conversation: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "trust_barrier_identifier", name: "Trust Barrier Identifier", nameBn: "বিশ্বাস বাধা শনাক্তকারী",
          department: "negativity_detection", team: "conversation_analysis",
          description: "Identifies specific trust barriers Bangladeshi customers have about the business model",
          descriptionBn: "বাংলাদেশী গ্রাহকদের বিজনেস মডেল সম্পর্কে নির্দিষ্ট বিশ্বাসের বাধা চিহ্নিত করে",
          expertise: "You identify trust barriers: 'এটা কি রিক্রুটমেন্ট?', 'আমি কি টাকা দিয়ে জয়েন করব?', 'কমিশন কত?', 'কোম্পানি কি বৈধ?' — these questions indicate distrust.",
          promptTemplate: "Identify trust barriers the customer is expressing. Common Bangladeshi trust barriers: legality concerns ('বৈধ কিনা'), Recruitment fear ('রিক্রুটমেন্ট কিনা'), money loss fear ('টাকা ডুবে যাবে'), upfront payment hesitation, company legitimacy doubt. Categorize each barrier. Customer message: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 89, when: "true",
        },
        {
          id: "control_feeling_detector", name: "Control Feeling Detector", nameBn: "নিয়ন্ত্রণ অনুভূতি শনাক্তকারী",
          department: "negativity_detection", team: "conversation_analysis",
          description: "Detects when customer feels pressured/controlled — trust erosion signal",
          descriptionBn: "গ্রাহক কখন চাপ/নিয়ন্ত্রণ অনুভব করে তা শনাক্ত করে — বিশ্বাস ক্ষয়ের সংকেত",
          expertise: "You detect control feelings: 'আমাকে চাপ দিচ্ছেন কেন?', 'আমি নিজে বুঝব', 'আজকেই করতে হবে?', 'আমি বলেছি পরে', 'জোর করবেন না'. These are RED FLAGS — immediately stop all push and give autonomy.",
          promptTemplate: "DETECT control/pressure feelings. RED FLAGS: 'চাপ দিচ্ছেন', 'জোর করছেন', 'আমি নিজে বুঝব', 'বলেছি তো পরে', 'আমাকে বিরক্ত করবেন না'. Severity: CRITICAL(HIGH)/MEDIUM/LOW. If CRITICAL → immediately stop, apologize, give space. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 97, when: "true",
        },
        {
          id: "mask_crack_detector", name: "Mask Crack Detector", nameBn: "মুখোশ ফাটল শনাক্তকারী",
          department: "negativity_detection", team: "conversation_analysis",
          description: "Detects when customer's mask cracks — opportunity to build deeper connection",
          descriptionBn: "গ্রাহকের মুখোশ কখন ফাটে তা শনাক্ত করে — গভীর সংযোগ স্থাপনের সুযোগ",
          expertise: "You detect mask cracks: customer was being polite/positive → suddenly shows frustration, doubt, or real emotion. 'আসলে বলতে কি...', 'সত্যি কথা বলতে...', 'আপনারই বলি...'. This is a GOOD sign — they're lowering their guard.",
          promptTemplate: "DETECT mask cracks. Customer shifts from polite/positive to real/emotional. Signal: 'আসলে', 'সত্যি কথা', 'আপনারই বলি', 'ভিতরে ভিতরে', honest admission of doubt/fear/worry. If detected → honor the vulnerability, provide safe space, deepen connection. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 88, when: "true",
        },
        {
          id: "manipulation_attempt_detector", name: "Manipulation Attempt Detector", nameBn: "ম্যানিপুলেশন প্রচেষ্টা শনাক্তকারী",
          department: "negativity_detection", team: "conversation_analysis",
          description: "Detects if someone is trying to manipulate the customer — external threat detection",
          descriptionBn: "কেউ গ্রাহককে ম্যানিপুলেট করার চেষ্টা করছে কিনা তা শনাক্ত করে — বাহ্যিক হুমকি সনাক্তকরণ",
          expertise: "You detect if someone is manipulating the customer (competitor, other agent, bad actor): 'অন্য কোম্পানি বলেছে এটা স্ক্যাম', 'আমার বন্ধু বলেছে না করতে', 'একজন ভদ্রলোক বললেন...'. Alert if customer is being misled by external sources.",
          promptTemplate: "SCAN for external manipulation. Is customer repeating claims from others? 'লোকজন বলে', 'বন্ধু বলেছে', 'সবাই জানে', 'একজন বললেন', 'ফেসবুকে দেখেছি'. If detected: gently correct misinformation without attacking the source. 'আমি বুঝি অনেকে নানা কথা বলে, কিন্তু আসল তথ্য হলো...' Context: {{context}}. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'general' || intent === 'price_inquiry' || intent === 'product_inquiry'",
        },
      ],
    },
    {
      id: "sensitivity_advisory",
      name: "Sensitivity Advisory",
      nameBn: "সংবেদনশীলতা পরামর্শ",
      department: "negativity_detection",
      description: "Advises other departments (Psychology, Sales, Member Success) on safe wording and approach",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b"],
      agents: [
        {
          id: "safe_wording_advisor", name: "Safe Wording Advisor", nameBn: "নিরাপদ শব্দচয়ন উপদেষ্টা",
          department: "negativity_detection", team: "sensitivity_advisory",
          description: "Suggests alternative positive wording for sensitive topics",
          descriptionBn: "সংবেদনশীল বিষয়ের জন্য বিকল্প পজেটিভ শব্দচয়নের পরামর্শ দেয়",
          expertise: "You advise on safe wording. Instead of 'recruitment plan' say 'partner program'. Instead of 'bring people' say 'grow together'. Instead of 'commission' say 'earnings'.",
          promptTemplate: "Review the drafted response for potentially negative wording. Suggest alternatives for any problematic phrases. Consider: recruitment-equivalent words, recruitment language, money promises, urgency pressure, guarantee claims. Original response: {{previousOutput}}. Detected triggers: {{context}}. Provide revised safe version. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["gpt-5.4-mini"],
          tier: 1, priority: 97, when: "true",
        },
        {
          id: "cultural_sensitivity_checker", name: "Cultural Sensitivity Checker", nameBn: "সাংস্কৃতিক সংবেদনশীলতা পরীক্ষক",
          department: "negativity_detection", team: "sensitivity_advisory",
          description: "Checks response for Islamic and Bangladeshi cultural sensitivity",
          descriptionBn: "ইসলামিক ও বাংলাদেশী সাংস্কৃতিক সংবেদনশীলতার জন্য উত্তর পরীক্ষা করে",
          expertise: "You ensure responses respect Islamic values, Bangladeshi social norms, and avoid culturally insensitive content.",
          promptTemplate: "Check this response for cultural sensitivity in Bangladeshi/Islamic context. Flag issues with: Islamic values (interest/riba, haram content, modesty), Bangladeshi social norms (respect for elders, family values), political sensitivity, religious sensitivity. Provide corrected version if issues found. Response: {{previousOutput}}. Customer: {{context}}. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["gpt-5.4-mini"],
          tier: 1, priority: 98, when: "true",
        },
      ],
    },
    {
      id: "negativity_recovery",
      name: "Negativity Recovery & Resolution",
      nameBn: "নেতিবাচকতা পুনরুদ্ধার ও সমাধান",
      department: "negativity_detection",
      description: "Listen to complaints, find root causes, craft solutions, resolve conflicts",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b"],
      agents: [
        {
          id: "complaint_listener", name: "Complaint Listener", nameBn: "অভিযোগ শ্রোতা",
          department: "negativity_detection", team: "negativity_recovery",
          description: "Listens empathetically to customer complaints and detects underlying negativity",
          descriptionBn: "গ্রাহকের অভিযোগ সহানুভূতির সাথে শুনে এবং অন্তর্নিহিত নেতিবাচকতা সনাক্ত করে",
          expertise: "You listen to complaints empathetically, validate feelings, and detect the true negative sentiment beneath surface anger.",
          promptTemplate: "Listen to this complaint. Validate the customer's feelings first. Then identify the underlying negative sentiment: is it distrust, disappointment, confusion, or fear? Extract the core issue without being defensive. Customer message: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 96, when: "intent === 'complaint' || intent === 'support'",
        },
        {
          id: "root_cause_finder", name: "Root Cause Finder", nameBn: "মূল কারণ অনুসন্ধানকারী",
          department: "negativity_detection", team: "negativity_recovery",
          description: "Finds the root cause of complaints and negative reactions in Bangladeshi context",
          descriptionBn: "বাংলাদেশী প্রেক্ষাপটে অভিযোগ ও নেতিবাচক প্রতিক্রিয়ার মূল কারণ খুঁজে বের করে",
          expertise: "You dig deeper to find the real root cause: past bad experience, cultural misunderstanding, unmet expectation, or genuine product issue.",
          promptTemplate: "Find the root cause of this negativity. Categories: past scam experience, cultural misunderstanding, unmet expectation, pricing confusion, trust issue from recruitment fear, genuine product complaint. Customer: {{previousOutput}}. Detect which category and provide evidence. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 92, when: "intent === 'complaint' || intent === 'support' || intent === 'feedback'",
        },
        {
          id: "solution_crafter", name: "Solution Crafter", nameBn: "সমাধান নির্মাতা",
          department: "negativity_detection", team: "negativity_recovery",
          description: "Crafts specific solutions to address identified negativity and restore trust",
          descriptionBn: "শনাক্ত নেতিবাচকতা মোকাবিলা ও বিশ্বাস পুনরুদ্ধারের জন্য নির্দিষ্ট সমাধান তৈরি করে",
          expertise: "You craft tailored solutions: for distrust → proof and transparency; for confusion → clear explanation; for disappointment → compensation/apology; for fear → risk reversal.",
          promptTemplate: "Craft a solution for the identified issue. Root cause: {{previousOutput}}. Issue type: {{context}}. Provide: 1) Immediate acknowledgment 2) Specific fix/compensation 3) Trust restoration step. Bangladesh context. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 90, when: "intent === 'complaint' || intent === 'support'",
        },
        {
          id: "conflict_resolver", name: "Conflict Resolver", nameBn: "দ্বন্দ্ব সমাধানকারী",
          department: "negativity_detection", team: "negativity_recovery",
          description: "Resolves escalated conflicts and prevents customer churn through conversation",
          descriptionBn: "উত্তীর্ণ দ্বন্দ্ব সমাধান করে এবং কথোপকথনের মাধ্যমে গ্রাহক চলে যাওয়া প্রতিরোধ করে",
          expertise: "You de-escalate conflicts: stay calm, acknowledge the issue, find common ground, propose a fair resolution, and leave the door open for future conversation.",
          promptTemplate: "De-escalate this conflict. Steps: 1) Acknowledge without blaming 2) Find common ground ('আমরা দুজনই চাই আপনার সাফল্য') 3) Propose fair resolution 4) Offer compensation if warranted 5) Leave door open. Customer: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["gpt-5.4-mini"],
          tier: 1, priority: 88, when: "intent === 'complaint' || intent === 'support'",
        },
        {
          id: "training_assigner", name: "Training Skill Assigner", nameBn: "প্রশিক্ষণ দক্ষতা নির্ধারক",
          department: "negativity_detection", team: "negativity_recovery",
          description: "Assigns relevant training/skills to help members overcome skill gaps causing friction",
          descriptionBn: "সদস্যদের দক্ষতার ঘাটতি দূর করতে প্রাসঙ্গিক প্রশিক্ষণ নির্ধারণ করে যা ঘর্ষণ সৃষ্টি করছে",
          expertise: "You identify skill gaps causing member frustration and assign appropriate training resources to help them succeed.",
          promptTemplate: "Identify skill gap from member's frustration. If they struggle with: using platform → assign onboarding skill; understanding commission → assign commission explainer; making sales → assign sales training; building team → assign referral guide. Member: {{previousOutput}}. Context: {{context}}. Suggest the specific skill/training needed. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 85, when: "intent === 'training' || intent === 'registration' || intent === 'commission_inquiry'",
        },
      ],
    },
    {
      id: "knowledge_accumulation",
      name: "Knowledge Accumulation",
      nameBn: "জ্ঞান সঞ্চয়ন",
      department: "negativity_detection",
      description: "Accumulates insights about negativity patterns and stores them in knowledge base",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b"],
      agents: [
        {
          id: "negativity_insight_miner", name: "Negativity Insight Miner", nameBn: "নেতিবাচকতা অন্তর্দৃষ্টি খননকারী",
          department: "negativity_detection", team: "knowledge_accumulation",
          description: "Mines conversation data to extract recurring negativity patterns and stores in knowledge DB",
          descriptionBn: "কনভারসেশন ডাটা থেকে পুনরাবৃত্ত নেতিবাচকতা প্যাটার্ন খুঁজে বের করে এবং জ্ঞান ডাটাবেজে সংরক্ষণ করে",
          expertise: "You extract recurring negativity patterns, identify new trigger words, and build the knowledge base for future reference.",
          promptTemplate: "Extract new negativity insights from this conversation. Identify: new trigger words not in our DB, recurring suspicion patterns, effective counter-arguments that worked, trust-building phrases that succeeded. Format as knowledge entries. Conversation: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "true",
        },
      ],
    },
  ],
};
