import type { DepartmentDef } from "../types";

export const negativity_detection: DepartmentDef = {
  id: "negativity_detection",
  name: "Negativity Detection & Sensitivity",
  nameBn: "নেতিবাচকতা সনাক্তকরণ ও সংবেদনশীলতা",
  icon: "⚠️",
  description: "Detects negative sentiment triggers in Bangladeshi context, advises other departments on safe wording, maintains knowledge base of cultural sensitivities",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "trigger_analysis",
      name: "Trigger Word Analysis",
      nameBn: "ট্রিগার শব্দ বিশ্লেষণ",
      department: "negativity_detection",
      description: "Identifies words and phrases that trigger negative reactions in Bangladeshi audience",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "mlm_trigger_detector", name: "Recruitment Trigger Detector", nameBn: "রিক্রুটমেন্ট ট্রিগার শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects recruitment, network marketing, team building related negative triggers",
          descriptionBn: "রিক্রুটমেন্ট, নেটওয়ার্ক মার্কেটিং, সহযোগী বিল্ডিং সংক্রান্ত নেতিবাচক ট্রিগার শনাক্ত করে",
          expertise: "You specialize in detecting words like recruitment, network marketing, chain marketing, multi-level that trigger strong negative reactions in Bangladesh.",
          promptTemplate: "Analyze the conversation for recruitment/network marketing negative triggers. Words like 'রিক্রুটমেন্ট', 'network marketing', 'multi-level', 'chain', 'pyramid' trigger extreme negativity in Bangladesh. If detected, flag with severity and suggest alternative wording. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 95, when: "intent === 'purchase' || intent === 'referral' || intent === 'registration'",
        },
        {
          id: "recruitment_trigger_detector", name: "Recruitment Trigger Detector", nameBn: "রিক্রুটমেন্ট ট্রিগার শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects negative triggers around member recruitment, joining, bringing people in",
          descriptionBn: "সদস্য বানানো, লোক ঢুকানো, জয়েন করানো সংক্রান্ত নেতিবাচক ট্রিগার শনাক্ত করে",
          expertise: "You detect when recruitment language triggers suspicion. 'লোক ঢুকানো', 'সদস্য বানানো', 'জয়েন করানো' are highly negative in Bangladeshi context due to recruitment scams.",
          promptTemplate: "Check for recruitment-related negative triggers. Phrases like 'লোক ঢুকানো', 'সদস্য বানানো', 'জয়েন করানো', 'bring people in', 'recruit members' trigger scam suspicion in Bangladesh. Flag and suggest positive alternatives like 'partner', 'join our team', 'grow together'. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 94, when: "intent === 'referral' || intent === 'registration' || intent === 'general'",
        },
        {
          id: "money_trigger_detector", name: "Money Trust Trigger Detector", nameBn: "টাকা বিশ্বাস ট্রিগার শনাক্তকারী",
          department: "negativity_detection", team: "trigger_analysis",
          description: "Detects negative triggers around money, payment, investment, commission",
          descriptionBn: "টাকা, পেমেন্ট, বিনিয়োগ, কমিশন সংক্রান্ত নেতিবাচক ট্রিগার শনাক্ত করে",
          expertise: "You detect money-related suspicion triggers. Bangladeshis are highly skeptical of advance payment, registration fees, investment promises, unrealistic commission claims.",
          promptTemplate: "Scan for money-related negative triggers: 'advance payment', 'registration fee', 'investment', 'guaranteed return', 'বিনিয়োগ', 'কমিশন', 'রেজিস্ট্রেশন ফি'. These trigger scam fear in Bangladesh. Flag severity and suggest trust-building alternatives. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 93, when: "intent === 'purchase' || intent === 'commission_inquiry' || intent === 'withdrawal'",
        },
      ],
    },
    {
      id: "conversation_analysis",
      name: "Conversation Sentiment Analysis",
      nameBn: "কনভারসেশন সেন্টিমেন্ট বিশ্লেষণ",
      department: "negativity_detection",
      description: "Analyzes full conversations for negative sentiment patterns and trust barriers",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b"],
      agents: [
        {
          id: "sentiment_negativity_scanner", name: "Sentiment Negativity Scanner", nameBn: "সেন্টিমেন্ট নেতিবাচকতা স্ক্যানার",
          department: "negativity_detection", team: "conversation_analysis",
          description: "Scans conversation history for negative sentiment patterns and trust barriers specific to Bangladesh",
          descriptionBn: "কনভারসেশন ইতিহাসে বাংলাদেশের প্রেক্ষাপটে নেতিবাচক সেন্টিমেন্ট প্যাটার্ন ও বিশ্বাসের বাধা খুঁজে বের করে",
          expertise: "You analyze conversation patterns to identify when a Bangladeshi customer is showing distrust, skepticism, or negativity about specific topics.",
          promptTemplate: "Analyze this conversation for negative sentiment patterns specific to Bangladesh. Look for: distrust ('বিশ্বাস হচ্ছে না', 'scam'), skepticism ('খুব ভালো লাগছে না'), fear ('ভয়', 'risk'), past bad experience ('আগে প্রতারিত'), comparison with scams ('রিক্রুটমেন্ট এর মত'). Return detected issues with severity. Conversation: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "trust_barrier_identifier", name: "Trust Barrier Identifier", nameBn: "বিশ্বাস বাধা শনাক্তকারী",
          department: "negativity_detection", team: "conversation_analysis",
          description: "Identifies specific trust barriers Bangladeshi customers have about the business model",
          descriptionBn: "বাংলাদেশী গ্রাহকদের বিজনেস মডেল সম্পর্কে নির্দিষ্ট বিশ্বাসের বাধা চিহ্নিত করে",
          expertise: "You identify trust barriers: 'এটা কি রিক্রুটমেন্ট?', 'আমি কি টাকা দিয়ে জয়েন করব?', 'কমিশন কত?', 'কোম্পানি কি বৈধ?' — these questions indicate distrust.",
          promptTemplate: "Identify trust barriers the customer is expressing. Common Bangladeshi trust barriers: legality concerns ('বৈধ কিনা'), Recruitment fear ('রিক্রুটমেন্ট কিনা'), money loss fear ('টাকা ডুবে যাবে'), upfront payment hesitation, company legitimacy doubt. Categorize each barrier. Customer message: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 2, priority: 89, when: "true",
        },
      ],
    },
    {
      id: "sensitivity_advisory",
      name: "Sensitivity Advisory",
      nameBn: "সংবেদনশীলতা পরামর্শ",
      department: "negativity_detection",
      description: "Advises other departments (Psychology, Sales, Member Success) on safe wording and approach",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b"],
      agents: [
        {
          id: "safe_wording_advisor", name: "Safe Wording Advisor", nameBn: "নিরাপদ শব্দচয়ন উপদেষ্টা",
          department: "negativity_detection", team: "sensitivity_advisory",
          description: "Suggests alternative positive wording for sensitive topics",
          descriptionBn: "সংবেদনশীল বিষয়ের জন্য বিকল্প পজেটিভ শব্দচয়নের পরামর্শ দেয়",
          expertise: "You advise on safe wording. Instead of 'recruitment plan' say 'partner program'. Instead of 'bring people' say 'grow together'. Instead of 'commission' say 'earnings'.",
          promptTemplate: "Review the drafted response for potentially negative wording. Suggest alternatives for any problematic phrases. Consider: recruitment-equivalent words, recruitment language, money promises, urgency pressure, guarantee claims. Original response: {{previousOutput}}. Detected triggers: {{context}}. Provide revised safe version. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["gpt-5.4-mini"],
          tier: 1, priority: 97, when: "true",
        },
        {
          id: "cultural_sensitivity_checker", name: "Cultural Sensitivity Checker", nameBn: "সাংস্কৃতিক সংবেদনশীলতা পরীক্ষক",
          department: "negativity_detection", team: "sensitivity_advisory",
          description: "Checks response for Islamic and Bangladeshi cultural sensitivity",
          descriptionBn: "ইসলামিক ও বাংলাদেশী সাংস্কৃতিক সংবেদনশীলতার জন্য উত্তর পরীক্ষা করে",
          expertise: "You ensure responses respect Islamic values, Bangladeshi social norms, and avoid culturally insensitive content.",
          promptTemplate: "Check this response for cultural sensitivity in Bangladeshi/Islamic context. Flag issues with: Islamic values (interest/riba, haram content, modesty), Bangladeshi social norms (respect for elders, family values), political sensitivity, religious sensitivity. Provide corrected version if issues found. Response: {{previousOutput}}. Customer: {{context}}. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["gpt-5.4-mini"],
          tier: 1, priority: 98, when: "true",
        },
      ],
    },
    {
      id: "knowledge_accumulation",
      name: "Knowledge Accumulation",
      nameBn: "জ্ঞান সঞ্চয়ন",
      department: "negativity_detection",
      description: "Accumulates insights about negativity patterns and stores them in knowledge base",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b"],
      agents: [
        {
          id: "negativity_insight_miner", name: "Negativity Insight Miner", nameBn: "নেতিবাচকতা অন্তর্দৃষ্টি খননকারী",
          department: "negativity_detection", team: "knowledge_accumulation",
          description: "Mines conversation data to extract recurring negativity patterns and stores in knowledge DB",
          descriptionBn: "কনভারসেশন ডাটা থেকে পুনরাবৃত্ত নেতিবাচকতা প্যাটার্ন খুঁজে বের করে এবং জ্ঞান ডাটাবেজে সংরক্ষণ করে",
          expertise: "You extract recurring negativity patterns, identify new trigger words, and build the knowledge base for future reference.",
          promptTemplate: "Extract new negativity insights from this conversation. Identify: new trigger words not in our DB, recurring suspicion patterns, effective counter-arguments that worked, trust-building phrases that succeeded. Format as knowledge entries. Conversation: {{previousOutput}}. Context: {{context}}. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "true",
        },
      ],
    },
  ],
};
