import type { DepartmentDef } from "../types";

export const operations: DepartmentDef = {
  id: "operations",
  name: "Operations",
  nameBn: "অপারেশনস",
  icon: "⚙️",
  description: "Order processing, payments, withdrawals, quality assurance",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["nemotron-3-ultra", "hermes-3-405b"],
  teams: [
    {
      id: "order_management",
      name: "Order Management",
      nameBn: "অর্ডার ম্যানেজমেন্ট",
      department: "operations",
      description: "Process, track, and manage orders",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "order_creator", name: "Order Creator", nameBn: "অর্ডার ক্রিয়েটর",
          department: "operations", team: "order_management",
          description: "Creates and validates new orders",
          descriptionBn: "নতুন অর্ডার তৈরি ও ভ্যালিডেট করে",
          expertise: "You create orders: verify customer, check product, validate quantity, calculate total, confirm availability.",
          promptTemplate: "Create order: customer={{name}}, product={{product}}, qty={{qty}}, price={{price}}. Validate details, check stock, create order. Return order ID. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 95, when: "intent === 'purchase'",
        },
        {
          id: "order_verifier", name: "Order Verifier", nameBn: "অর্ডার ভেরিফায়ার",
          department: "operations", team: "order_management",
          description: "Confirms orders after payment verification",
          descriptionBn: "পেমেন্ট কনফার্ম হলে অর্ডার কনফার্ম করে",
          expertise: "You verify orders: check payment confirmation, match amount, update order status, trigger fulfillment.",
          promptTemplate: "Verify order {{orderId}}. Payment={{paymentStatus}}, amount={{amount}}. If confirmed → update status to confirmed, notify customer. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 90, when: "intent === 'purchase'",
        },
        {
          id: "invoice_generator", name: "Invoice Generator", nameBn: "ইনভয়েস জেনারেটর",
          department: "operations", team: "order_management",
          description: "Generates invoices for orders",
          descriptionBn: "অর্ডারের জন্য ইনভয়েস তৈরি করে",
          expertise: "You generate invoices: order details, pricing, taxes, total, payment terms, company info, customer info.",
          promptTemplate: "Generate invoice. Order={{orderId}}, items={{items}}, total={{total}}, tax={{tax}}, payment={{method}}. Professional format. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 80, when: "intent === 'purchase'",
        },
        {
          id: "inventory_updater", name: "Inventory Updater", nameBn: "ইনভেন্টরি আপডেটার",
          department: "operations", team: "order_management",
          description: "Updates stock levels when orders are placed",
          descriptionBn: "অর্ডার প্লেস হলে স্টক লেভেল আপডেট করে",
          expertise: "You update inventory: deduct ordered items, trigger low stock alerts, update availability status, sync with product pages.",
          promptTemplate: "Update inventory. Product={{product}}, ordered={{qty}}, current={{stock}}, new={{newStock}}. If low stock: alert. Update status. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "intent === 'purchase'",
        },
        {
          id: "order_notifier", name: "Order Notifier", nameBn: "অর্ডার নোটিফায়ার",
          department: "operations", team: "order_management",
          description: "Sends order updates to customers",
          descriptionBn: "গ্রাহককে অর্ডার আপডেট পাঠায়",
          expertise: "You notify customers: order confirmed, processing, shipped, out for delivery, delivered, delayed.",
          promptTemplate: "Send order update. Order={{orderId}}, status={{status}}, details={{details}}. Keep customer informed and excited. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 85, when: "intent === 'purchase'",
        },
        {
          id: "order_analytics", name: "Order Analytics", nameBn: "অর্ডার এনালাইটিক্স",
          department: "operations", team: "order_management",
          description: "Analyzes order trends and patterns",
          descriptionBn: "অর্ডার ট্রেন্ড ও প্যাটার্ন বিশ্লেষণ করে",
          expertise: "You analyze orders: daily volume, popular products, peak times, payment methods, cancellation rates, delivery performance.",
          promptTemplate: "Order analytics: period={{period}}, orders={{orders}}, top products={{products}}, peak times={{peaks}}, cancellations={{cancel}}%. Insights + recommendations. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 60, when: "true",
        },
      ],
    },
    {
      id: "payment_processing",
      name: "Payment Processing",
      nameBn: "পেমেন্ট প্রসেসিং",
      department: "operations",
      description: "Process, verify, and track payments",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "sslcommerz_initiator", name: "SSLCommerz Initiator", nameBn: "SSLCommerz ইনিশিয়েটর",
          department: "operations", team: "payment_processing",
          description: "Initiates SSLCommerz payment gateway",
          descriptionBn: "SSLCommerz পেমেন্ট গেটওয়ে ইনিশিয়েট করে",
          expertise: "You initiate SSLCommerz payments: generate payment URL, pass order details, handle success/cancel/fail URLs.",
          promptTemplate: "Initiate SSLCommerz payment. Order={{orderId}}, amount={{amount}} BDT. Generate payment link. Instruct customer. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'purchase'",
        },
        {
          id: "ipn_validator", name: "IPN Validator", nameBn: "IPN ভ্যালিডেটর",
          department: "operations", team: "payment_processing",
          description: "Validates IPN (Instant Payment Notification)",
          descriptionBn: "IPN ভ্যালিডেশন ও ভারিফিকেশন করে",
          expertise: "You validate IPN: verify signature, check amount matches, confirm transaction ID, update order status.",
          promptTemplate: "Validate IPN: trxID={{trxId}}, amount={{amount}}, status={{status}}. Verify signature, match order, update. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'purchase'",
        },
        {
          id: "payment_status_checker", name: "Payment Status Checker", nameBn: "পেমেন্ট স্ট্যাটাস চেকার",
          department: "operations", team: "payment_processing",
          description: "Checks payment status for orders",
          descriptionBn: "অর্ডারের পেমেন্ট স্ট্যাটাস চেক করে",
          expertise: "You check payment status: pending, processing, completed, failed, refunded. Provide clear status to customers.",
          promptTemplate: "Check payment status: order={{orderId}}, trxID={{trxId}}. Status: pending/processing/completed/failed/refunded. Guide next step. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 80, when: "intent === 'general' || intent === 'complaint'",
        },
        {
          id: "refund_initiator", name: "Refund Initiator", nameBn: "রিফান্ড ইনিশিয়েটর",
          department: "operations", team: "payment_processing",
          description: "Initiates payment refunds",
          descriptionBn: "পেমেন্ট রিফান্ড ইনিশিয়েট করে",
          expertise: "You initiate refunds: verify eligibility, process through gateway, notify customer, track refund status.",
          promptTemplate: "Initiate refund: order={{orderId}}, amount={{amount}}, reason={{reason}}. Process via gateway, notify customer, provide reference. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'complaint'",
        },
        {
          id: "transaction_logger", name: "Transaction Logger", nameBn: "ট্রানজেকশন লগার",
          department: "operations", team: "payment_processing",
          description: "Logs all financial transactions",
          descriptionBn: "সব আর্থিক লেনদেন লগ করে",
          expertise: "You log transactions: order payments, commissions, withdrawals, bonuses, refunds. Date, amount, type, reference.",
          promptTemplate: "Log transaction: type={{type}}, amount={{amount}}, reference={{ref}}, customer={{customer}}. Record with timestamp. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 70, when: "true",
        },
        {
          id: "fraud_detector", name: "Fraud Detector", nameBn: "ফ্রড ডিটেক্টর",
          department: "operations", team: "payment_processing",
          description: "Detects suspicious payment activities",
          descriptionBn: "সন্দেহজনক পেমেন্ট অ্যাক্টিভিটি ডিটেক্ট করে",
          expertise: "You detect fraud: multiple failed attempts, unusual amounts, rapid transactions, mismatched details, suspicious patterns.",
          promptTemplate: "Check for fraud: transaction={{trx}}, pattern={{pattern}}. Risk: high/medium/low. If high → block + notify admin. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 95, when: "true",
        },
      ],
    },
    {
      id: "withdrawal_management",
      name: "Withdrawal Management",
      nameBn: "উইথড্রয়াল ম্যানেজমেন্ট",
      department: "operations",
      description: "Process and manage commission withdrawals",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "withdrawal_validator", name: "Withdrawal Validator", nameBn: "উইথড্রয়াল ভ্যালিডেটর",
          department: "operations", team: "withdrawal_management",
          description: "Validates withdrawal requests",
          descriptionBn: "উইথড্রয়াল রিকোয়েস্ট চেক করে",
          expertise: "You validate withdrawals: check minimum balance, verify identity, confirm method, check frequency limits.",
          promptTemplate: "Validate withdrawal: balance={{balance}}, requested={{amount}}, min={{min}}, method={{method}}. Valid yes/no. Reason if invalid. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'withdrawal'",
        },
        {
          id: "withdrawal_approver", name: "Withdrawal Approver", nameBn: "উইথড্রয়াল অ্যাপ্রুভার",
          department: "operations", team: "withdrawal_management",
          description: "Auto-approves small, flags large withdrawals",
          descriptionBn: "ছোট অঙ্ক অটো-অ্যাপ্রুভ, বড় অঙ্ক ফ্ল্যাগ করে",
          expertise: "You approve withdrawals: small amounts (under threshold) → auto, large amounts → manual review, suspicious → hold.",
          promptTemplate: "Approve withdrawal: amount={{amount}}, threshold={{threshold}}. If under → auto-approve. If over → flag for manual review. If suspicious → hold. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'withdrawal'",
        },
        {
          id: "payment_sender", name: "Payment Sender", nameBn: "পেমেন্ট প্রেরক",
          department: "operations", team: "withdrawal_management",
          description: "Sends payments via bKash/Nagad/bank",
          descriptionBn: "bKash/Nagad/ব্যাংকে পেমেন্ট পাঠায়",
          expertise: "You send payments: process via selected method, confirm receipt, provide reference, update member.",
          promptTemplate: "Send payment: member={{name}}, amount={{amount}}, method={{method}}, account={{account}}. Process, confirm, notify with reference. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'withdrawal'",
        },
        {
          id: "withdrawal_notifier", name: "Withdrawal Notifier", nameBn: "উইথড্রয়াল নোটিফায়ার",
          department: "operations", team: "withdrawal_management",
          description: "Notifies members about withdrawal status",
          descriptionBn: "উইথড্রয়াল স্ট্যাটাস সম্পর্কে কর্মীকে জানায়",
          expertise: "You notify: request received, processing, approved, sent, completed, or rejected with reason.",
          promptTemplate: "Notify withdrawal status: status={{status}}, amount={{amount}}, method={{method}}. Clear update with next steps. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "intent === 'withdrawal'",
        },
        {
          id: "withdrawal_analytics", name: "Withdrawal Analytics", nameBn: "উইথড্রয়াল এনালাইটিক্স",
          department: "operations", team: "withdrawal_management",
          description: "Analyzes withdrawal patterns",
          descriptionBn: "উইথড্রয়াল প্যাটার্ন এনালাইসিস করে",
          expertise: "You analyze withdrawals: frequency, average amount, peak days, method preference, rejection reasons, trends.",
          promptTemplate: "Withdrawal analytics: period={{period}}, total={{total}}, avg={{avg}}, peakDay={{peak}}, topMethod={{method}}. Insights. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 60, when: "true",
        },
      ],
    },
    {
      id: "quality_assurance",
      name: "Quality Assurance",
      nameBn: "কোয়ালিটি অ্যাসিউরেন্স",
      department: "operations",
      description: "Monitor quality, errors, compliance, backups",
      primaryModel: "nemotron-3-super",
      fallbackModels: ["gpt-5.4-mini", "deepseek-v4-flash-free"],
      agents: [
        {
          id: "response_quality_checker", name: "Response Quality Checker", nameBn: "রেসপন্স কোয়ালিটি চেকার",
          department: "operations", team: "quality_assurance",
          description: "Checks AI output quality",
          descriptionBn: "AI আউটপুটের কোয়ালিটি চেক করে",
          expertise: "You check AI responses: accuracy, tone, cultural appropriateness, completeness, policy compliance, language correctness.",
          promptTemplate: "Check response quality: response={{response}}, context={{context}}. Score 0-10. Issues: accuracy/tone/culture/policy. Suggest fix. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "error_monitor", name: "Error Monitor", nameBn: "এরর মনিটর",
          department: "operations", team: "quality_assurance",
          description: "Monitors and reports system errors",
          descriptionBn: "সিস্টেম এরর মনিটর ও রিপোর্ট করে",
          expertise: "You monitor errors: API failures, database errors, timeout, rate limits, authentication failures, deployment issues.",
          promptTemplate: "Error report: type={{type}}, count={{count}}, lastError={{last}}. Severity: critical/high/medium/low. Action needed. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 85, when: "true",
        },
        {
          id: "performance_auditor", name: "Performance Auditor", nameBn: "পারফরম্যান্স অডিটর",
          department: "operations", team: "quality_assurance",
          description: "Audits system and agent performance",
          descriptionBn: "সিস্টেম ও এজেন্ট পারফরম্যান্স অডিট করে",
          expertise: "You audit performance: response times, agent success rates, model failover rates, error rates, throughput.",
          promptTemplate: "Performance audit: period={{period}}, avgResponse={{response}}ms, success={{success}}%, errors={{errors}}%. Findings + recommendations. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 80, when: "true",
        },
        {
          id: "compliance_checker", name: "Compliance Checker", nameBn: "কমপ্লায়েন্স চেকার",
          department: "operations", team: "quality_assurance",
          description: "Checks regulatory and policy compliance",
          descriptionBn: "নিয়ম ও নীতি মেনে চলছে কিনা চেক করে",
          expertise: "You check compliance: data protection, consumer rights, MLM regulations, payment security, content guidelines.",
          promptTemplate: "Compliance check: area={{area}}, practice={{practice}}. Status: compliant/violation/caution. Remediation steps if violation. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "backup_manager", name: "Backup Manager", nameBn: "ব্যাকআপ ম্যানেজার",
          department: "operations", team: "quality_assurance",
          description: "Monitors data backup status",
          descriptionBn: "ডাটা ব্যাকআপ স্ট্যাটাস মনিটর করে",
          expertise: "You monitor backups: last backup time, size, integrity, frequency, next scheduled. Alert on failures.",
          promptTemplate: "Backup status: last={{last}}, size={{size}}, integrity={{integrity}}, next={{next}}. Status: ok/warning/critical. Action if critical. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "true",
        },
      ],
    },
  ],
};
