import type { DepartmentDef } from "../types";

export const platform_admin: DepartmentDef = {
  id: "platform_admin",
  name: "Platform Administration",
  nameBn: "প্ল্যাটফর্ম প্রশাসন",
  icon: "🛠️",
  description: "Content management, configuration, security, platform health",
  primaryModel: "gpt-5.4-mini",
  fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
  teams: [
    {
      id: "content_management",
      name: "Content Management",
      nameBn: "কন্টেন্ট ম্যানেজমেন্ট",
      department: "platform_admin",
      description: "Manage translations, currency, FAQs, product descriptions",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "translation_manager", name: "Translation Manager", nameBn: "অনুবাদ ব্যবস্থাপক",
          department: "platform_admin", team: "content_management",
          description: "Syncs English ↔ Bengali translations",
          descriptionBn: "ইংরেজি ↔ বাংলা অনুবাদ সিঙ্ক করে",
          expertise: "You manage translations: ensure English and Bengali versions match, fix discrepancies, maintain consistency in terminology, update both on changes.",
          promptTemplate: "Manage translation: en={{english}}, bn={{bangla}}. Check accuracy, consistency, cultural appropriateness. Fix if needed. Language: Bengali/English.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "true",
        },
        {
          id: "currency_manager", name: "Currency Manager", nameBn: "মুদ্রা ব্যবস্থাপক",
          department: "platform_admin", team: "content_management",
          description: "Updates currency exchange rates",
          descriptionBn: "মুদ্রা বিনিময় হার আপডেট করে",
          expertise: "You manage currency: update BDT exchange rates, ensure price consistency, display correct currency format, handle multi-currency display.",
          promptTemplate: "Update currency: USD={{usd}}, BDT rate={{rate}}. Update prices, verify display. Ensure {{currency}} formatting correct. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 70, when: "true",
        },
        {
          id: "faq_updater", name: "FAQ Updater", nameBn: "FAQ আপডেটার",
          department: "platform_admin", team: "content_management",
          description: "Updates and optimizes FAQ content",
          descriptionBn: "FAQ কন্টেন্ট আপডেট ও অপটিমাইজ করে",
          expertise: "You update FAQs: add new questions, update answers for policy changes, remove outdated, categorize correctly, optimize for clarity.",
          promptTemplate: "Update FAQ: action={{action}}, question={{q}}, answer={{a}}. Ensure accuracy, policy compliance, clarity. Bengali + English versions. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "true",
        },
        {
          id: "product_desc_writer", name: "Product Description Writer", nameBn: "পণ্য বিবরণ লেখক",
          department: "platform_admin", team: "content_management",
          description: "Writes product descriptions in English + Bengali",
          descriptionBn: "ইংরেজি ও বাংলায় পণ্যের বিবরণ লেখে",
          expertise: "You write product descriptions: features, benefits, price, usage, specifications. Compelling, accurate, SEO-friendly. Both languages.",
          promptTemplate: "Write product description: product={{product}}, features={{features}}, price={{price}}. En + Bn versions. Compelling, accurate, clear. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "true",
        },
        {
          id: "content_localizer", name: "Content Localizer", nameBn: "কন্টেন্ট লোকালাইজার",
          department: "platform_admin", team: "content_management",
          description: "Localizes content for Bangladeshi audience",
          descriptionBn: "বাংলাদেশি দর্শকদের জন্য কন্টেন্ট লোকালাইজ করে",
          expertise: "You localize content: Bangladeshi examples, local references, appropriate tone, cultural sensitivity, Bengali expressions, local payment methods.",
          promptTemplate: "Localize content: {{content}}. Adapt for Bangladesh: local examples, cultural references, Bengali expressions. Keep core message. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 80, when: "true",
        },
      ],
    },
    {
      id: "configuration",
      name: "Configuration",
      nameBn: "কনফিগারেশন",
      department: "platform_admin",
      description: "Commission config, payment gateway health, settings backup, test mode",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "commission_config_validator", name: "Commission Config Validator", nameBn: "কমিশন কনফিগ ভ্যালিডেটর",
          department: "platform_admin", team: "configuration",
          description: "Validates commission structure settings",
          descriptionBn: "কমিশন কাঠামো সেটিংস চেক করে",
          expertise: "You validate commission config: level percentages, caps, minimums, bonus rules, withdrawal limits. Ensure consistency and correctness.",
          promptTemplate: "Validate commission config: {{config}}. Check: levels, percentages, caps, minimums. Report issues + fix suggestions. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "true",
        },
        {
          id: "payment_gateway_health", name: "Payment Gateway Health", nameBn: "পেমেন্ট গেটওয়ে হেলথ",
          department: "platform_admin", team: "configuration",
          description: "Checks SSLCommerz and other payment gateways",
          descriptionBn: "SSLCommerz ও অন্যান্য পেমেন্ট গেটওয়ে চেক করে",
          expertise: "You check gateway health: SSLCommerz API status, response times, success rates, error rates. Alert on issues.",
          promptTemplate: "Check payment gateway: gateway={{gateway}}, status={{status}}, success={{success}}%, errors={{errors}}. Health: ok/warning/critical. Action if needed. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 95, when: "true",
        },
        {
          id: "settings_backup", name: "Settings Backup", nameBn: "সেটিংস ব্যাকআপ",
          department: "platform_admin", team: "configuration",
          description: "Backs up company settings configuration",
          descriptionBn: "কোম্পানি সেটিংস কনফিগারেশন ব্যাকআপ করে",
          expertise: "You backup settings: commission config, model config, system prompts, feature flags, API keys config. Timestamped, versioned.",
          promptTemplate: "Backup settings: config={{config}}, timestamp={{time}}. Create backup, verify integrity, log version. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 75, when: "true",
        },
        {
          id: "test_mode_manager", name: "Test Mode Manager", nameBn: "টেস্ট মোড ম্যানেজার",
          department: "platform_admin", team: "configuration",
          description: "Manages test mode for development",
          descriptionBn: "ডেভেলপমেন্টের জন্য টেস্ট মোড পরিচালনা করে",
          expertise: "You manage test mode: toggle test/live, sandbox payment, test phone numbers, mock data, isolation from production.",
          promptTemplate: "Manage test mode: current={{mode}}, request={{request}}. Toggle? Impact assessment. Ensure production isolation. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 65, when: "true",
        },
      ],
    },
    {
      id: "security_access",
      name: "Security & Access",
      nameBn: "নিরাপত্তা ও অ্যাক্সেস",
      department: "platform_admin",
      description: "Login monitoring, permissions, suspicious activity, audit logs",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "login_monitor", name: "Login Monitor", nameBn: "লগইন মনিটর",
          department: "platform_admin", team: "security_access",
          description: "Monitors login attempts for suspicious activity",
          descriptionBn: "সন্দেহজনক কার্যকলাপের জন্য লগইন প্রচেষ্টা মনিটর করে",
          expertise: "You monitor logins: failed attempts, unusual times, new devices, different locations, brute force patterns. Alert on anomalies.",
          promptTemplate: "Monitor login: user={{user}}, attempts={{attempts}}, lastFailed={{last}}, location={{location}}. Risk: low/medium/high. Action if needed. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "true",
        },
        {
          id: "permission_checker", name: "Permission Checker", nameBn: "পারমিশন চেকার",
          department: "platform_admin", team: "security_access",
          description: "Verifies user permissions before actions",
          descriptionBn: "কাজ করার আগে ব্যবহারকারীর অনুমতি যাচাই করে",
          expertise: "You check permissions: role-based access, resource-level permissions, action authorization. Deny unauthorized access with clear reason.",
          promptTemplate: "Check permission: user={{user}}, action={{action}}, resource={{resource}}, role={{role}}. Authorized yes/no. Reason if no. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 90, when: "true",
        },
        {
          id: "suspicious_activity_detector", name: "Suspicious Activity Detector", nameBn: "সন্দেহজনক কার্যকলাপ শনাক্তকারী",
          department: "platform_admin", team: "security_access",
          description: "Detects suspicious system activity",
          descriptionBn: "সন্দেহজনক সিস্টেম কার্যকলাপ শনাক্ত করে",
          expertise: "You detect anomalies: unusual API patterns, data scraping, multiple account creation, rapid transactions, access pattern changes.",
          promptTemplate: "Detect suspicious activity: pattern={{pattern}}, threshold={{threshold}}. Score: 0-10. If >7: alert + action. Evidence. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 100, when: "true",
        },
        {
          id: "audit_logger", name: "Audit Logger", nameBn: "অডিট লগার",
          department: "platform_admin", team: "security_access",
          description: "Maintains system audit logs",
          descriptionBn: "সিস্টেম অডিট লগ রক্ষণাবেক্ষণ করে",
          expertise: "You maintain audit logs: who did what, when, from where. Immutable records. Support compliance investigations.",
          promptTemplate: "Log audit: user={{user}}, action={{action}}, resource={{resource}}, result={{result}}, timestamp={{time}}. Immutable record. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 85, when: "true",
        },
      ],
    },
    {
      id: "platform_health",
      name: "Platform Health",
      nameBn: "প্ল্যাটফর্ম স্বাস্থ্য",
      department: "platform_admin",
      description: "DB health, API availability, performance, error logs, version tracking",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "db_health_monitor", name: "DB Health Monitor", nameBn: "ডাটাবেস স্বাস্থ্য মনিটর",
          department: "platform_admin", team: "platform_health",
          description: "Monitors D1 database health",
          descriptionBn: "D1 ডাটাবেস স্বাস্থ্য মনিটর করে",
          expertise: "You monitor DB: query performance, connection count, storage usage, error rates, migration status. Alert on degradation.",
          promptTemplate: "DB health: queries={{qps}}, errors={{errors}}, storage={{storage}}%, migrations={{migrations}}. Status: healthy/warning/critical. Action. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "true",
        },
        {
          id: "api_availability_checker", name: "API Availability Checker", nameBn: "API প্রাপ্যতা পরীক্ষক",
          department: "platform_admin", team: "platform_health",
          description: "Checks API endpoint availability",
          descriptionBn: "API এন্ডপয়েন্ট প্রাপ্যতা পরীক্ষা করে",
          expertise: "You check APIs: endpoint status codes, response times, uptime percentage, recent failures, rate limit status.",
          promptTemplate: "Check API: endpoint={{endpoint}}, status={{status}}, response={{response}}ms, uptime={{uptime}}%. Health: ok/warning/down. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 90, when: "true",
        },
        {
          id: "performance_monitor", name: "Performance Monitor", nameBn: "পারফরম্যান্স মনিটর",
          department: "platform_admin", team: "platform_health",
          description: "Monitors site and AI performance",
          descriptionBn: "সাইট ও AI পারফরম্যান্স মনিটর করে",
          expertise: "You monitor performance: page load time, API response times, AI model latency, memory usage, CPU, concurrent requests.",
          promptTemplate: "Performance: load={{load}}ms, api={{api}}ms, ai={{ai}}ms, memory={{mem}}%, concurrent={{concurrent}}. Issues + recommendations. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 85, when: "true",
        },
        {
          id: "error_log_analyzer", name: "Error Log Analyzer", nameBn: "এরর লগ বিশ্লেষক",
          department: "platform_admin", team: "platform_health",
          description: "Analyzes error logs for patterns",
          descriptionBn: "এরর লগ বিশ্লেষণ করে প্যাটার্ন খুঁজে বের করে",
          expertise: "You analyze errors: categorize by type, frequency, impact. Find root causes. Suggest fixes. Track recurring issues.",
          promptTemplate: "Analyze errors: logs={{logs}}. Top errors: type + count + impact. Root causes. Fix suggestions. Track trends. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 80, when: "true",
        },
        {
          id: "update_manager", name: "Update Manager", nameBn: "আপডেট ম্যানেজার",
          department: "platform_admin", team: "platform_health",
          description: "Tracks version updates and changes",
          descriptionBn: "ভার্সন আপডেট ও পরিবর্তন ট্র্যাক করে",
          expertise: "You track updates: current version, latest version, changelog, breaking changes, migration needed, update schedule.",
          promptTemplate: "Check updates: current={{current}}, latest={{latest}}, changes={{changes}}. Update needed? yes/no. Migration required? Impact assessment. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 75, when: "true",
        },
      ],
    },
  ],
};
