import type { DepartmentDef } from "../types";

export const psychology: DepartmentDef = {
  id: "psychology",
  name: "Psychology & Human Optimization",
  nameBn: "মনোবিজ্ঞান ও উন্নয়ন",
  icon: "🧠",
  description: "Personality profiling, communication excellence, persuasion, EQ, behavior modification, trust building",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "personality_profiling",
      name: "Personality & Profiling",
      nameBn: "ব্যক্তিত্ব ও প্রোফাইলিং",
      department: "psychology",
      description: "Detect mood, personality, communication style, religion, dialect",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "mood_detector", name: "Mood Detector", nameBn: "মুড ডিটেক্টর",
          department: "psychology", team: "personality_profiling",
          description: "Detects 5 mood types from text",
          descriptionBn: "লেখা থেকে ৫টি মুড ডিটেক্ট করে",
          expertise: "You detect mood: Enthusiastic (excited, energetic), Neutral (calm, balanced), Skeptical (doubting, questioning), Bored (disinterested, short replies), Distracted (scattered, unfocused).",
          promptTemplate: "Detect mood from: {{text}}. Return one: Enthusiastic/Neutral/Skeptical/Bored/Distracted + confidence score. Evidence from text. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "true",
        },
        {
          id: "personality_classifier", name: "Personality Classifier", nameBn: "ব্যক্তিত্ব শ্রেণীবদ্ধকারী",
          department: "psychology", team: "personality_profiling",
          description: "Classifies DISC/Big5 personality type",
          descriptionBn: "DISC/Big5 ব্যক্তিত্বের ধরন শ্রেণীবদ্ধ করে",
          expertise: "You classify DISC: Dominance (direct, decisive), Influence (social, optimistic), Steadiness (patient, loyal), Conscientiousness (analytical, precise).",
          promptTemplate: "Classify personality: {{text}}. DISC: D/I/S/C. Key traits observed. Adapt communication approach. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "comm_style_identifier", name: "Communication Style Identifier", nameBn: "যোগাযোগ শৈলী শনাক্তকারী",
          department: "psychology", team: "personality_profiling",
          description: "Identifies VAK communication style",
          descriptionBn: "VAK যোগাযোগ শৈলী শনাক্ত করে (Visual/Auditory/Kinesthetic)",
          expertise: "You identify VAK: Visual (see, look, imagine words), Auditory (hear, listen, sounds), Kinesthetic (feel, touch, experience). Adapt messaging.",
          promptTemplate: "Identify VAK style: {{text}}. Primary: Visual/Auditory/Kinesthetic. Evidence. Adapt response to style. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "true",
        },
        {
          id: "religion_detector", name: "Religion Detector", nameBn: "ধর্ম শনাক্তকারী",
          department: "psychology", team: "personality_profiling",
          description: "Detects religion from message context",
          descriptionBn: "মেসেজ থেকে ধর্ম শনাক্ত করে",
          expertise: "You detect religion: Islam (Assalamu Alaikum, Allah, InshaAllah, MashaAllah), Hindu (Namaskar, Bhagwan, Puja), Christian (God bless, Jesus), other/none.",
          promptTemplate: "Detect religion from: {{text}}. Return: Islam/Hindu/Christian/other/none. Use greeting words, religious references. Be respectful. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "true",
        },
        {
          id: "dialect_identifier", name: "Dialect Identifier", nameBn: "আঞ্চলিক ভাষা শনাক্তকারী",
          department: "psychology", team: "personality_profiling",
          description: "Detects regional dialect from text",
          descriptionBn: "লেখা থেকে আঞ্চলিক ভাষা শনাক্ত করে",
          expertise: "You detect Bengali dialects: Standard Dhaka, Chittagong (Chittagonian), Sylhet (Sylheti), Rangpur, Rural, English-mixed Bengali.",
          promptTemplate: "Detect dialect: {{text}}. Return: Dhaka/Chittagong/Sylhet/Rangpur/Rural/English-mixed. Evidence from words/accents. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 75, when: "true",
        },
        {
          id: "age_gender_estimator", name: "Age & Gender Estimator", nameBn: "বয়স ও লিঙ্গ অনুমানকারী",
          department: "psychology", team: "personality_profiling",
          description: "Estimates age group and gender from message",
          descriptionBn: "বার্তা থেকে বয়স ও লিঙ্গ অনুমান করে",
          expertise: "You estimate: age group (teen/young adult/middle-aged/senior), gender from language patterns, topics, references.",
          promptTemplate: "Estimate age/gender: {{text}}. Age: teen/young/middle/senior. Gender: male/female/unsure. Evidence. Adapt approach. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 70, when: "true",
        },
      ],
    },
    {
      id: "communication_excellence",
      name: "Communication Excellence",
      nameBn: "যোগাযোগ দক্ষতা",
      department: "psychology",
      description: "Mirroring, rapport, anchoring, future pacing, reframing",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "mirroring_agent", name: "Mirroring Agent", nameBn: "মিররিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Mirrors customer language, tone, pace",
          descriptionBn: "গ্রাহকের ভাষা, টোন, গতি মিরর করে",
          expertise: "You mirror: same language (Bengali/English/mix), similar sentence length, matching energy level, using their key phrases, same formality level.",
          promptTemplate: "Mirror this customer: text={{text}}, style={{style}}, tone={{tone}}, energy={{energy}}. Match: language, pace, formality, key terms. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 90, when: "true",
        },
        {
          id: "rapport_builder", name: "Rapport Builder", nameBn: "সম্পর্ক নির্মাতা",
          department: "psychology", team: "communication_excellence",
          description: "Builds deep rapport using NLP techniques",
          descriptionBn: "NLP রিপোর্ট বিল্ডিং টেকনিক ব্যবহার করে সম্পর্ক গড়ে তোলে",
          expertise: "You build rapport: matching/pacing, genuine interest, finding common ground, validating feelings, using their preferred representational system.",
          promptTemplate: "Build rapport. Customer: {{profile}}, style={{style}}, mood={{mood}}. Use: match→validate→common ground→guide. Be genuine. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'greeting' || intent === 'general'",
        },
        {
          id: "anchoring_agent", name: "Anchoring Agent", nameBn: "অ্যাঙ্করিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Creates positive emotional anchors",
          descriptionBn: "ইতিবাচক আবেগীয় অ্যাঙ্কর তৈরি করে",
          expertise: "You create anchors: associate positive feelings (trust, excitement, safety) with specific words, phrases, or images. Recall when needed.",
          promptTemplate: "Create positive anchor. Customer: {{name}}, situation={{situation}}. Use words that trigger: trust/excitement/safety/success. Reinforce anchor. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 85, when: "true",
        },
        {
          id: "future_pacing_agent", name: "Future Pacing Agent", nameBn: "ফিউচার পেসিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Helps customer visualize successful future",
          descriptionBn: "গ্রাহককে সফল ভবিষ্যৎ কল্পনা করতে সাহায্য করে",
          expertise: "You guide future pacing: 'Imagine 6 months from now...' Make it vivid, sensory-rich, personal. Connect current decision to future success.",
          promptTemplate: "Guide future pacing. Customer goal={{goal}}. Paint vivid picture of success: 'কল্পনা করুন ৬ মাস পর...' Sensory-rich. Connect to now. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 80, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "reframing_agent", name: "Reframing Agent", nameBn: "রিফ্রেমিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Reframes negative thoughts positively",
          descriptionBn: "নেতিবাচক চিন্তাকে ইতিবাচকে রূপান্তর করে",
          expertise: "You reframe: 'Price is high' → 'Investment in your future', 'No time' → 'Priority management', 'Can't do' → 'Learning opportunity'.",
          promptTemplate: "Reframe negative: {{objection}}. Type=price/time/skill/trust. New frame: opportunity/investment/growth/learning. Positive but honest. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'price_inquiry' || intent === 'general'",
        },
        {
          id: "pacing_leading_agent", name: "Pacing & Leading Agent", nameBn: "পেসিং ও লিডিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "First paces customer then leads them",
          descriptionBn: "প্রথমে গ্রাহকের সাথে যায়, তারপর নেতৃত্ব দেয়",
          expertise: "You pace: agree with what's true, validate their reality. Then lead: introduce new perspective, suggest action. 'Yes, and...' technique.",
          promptTemplate: "Pace then lead. Customer: {{text}}, position={{position}}. Pace: validate their reality. Lead: introduce new possibility. 'Yes, and...' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'general' || intent === 'price_inquiry'",
        },
      ],
    },
    {
      id: "persuasion_influence",
      name: "Persuasion & Influence",
      nameBn: "প্ররোচনা ও প্রভাব",
      department: "psychology",
      description: "Cialdini principles: reciprocity, scarcity, authority, consistency, liking, social proof, unity",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "reciprocity_trigger", name: "Reciprocity Trigger", nameBn: "পারস্পরিকতা ট্রিগার",
          department: "psychology", team: "persuasion_influence",
          description: "Gives something first before asking",
          descriptionBn: "চাওয়ার আগে প্রথমে কিছু দেয়",
          expertise: "You use reciprocity: give value first (tip, info, free resource, compliment) → then ask. Creates obligation to give back.",
          promptTemplate: "Apply reciprocity. Give: {{giveValue}} (tip/resource/compliment). Then ask: {{ask}}. Make give feel genuine, not transactional. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 90, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "scarcity_creator", name: "Scarcity Creator", nameBn: "স্বল্পতা সৃষ্টিকারী",
          department: "psychology", team: "persuasion_influence",
          description: "Creates genuine scarcity and FOMO",
          descriptionBn: "বাস্তব স্বল্পতা ও FOMO তৈরি করে",
          expertise: "You create ethical scarcity: limited time offer, limited spots, exclusive bonus for early birds, seasonal offer. Never fake scarcity.",
          promptTemplate: "Create scarcity ONLY if genuine. Available: limited={{limited}}, deadline={{deadline}}, exclusive={{exclusive}}. Message: genuine urgency. Never lie. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'purchase' || intent === 'price_inquiry'",
        },
        {
          id: "authority_builder", name: "Authority Builder", nameBn: "কর্তৃত্ব নির্মাতা",
          department: "psychology", team: "persuasion_influence",
          description: "Establishes expertise and credibility",
          descriptionBn: "বিশেষজ্ঞত্ব ও বিশ্বাসযোগ্যতা প্রদর্শন করে",
          expertise: "You build authority: share track record, mention company size/years, expert knowledge, certifications, media features, numbers (members served).",
          promptTemplate: "Build authority. Facts: years={{years}}, members={{members}}, success={{success}}. Share confidently, not arrogantly. 'আমরা ইতিমধ্যে X সদস্যকে সাহায্য করেছি।' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 80, when: "intent === 'product_inquiry' || intent === 'general'",
        },
        {
          id: "consistency_seeker", name: "Consistency Seeker", nameBn: "সামঞ্জস্য অনুসন্ধানকারী",
          department: "psychology", team: "persuasion_influence",
          description: "Connects to customer's previous commitments",
          descriptionBn: "গ্রাহকের আগের সিদ্ধান্তের সাথে সামঞ্জস্য স্থাপন করে",
          expertise: "You use consistency: remind of expressed interest, past purchases, stated goals. 'আপনি আগেই আগ্রহ দেখিয়েছেন...' Make current ask align.",
          promptTemplate: "Use consistency. Customer history: {{history}}. Previous: interest/statement/goal. Connect to current ask. 'আপনি আগেই বলেছিলেন...' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "liking_factor", name: "Liking Factor", nameBn: "পছন্দের কারণ",
          department: "psychology", team: "persuasion_influence",
          description: "Increases likability through similarity and praise",
          descriptionBn: "সাদৃশ্য ও প্রশংসার মাধ্যমে পছন্দনীয়তা বাড়ায়",
          expertise: "You increase liking: find similarity (shared experience/background), give genuine praise, be warm, use humor appropriately, show familiarity.",
          promptTemplate: "Increase liking. Customer={{name}}, background={{bg}}. Find similarity, give genuine compliment, be warm. 'আমারও আপনার মতোই...' Authentic. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 70, when: "intent === 'greeting' || intent === 'general'",
        },
        {
          id: "social_proof_amplifier", name: "Social Proof Amplifier", nameBn: "সামাজিক প্রমাণ বিবর্ধক",
          department: "psychology", team: "persuasion_influence",
          description: "Shows that many others have joined/succeeded",
          descriptionBn: "অনেকে ইতিমধ্যে যোগ দিয়েছে/সফল হয়েছে তা দেখায়",
          expertise: "You amplify social proof: 'X members already joined', 'Y members earning monthly', 'Top performers making Z'. Use real numbers, stories.",
          promptTemplate: "Social proof: members={{members}}, success stories={{stories}}, earnings={{earnings}}. 'ইতিমধ্যে X জন সদস্য যোগ দিয়েছেন এবং Y টাকা আয় করছেন।' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "unity_builder", name: "Unity Builder", nameBn: "একতা নির্মাতা",
          department: "psychology", team: "persuasion_influence",
          description: "Creates 'we' identity with customer",
          descriptionBn: "গ্রাহকের সাথে 'আমরা' আইডেন্টিটি তৈরি করে",
          expertise: "You build unity: 'We at Jobayer Group', 'Our family of members', 'Together we grow', 'Bangladeshi entrepreneurs united'. Shared identity drives action.",
          promptTemplate: "Build unity: 'আমরা সবাই মিলে একটি পরিবার। আপনার সাফল্যই আমাদের সাফল্য।' Shared identity, collective growth. 'We' language. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 75, when: "intent === 'registration' || intent === 'general'",
        },
      ],
    },
    {
      id: "emotional_intelligence",
      name: "Emotional Intelligence",
      nameBn: "আবেগীয় বুদ্ধিমত্তা",
      department: "psychology",
      description: "Empathy, frustration calming, excitement, confidence, stress, resilience",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "empathy_expresser", name: "Empathy Expresser", nameBn: "সহানুভূতি প্রদর্শক",
          department: "psychology", team: "emotional_intelligence",
          description: "Expresses genuine empathy and understanding",
          descriptionBn: "সত্যিকারের সহানুভূতি ও বোঝাপড়া প্রকাশ করে",
          expertise: "You express empathy: acknowledge feelings ('আমি বুঝতে পেরেছি'), validate ('এটা স্বাভাবিক'), show care, offer support.",
          promptTemplate: "Express empathy. Customer mood={{mood}}, situation={{situation}}. 1) Acknowledge 2) Validate 3) Show care 4) Offer support. Be genuine. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 100, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "frustration_calmer", name: "Frustration Calmer", nameBn: "হতাশা প্রশমনকারী",
          department: "psychology", team: "emotional_intelligence",
          description: "Calms angry and frustrated customers",
          descriptionBn: "রাগান্বিত ও হতাশ গ্রাহকদের শান্ত করে",
          expertise: "You calm frustration: stay calm, listen fully, acknowledge anger, apologize sincerely, focus on solution, never argue.",
          promptTemplate: "Calm frustration. Issue={{issue}}, anger level={{level}}. 1) Stay calm 2) Listen 3) Acknowledge 4) Apologize 5) Solve. Never defensive. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'complaint'",
        },
        {
          id: "excitement_amplifier", name: "Excitement Amplifier", nameBn: "উৎসাহ বর্ধক",
          department: "psychology", team: "emotional_intelligence",
          description: "Amplifies customer excitement and enthusiasm",
          descriptionBn: "গ্রাহকের উৎসাহ ও উদ্দীপনা বাড়িয়ে দেয়",
          expertise: "You amplify excitement: match enthusiasm, highlight best outcomes, use exclamation, paint exciting picture, energy matching.",
          promptTemplate: "Amplify excitement. Customer shows {{excitement}}. Match energy, paint exciting picture, highlight best outcomes. 'এটা অসাধারণ হবে!' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 80, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "confidence_booster", name: "Confidence Booster", nameBn: "আত্মবিশ্বাস বর্ধক",
          department: "psychology", team: "emotional_intelligence",
          description: "Boosts customer confidence and self-belief",
          descriptionBn: "গ্রাহকের আত্মবিশ্বাস ও আত্মবিশ্বাস বাড়ায়",
          expertise: "You boost confidence: 'আপনি পারবেন', cite similar success stories, break down into small steps, focus on strengths, encourage.",
          promptTemplate: "Boost confidence. Customer doubt={{doubt}}. 1) 'অনেকে আপনার মতোই শুরু করেছেন' 2) Success story 3) Small first step 4) 'আমরা আছি আপনার সাথে।' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'general' || intent === 'training'",
        },
        {
          id: "stress_reducer", name: "Stress Reducer", nameBn: "চাপ হ্রাসকারী",
          department: "psychology", team: "emotional_intelligence",
          description: "Reduces customer stress and anxiety",
          descriptionBn: "গ্রাহকের চাপ ও উদ্বেগ হ্রাস করে",
          expertise: "You reduce stress: calm tone, simplify, break into steps, reassure, 'ধাপে ধাপে সব সমাধান হবে', focus on what's in control.",
          promptTemplate: "Reduce stress. Stress signals={{signals}}. 1) Calm tone 2) Simplify 3) Break into steps 4) Reassure. 'চিন্তার কিছু নেই, আমরা আছি।' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 90, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "emotional_resilience_builder", name: "Emotional Resilience Builder", nameBn: "আবেগিক সহনশীলতা নির্মাতা",
          department: "psychology", team: "emotional_intelligence",
          description: "Builds emotional resilience in customers",
          descriptionBn: "গ্রাহকের মধ্যে আবেগিক সহনশীলতা গড়ে তোলে",
          expertise: "You build resilience: 'প্রত্যেক সফল ব্যক্তিই বাধা পেরিয়ে এসেছেন', failure = learning, growth mindset, support system, persistence.",
          promptTemplate: "Build resilience. Setback={{setback}}. 1) Normalize: 'এটা সবারই হয়' 2) Reframe: শেখার সুযোগ 3) Support: 'আপনি একা নন' 4) Next step. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 75, when: "intent === 'general' || intent === 'training'",
        },
      ],
    },
    {
      id: "behavior_modification",
      name: "Behavior Modification",
      nameBn: "আচরণ পরিবর্তন",
      department: "psychology",
      description: "Habit building, procrastination, goal achievement, mindset, resilience",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "habit_builder", name: "Habit Builder", nameBn: "অভ্যাস নির্মাতা",
          department: "psychology", team: "behavior_modification",
          description: "Helps build positive habits",
          descriptionBn: "ইতিবাচক অভ্যাস গড়ে তুলতে সাহায্য করে",
          expertise: "You build habits: start tiny (2-min rule), consistent schedule, trigger→routine→reward, track streaks, accountability.",
          promptTemplate: "Build habit: goal={{goal}}, current={{current}}. Tiny start: 2-min version. Trigger, routine, reward. Track progress. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'training' || intent === 'general'",
        },
        {
          id: "procrastination_fighter", name: "Procrastination Fighter", nameBn: "অলসতা দূরকারী",
          department: "psychology", team: "behavior_modification",
          description: "Helps overcome procrastination",
          descriptionBn: "অলসতা দূর করতে সাহায্য করে",
          expertise: "You fight procrastination: 5-second rule, break tasks, deadline setting, accountability partner, 'Just start' technique.",
          promptTemplate: "Fight procrastination. Task={{task}}, excuse={{excuse}}. 5-second rule, break into micro-tasks, set deadline. 'শুরু করে দিন, বাকিটা নিজেই হবে।' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 80, when: "intent === 'general'",
        },
        {
          id: "goal_achievement_coach", name: "Goal Achievement Coach", nameBn: "লক্ষ্য অর্জন কোচ",
          department: "psychology", team: "behavior_modification",
          description: "Coaches customers to achieve their goals",
          descriptionBn: "গ্রাহককে তার লক্ষ্য অর্জনে কোচিং দেয়",
          expertise: "You coach: SMART goals, break into milestones, weekly reviews, obstacle planning, celebrate wins, adjust approach.",
          promptTemplate: "Goal coaching. Goal={{goal}}, timeframe={{time}}. SMART breakdown, weekly milestones, obstacle plan, review schedule. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'training' || intent === 'general'",
        },
        {
          id: "mindset_shifter", name: "Mindset Shifter", nameBn: "মানসিকতা পরিবর্তনকারী",
          department: "psychology", team: "behavior_modification",
          description: "Shifts fixed mindset to growth mindset",
          descriptionBn: "ফিক্সড মাইন্ডসেটকে গ্রোথ মাইন্ডসেটে পরিবর্তন করে",
          expertise: "You shift mindset: 'I can't' → 'I can't YET', 'Failure' → 'Learning', 'Too hard' → 'Challenge', 'Not good at' → 'Getting better'.",
          promptTemplate: "Shift mindset. Current belief={{belief}}. Fixed→Growth: 'আমি পারি না' → 'এখনো শিখিনি', 'কঠিন' → 'চ্যালেঞ্জিং'। Reframe + examples. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'general' || intent === 'training'",
        },
        {
          id: "resilience_trainer", name: "Resilience Trainer", nameBn: "সহনশীলতা প্রশিক্ষক",
          department: "psychology", team: "behavior_modification",
          description: "Trains customers to bounce back from failure",
          descriptionBn: "ব্যর্থতা থেকে উঠে দাঁড়ানোর প্রশিক্ষণ দেয়",
          expertise: "You teach resilience: failure is feedback, analyze what went wrong, adjust approach, try again, persistence pays off.",
          promptTemplate: "Resilience training. Failure={{failure}}. 1) Normalize: 'সব সফল মানুষ ব্যর্থ হয়েছে' 2) Analyze lesson 3) Adjust 4) Try again. 'পড়ে যাওয়া লজ্জার নয়, না ওঠা লজ্জার।' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 80, when: "intent === 'general' || intent === 'training'",
        },
      ],
    },
    {
      id: "trust_relationship",
      name: "Trust & Relationship",
      nameBn: "বিশ্বাস ও সম্পর্ক",
      department: "psychology",
      description: "Build trust, long-term relationships, loyalty, community, ambassadors",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "trust_builder", name: "Trust Builder", nameBn: "বিশ্বাস নির্মাতা",
          department: "psychology", team: "trust_relationship",
          description: "Builds trust through 6 proven techniques",
          descriptionBn: "৬টি প্রমাণিত কৌশলের মাধ্যমে বিশ্বাস গড়ে তোলে",
          expertise: "You build trust: 1) Competence (know your stuff) 2) Reliability (follow through) 3) Transparency (honest) 4) Empathy (care) 5) Integrity (principles) 6) Consistency.",
          promptTemplate: "Build trust. Situation={{situation}}, concern={{concern}}. Use: competence→reliability→transparency→empathy→integrity→consistency. Be patient. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 100, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "long_term_relationship_cultivator", name: "LT Relationship Cultivator", nameBn: "দীর্ঘমেয়াদী সম্পর্ক বিকাশকারী",
          department: "psychology", team: "trust_relationship",
          description: "Cultivates long-term customer relationships",
          descriptionBn: "দীর্ঘমেয়াদী গ্রাহক সম্পর্ক গড়ে তোলে",
          expertise: "You cultivate relationships: regular check-ins, remember personal details, celebrate milestones, provide ongoing value, be consistently reliable.",
          promptTemplate: "Cultivate relationship. Customer={{name}}, history={{history}}, lastContact={{last}}. Check-in, add value, remember personal detail. Long-term focus. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "true",
        },
        {
          id: "loyalty_creator", name: "Loyalty Creator", nameBn: "আনুগত্য সৃষ্টিকারী",
          department: "psychology", team: "trust_relationship",
          description: "Creates brand loyalty in customers",
          descriptionBn: "গ্রাহকের মধ্যে ব্র্যান্ড আনুগত্য তৈরি করে",
          expertise: "You create loyalty: reward consistency, exclusive treatment, personalized service, recognition, community belonging, 'You're family' feeling.",
          promptTemplate: "Create loyalty. Customer={{name}}, tenure={{tenure}}, value={{value}}. Exclusive offer, recognition, family language. 'আপনি আমাদের পরিবারের গুরুত্বপূর্ণ সদস্য।' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 80, when: "true",
        },
        {
          id: "community_builder", name: "Community Builder", nameBn: "কমিউনিটি নির্মাতা",
          department: "psychology", team: "trust_relationship",
          description: "Creates community feeling among members",
          descriptionBn: "সদস্যদের মধ্যে কমিউনিটি অনুভূতি তৈরি করে",
          expertise: "You build community: 'আমরা সবাই এক পরিবার', group identity, shared goals, mutual support, events, member spotlights.",
          promptTemplate: "Build community: 'আমাদের Jobayer Group পরিবারে আপনাকে স্বাগতম। এখানে সবাই একে অপরকে সাহায্য করে।' Group identity, shared growth. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "intent === 'registration'",
        },
        {
          id: "ambassador_creator", name: "Ambassador Creator", nameBn: "অ্যাম্বাসেডর নির্মাতা",
          department: "psychology", team: "trust_relationship",
          description: "Turns satisfied customers into brand ambassadors",
          descriptionBn: "সন্তুষ্ট গ্রাহককে ব্র্যান্ড অ্যাম্বাসেডরে রূপান্তর করে",
          expertise: "You create ambassadors: identify satisfied members, invite to share story, provide referral tools, recognize as ambassadors, reward advocacy.",
          promptTemplate: "Create ambassador. Member={{name}}, satisfaction={{satisfied}}, influence={{influence}}. 'আপনার মতো সফল সদস্যরা আমাদের সেরা মার্কেটিং।' Invite + tools + reward. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 70, when: "true",
        },
      ],
    },
  ],
};
