import type { DepartmentDef } from "../types";

export const psychology: DepartmentDef = {
  id: "psychology",
  name: "Psychology & Human Optimization",
  nameBn: "মনোবিজ্ঞান ও উন্নয়ন",
  icon: "🧠",
  description: "Personality profiling, communication excellence, persuasion, EQ, trust building",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "personality_profiling",
      name: "Personality & Profiling",
      nameBn: "ব্যক্তিত্ব ও প্রোফাইলিং",
      department: "psychology",
      description: "Detect mood, personality, communication style, religion, dialect",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "mood_detector", name: "Mood Detector", nameBn: "মুড ডিটেক্টর",
          department: "psychology", team: "personality_profiling",
          description: "Detects 5 mood types from text",
          descriptionBn: "লেখা থেকে ৫টি মুড ডিটেক্ট করে",
          expertise: "You detect mood: Enthusiastic (excited, energetic), Neutral (calm, balanced), Skeptical (doubting, questioning), Bored (disinterested, short replies), Distracted (scattered, unfocused).",
          promptTemplate: "Detect mood from: {{text}}. Return one: Enthusiastic/Neutral/Skeptical/Bored/Distracted + confidence score. Evidence from text. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'complaint' || intent === 'price_inquiry' || intent === 'purchase'",
        },
        {
          id: "personality_classifier", name: "Personality Classifier", nameBn: "ব্যক্তিত্ব শ্রেণীবদ্ধকারী",
          department: "psychology", team: "personality_profiling",
          description: "Classifies DISC/Big5 personality type",
          descriptionBn: "DISC/Big5 ব্যক্তিত্বের ধরন শ্রেণীবদ্ধ করে",
          expertise: "You classify DISC: Dominance (direct, decisive), Influence (social, optimistic), Steadiness (patient, loyal), Conscientiousness (analytical, precise).",
          promptTemplate: "Classify personality: {{text}}. DISC: D/I/S/C. Key traits observed. Adapt communication approach. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 90, when: "intent === 'purchase' || intent === 'registration' || intent === 'price_inquiry'",
        },
        {
          id: "comm_style_identifier", name: "Communication Style Identifier", nameBn: "যোগাযোগ শৈলী শনাক্তকারী",
          department: "psychology", team: "personality_profiling",
          description: "Identifies VAK communication style",
          descriptionBn: "VAK যোগাযোগ শৈলী শনাক্ত করে (Visual/Auditory/Kinesthetic)",
          expertise: "You identify VAK: Visual (see, look, imagine words), Auditory (hear, listen, sounds), Kinesthetic (feel, touch, experience). Adapt messaging.",
          promptTemplate: "Identify VAK style: {{text}}. Primary: Visual/Auditory/Kinesthetic. Evidence. Adapt response to style. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'purchase' || intent === 'product_inquiry' || intent === 'general'",
        },
        {
          id: "religion_detector", name: "Religion Detector", nameBn: "ধর্ম শনাক্তকারী",
          department: "psychology", team: "personality_profiling",
          description: "Detects religion from message context",
          descriptionBn: "মেসেজ থেকে ধর্ম শনাক্ত করে",
          expertise: "You detect religion: Islam (Assalamu Alaikum, Allah, InshaAllah, MashaAllah), Hindu (Namaskar, Bhagwan, Puja), Christian (God bless, Jesus), other/none.",
          promptTemplate: "Detect religion from: {{text}}. Return: Islam/Hindu/Christian/other/none. Use greeting words, religious references. Be respectful. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'greeting' || intent === 'general'",
        },
        {
          id: "dialect_identifier", name: "Dialect Identifier", nameBn: "আঞ্চলিক ভাষা শনাক্তকারী",
          department: "psychology", team: "personality_profiling",
          description: "Detects regional dialect from text",
          descriptionBn: "লেখা থেকে আঞ্চলিক ভাষা শনাক্ত করে",
          expertise: "You detect Bengali dialects: Standard Dhaka, Chittagong (Chittagonian), Sylhet (Sylheti), Rangpur, Rural, English-mixed Bengali.",
          promptTemplate: "Detect dialect: {{text}}. Return: Dhaka/Chittagong/Sylhet/Rangpur/Rural/English-mixed. Evidence from words/accents. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 75, when: "intent === 'greeting' || intent === 'general'",
        },
      ],
    },
    {
      id: "communication_excellence",
      name: "Communication Excellence",
      nameBn: "যোগাযোগ দক্ষতা",
      department: "psychology",
      description: "Mirroring, rapport, anchoring, future pacing, reframing",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "mirroring_agent", name: "Mirroring Agent", nameBn: "মিররিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Mirrors customer language, tone, pace",
          descriptionBn: "গ্রাহকের ভাষা, টোন, গতি মিরর করে",
          expertise: "You mirror: same language (Bengali/English/mix), similar sentence length, matching energy level, using their key phrases, same formality level.",
          promptTemplate: "Mirror this customer: text={{text}}, style={{style}}, tone={{tone}}, energy={{energy}}. Match: language, pace, formality, key terms. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 90, when: "intent === 'purchase' || intent === 'price_inquiry' || intent === 'general'",
        },
        {
          id: "rapport_builder", name: "Rapport Builder", nameBn: "সম্পর্ক নির্মাতা",
          department: "psychology", team: "communication_excellence",
          description: "Builds deep rapport using NLP techniques",
          descriptionBn: "NLP রিপোর্ট বিল্ডিং টেকনিক ব্যবহার করে সম্পর্ক গড়ে তোলে",
          expertise: "You build rapport: matching/pacing, genuine interest, finding common ground, validating feelings, using their preferred representational system.",
          promptTemplate: "Build rapport. Customer: {{profile}}, style={{style}}, mood={{mood}}. Use: match→validate→common ground→guide. Be genuine. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'greeting' || intent === 'general'",
        },
        {
          id: "anchoring_agent", name: "Anchoring Agent", nameBn: "অ্যাঙ্করিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Creates positive emotional anchors",
          descriptionBn: "ইতিবাচক আবেগীয় অ্যাঙ্কর তৈরি করে",
          expertise: "You create anchors: associate positive feelings (trust, excitement, safety) with specific words, phrases, or images. Recall when needed.",
          promptTemplate: "Create positive anchor. Customer: {{name}}, situation={{situation}}. Use words that trigger: trust/excitement/safety/success. Reinforce anchor. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 85, when: "intent === 'purchase' || intent === 'price_inquiry'",
        },
        {
          id: "future_pacing_agent", name: "Future Pacing Agent", nameBn: "ফিউচার পেসিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Helps customer visualize successful future",
          descriptionBn: "গ্রাহককে সফল ভবিষ্যৎ কল্পনা করতে সাহায্য করে",
          expertise: "You guide future pacing: 'Imagine 6 months from now...' Make it vivid, sensory-rich, personal. Connect current decision to future success.",
          promptTemplate: "Guide future pacing. Customer goal={{goal}}. Paint vivid picture of success: 'কল্পনা করুন ৬ মাস পর...' Sensory-rich. Connect to now. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 80, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "reframing_agent", name: "Reframing Agent", nameBn: "রিফ্রেমিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Reframes negative thoughts positively",
          descriptionBn: "নেতিবাচক চিন্তাকে ইতিবাচকে রূপান্তর করে",
          expertise: "You reframe: 'Price is high' → 'Investment in your future', 'No time' → 'Priority management', 'Can't do' → 'Learning opportunity'.",
          promptTemplate: "Reframe negative: {{objection}}. Type=price/time/skill/trust. New frame: opportunity/investment/growth/learning. Positive but honest. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'price_inquiry' || intent === 'general'",
        },
        {
          id: "pacing_leading_agent", name: "Pacing & Leading Agent", nameBn: "পেসিং ও লিডিং এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "First paces customer then leads them",
          descriptionBn: "প্রথমে গ্রাহকের সাথে যায়, তারপর নেতৃত্ব দেয়",
          expertise: "You pace: agree with what's true, validate their reality. Then lead: introduce new perspective, suggest action. 'Yes, and...' technique.",
          promptTemplate: "Pace then lead. Customer: {{text}}, position={{position}}. Pace: validate their reality. Lead: introduce new possibility. 'Yes, and...' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'general' || intent === 'price_inquiry'",
        },
        {
          id: "deep_listening_agent", name: "Deep Listening Agent", nameBn: "গভীর শ্রবণ এজেন্ট",
          department: "psychology", team: "communication_excellence",
          description: "Practices Bob Berg's 3 active listening techniques",
          descriptionBn: "বব বার্গের ৩টি অ্যাকটিভ লিসেনিং টেকনিক প্রয়োগ করে",
          expertise: "You practice 3 listening techniques: 1) Reference their previous messages to show you remember, 2) Let them finish completely before responding, 3) Recap their words — 'So you're saying that...' before adding your input. Silence is powerful. Let them fill the pause.",
          promptTemplate: "Active Listening. 3 rules: 1) Reference their past msg. 2) Don't interrupt — let them finish. 3) Recap: 'So you're saying...'. Pause after key questions. Let them talk more. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 88, when: "intent === 'complaint' || intent === 'general' || intent === 'price_inquiry'",
        },
      ],
    },
    {
      id: "persuasion_influence",
      name: "Persuasion & Influence",
      nameBn: "প্ররোচনা ও প্রভাব",
      department: "psychology",
      description: "Cialdini principles: reciprocity, scarcity, authority, consistency, liking, social proof, unity",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "reciprocity_trigger", name: "Reciprocity Trigger", nameBn: "পারস্পরিকতা ট্রিগার",
          department: "psychology", team: "persuasion_influence",
          description: "Gives something first before asking",
          descriptionBn: "চাওয়ার আগে প্রথমে কিছু দেয়",
          expertise: "You use reciprocity: give value first (tip, info, free resource, compliment) → then ask. Creates obligation to give back.",
          promptTemplate: "Apply reciprocity. Give: {{giveValue}} (tip/resource/compliment). Then ask: {{ask}}. Make give feel genuine, not transactional. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 90, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "scarcity_creator", name: "Scarcity Creator", nameBn: "স্বল্পতা সৃষ্টিকারী",
          department: "psychology", team: "persuasion_influence",
          description: "Creates genuine scarcity and FOMO",
          descriptionBn: "বাস্তব স্বল্পতা ও FOMO তৈরি করে",
          expertise: "You create ethical scarcity: limited time offer, limited spots, exclusive bonus for early birds, seasonal offer. Never fake scarcity.",
          promptTemplate: "Create scarcity ONLY if genuine. Available: limited={{limited}}, deadline={{deadline}}, exclusive={{exclusive}}. Message: genuine urgency. Never lie. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'purchase' || intent === 'price_inquiry'",
        },
        {
          id: "authority_builder", name: "Authority Builder", nameBn: "কর্তৃত্ব নির্মাতা",
          department: "psychology", team: "persuasion_influence",
          description: "Establishes expertise and credibility",
          descriptionBn: "বিশেষজ্ঞত্ব ও বিশ্বাসযোগ্যতা প্রদর্শন করে",
          expertise: "You build authority: share track record, mention company size/years, expert knowledge, certifications, media features, numbers (members served).",
          promptTemplate: "Build authority. Facts: years={{years}}, members={{members}}, success={{success}}. Share confidently, not arrogantly. 'আমরা ইতিমধ্যে X সদস্যকে সাহায্য করেছি।' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 80, when: "intent === 'product_inquiry' || intent === 'general'",
        },
        {
          id: "consistency_seeker", name: "Consistency Seeker", nameBn: "সামঞ্জস্য অনুসন্ধানকারী",
          department: "psychology", team: "persuasion_influence",
          description: "Connects to customer's previous commitments",
          descriptionBn: "গ্রাহকের আগের সিদ্ধান্তের সাথে সামঞ্জস্য স্থাপন করে",
          expertise: "You use consistency: remind of expressed interest, past purchases, stated goals. 'আপনি আগেই আগ্রহ দেখিয়েছেন...' Make current ask align.",
          promptTemplate: "Use consistency. Customer history: {{history}}. Previous: interest/statement/goal. Connect to current ask. 'আপনি আগেই বলেছিলেন...' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "liking_factor", name: "Liking Factor", nameBn: "পছন্দের কারণ",
          department: "psychology", team: "persuasion_influence",
          description: "Increases likability through similarity and praise",
          descriptionBn: "সাদৃশ্য ও প্রশংসার মাধ্যমে পছন্দনীয়তা বাড়ায়",
          expertise: "You increase liking: find similarity (shared experience/background), give genuine praise, be warm, use humor appropriately, show familiarity.",
          promptTemplate: "Increase liking. Customer={{name}}, background={{bg}}. Find similarity, give genuine compliment, be warm. 'আমারও আপনার মতোই...' Authentic. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 70, when: "intent === 'greeting' || intent === 'general'",
        },
        {
          id: "social_proof_amplifier", name: "Social Proof Amplifier", nameBn: "সামাজিক প্রমাণ বিবর্ধক",
          department: "psychology", team: "persuasion_influence",
          description: "Shows that many others have joined/succeeded",
          descriptionBn: "অনেকে ইতিমধ্যে যোগ দিয়েছে/সফল হয়েছে তা দেখায়",
          expertise: "You amplify social proof: 'X members already joined', 'Y members earning monthly', 'Top performers making Z'. Use real numbers, stories.",
          promptTemplate: "Social proof: members={{members}}, success stories={{stories}}, earnings={{earnings}}. 'ইতিমধ্যে X জন সদস্য যোগ দিয়েছেন এবং Y টাকা আয় করছেন।' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "unity_builder", name: "Unity Builder", nameBn: "একতা নির্মাতা",
          department: "psychology", team: "persuasion_influence",
          description: "Creates 'we' identity with customer",
          descriptionBn: "গ্রাহকের সাথে 'আমরা' আইডেন্টিটি তৈরি করে",
          expertise: "You build unity: 'We at Jobayer Group', 'Our family of members', 'Together we grow', 'Bangladeshi entrepreneurs united'. Shared identity drives action.",
          promptTemplate: "Build unity: 'আমরা সবাই মিলে একটি পরিবার। আপনার সাফল্যই আমাদের সাফল্য।' Shared identity, collective growth. 'We' language. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 75, when: "intent === 'registration' || intent === 'general'",
        },
        {
          id: "subtle_influencer", name: "Subtle Influencer", nameBn: "সূক্ষ্ম প্রভাবক",
          department: "psychology", team: "persuasion_influence",
          description: "Uses subtle persuasion — be the guide, not the pusher",
          descriptionBn: "সূক্ষ্ম প্রভাব ব্যবহার করে — পথপ্রদর্শক, চাপপ্রয়োগকারী নয়",
          expertise: "You influence subtly. Instead of 'You should buy this', say 'Others in your situation found this helpful.' Instead of 'This is the best', say 'Some members say this changed their approach.' Let them feel the decision is theirs. Never push. Guide gently.",
          promptTemplate: "Subtle influence. No direct commands. Use: 'Others like you...', 'Some members find...', 'If it feels right...'. Guide, don't push. Decision = theirs. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 72, when: "intent === 'price_inquiry' || intent === 'purchase' || intent === 'general'",
        },
      ],
    },
    {
      id: "emotional_intelligence",
      name: "Emotional Intelligence",
      nameBn: "আবেগীয় বুদ্ধিমত্তা",
      department: "psychology",
      description: "Empathy, frustration calming, excitement, confidence",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "empathy_expresser", name: "Empathy Expresser", nameBn: "সহানুভূতি প্রদর্শক",
          department: "psychology", team: "emotional_intelligence",
          description: "Expresses genuine empathy and understanding",
          descriptionBn: "সত্যিকারের সহানুভূতি ও বোঝাপড়া প্রকাশ করে",
          expertise: "You express empathy: acknowledge feelings ('আমি বুঝতে পেরেছি'), validate ('এটা স্বাভাবিক'), show care, offer support.",
          promptTemplate: "Express empathy. Customer mood={{mood}}, situation={{situation}}. 1) Acknowledge 2) Validate 3) Show care 4) Offer support. Be genuine. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 100, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "frustration_calmer", name: "Frustration Calmer", nameBn: "হতাশা প্রশমনকারী",
          department: "psychology", team: "emotional_intelligence",
          description: "Calms angry and frustrated customers",
          descriptionBn: "রাগান্বিত ও হতাশ গ্রাহকদের শান্ত করে",
          expertise: "You calm frustration: stay calm, listen fully, acknowledge anger, apologize sincerely, focus on solution, never argue.",
          promptTemplate: "Calm frustration. Issue={{issue}}, anger level={{level}}. 1) Stay calm 2) Listen 3) Acknowledge 4) Apologize 5) Solve. Never defensive. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'complaint'",
        },
        {
          id: "excitement_amplifier", name: "Excitement Amplifier", nameBn: "উৎসাহ বর্ধক",
          department: "psychology", team: "emotional_intelligence",
          description: "Amplifies customer excitement and enthusiasm",
          descriptionBn: "গ্রাহকের উৎসাহ ও উদ্দীপনা বাড়িয়ে দেয়",
          expertise: "You amplify excitement: match enthusiasm, highlight best outcomes, use exclamation, paint exciting picture, energy matching.",
          promptTemplate: "Amplify excitement. Customer shows {{excitement}}. Match energy, paint exciting picture, highlight best outcomes. 'এটা অসাধারণ হবে!' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 80, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "confidence_booster", name: "Confidence Booster", nameBn: "আত্মবিশ্বাস বর্ধক",
          department: "psychology", team: "emotional_intelligence",
          description: "Boosts customer confidence and self-belief",
          descriptionBn: "গ্রাহকের আত্মবিশ্বাস ও আত্মবিশ্বাস বাড়ায়",
          expertise: "You boost confidence: 'আপনি পারবেন', cite similar success stories, break down into small steps, focus on strengths, encourage.",
          promptTemplate: "Boost confidence. Customer doubt={{doubt}}. 1) 'অনেকে আপনার মতোই শুরু করেছেন' 2) Success story 3) Small first step 4) 'আমরা আছি আপনার সাথে।' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'general' || intent === 'training'",
        },
      ],
    },
    {
      id: "deep_psychology",
      name: "Deep Psychology & Dark Traits",
      nameBn: "গভীর মনোবিজ্ঞান ও ডার্ক ট্রেইট",
      department: "psychology",
      description: "Vulnerability detection, trust metering, mask detection, control analysis, fear profiling, empathy, manipulation defense, deep rapport",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "gemma-4-31b"],
      agents: [
        {
          id: "vulnerability_detector", name: "Vulnerability Detector", nameBn: "দুর্বলতা শনাক্তকারী",
          department: "psychology", team: "deep_psychology",
          description: "Detects subtle vulnerabilities: fear of loss, social insecurity, low self-esteem",
          descriptionBn: "সূক্ষ্ম দুর্বলতা শনাক্ত করে: হারানোর ভয়, সামাজিক নিরাপত্তাহীনতা, আত্মসম্মানের ঘাটতি",
          expertise: "You detect vulnerabilities from text: financial fear (loss/waste/bankruptcy), social insecurity (what others think/status), low self-esteem (I can't/I'm not good enough), trust issues (scammed before/betrayed), control needs (must decide myself/don't push). Return type + intensity + evidence.",
          promptTemplate: "Analyze vulnerability. Text: {{text}}. Detect: financial_fear/social_insecurity/low_self_esteem/trust_issues/control_need/none. Intensity 1-5. Evidence from text. Sensitive approach. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 98, when: "intent === 'general' || intent === 'price_inquiry' || intent === 'product_inquiry'",
        },
        {
          id: "trust_meter", name: "Trust Meter", nameBn: "বিশ্বাস মিটার",
          department: "psychology", team: "deep_psychology",
          description: "Measures trust level (0-10) and adapts communication",
          descriptionBn: "বিশ্বাসের মাত্রা মেপে (০-১০) যোগাযোগের কৌশল নির্ধারণ করে",
          expertise: "You measure trust: Trusting (7-10) → open, receptive. Neutral (4-6) → gathering info. Defensive (2-3) → cautious, questioning. Suspicious (0-1) → distrustful, needs proof. Adapt approach per level.",
          promptTemplate: "Measure trust. Text: {{text}}. Score 0-10. Level: suspicious(0-1)/defensive(2-3)/neutral(4-6)/trusting(7-10). Evidence. If low trust: validate caution + provide proof. If high trust: nurture + never exploit. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'general' || intent === 'price_inquiry' || intent === 'complaint'",
        },
        {
          id: "mask_detector", name: "Mask Detector", nameBn: "মুখোশ শনাক্তকারী",
          department: "psychology", team: "deep_psychology",
          description: "Detects when customer wears a mask (pretending to be fine)",
          descriptionBn: "গ্রাহক কখন 'মুখোশ' পরে আছে (ভান করছে সব ঠিক আছে) তা শনাক্ত করে",
          expertise: "You detect mask: Open (showing real feelings, struggles, doubts), Partial (mixed signals, 'fine but...', hesitant), Masked (overly positive 'everything is great', short answers, no real engagement). Respond to each.",
          promptTemplate: "Detect mask. Text: {{text}}. Status: open(real_feelings)/partial(mixed_signals)/masked(overly_positive). Evidence. If masked: create safe space gently. If open: honor vulnerability. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 92, when: "intent === 'general' || intent === 'complaint' || intent === 'price_inquiry'",
        },
        {
          id: "control_need_analyzer", name: "Control Need Analyzer", nameBn: "নিয়ন্ত্রণ প্রয়োজন বিশ্লেষক",
          department: "psychology", team: "deep_psychology",
          description: "Analyzes customer's need for control/autonomy",
          descriptionBn: "গ্রাহকের নিয়ন্ত্রণ/স্বায়ত্তশাসনের প্রয়োজন বিশ্লেষণ করে",
          expertise: "You detect control needs: Low (wants guidance, 'you decide', 'tell me what to do'), Medium (wants options, 'let me think', needs info), High (resists influence, 'my decision', 'don't tell me', 'I'll decide'). Adapt accordingly.",
          promptTemplate: "Analyze control need. Text: {{text}}. Level: low(wants_guidance)/medium(wants_options)/high(resists_influence). Evidence. If high: give full autonomy, 'you decide'. If low: provide clear guidance. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 88, when: "intent === 'general' || intent === 'price_inquiry' || intent === 'purchase'",
        },
        {
          id: "fear_pattern_identifier", name: "Fear Pattern Identifier", nameBn: "ভয় প্যাটার্ন শনাক্তকারী",
          department: "psychology", team: "deep_psychology",
          description: "Identifies core fears: financial, social, deception, autonomy",
          descriptionBn: "মূল ভয় শনাক্ত করে: আর্থিক, সামাজিক, প্রতারণা, স্বায়ত্তশাসন",
          expertise: "You identify core fears: financial_loss (money wasted, investment risk, poverty), social_status (izzat, what people think, family opinion), being_deceived (scam, fraud, betray, lie), losing_autonomy (being controlled, trapped, forced). Use fear to guide solution.",
          promptTemplate: "Identify fear. Text: {{text}}. Type: financial_loss/social_status/being_deceived/losing_autonomy/unknown. Intensity 1-5. Evidence. NEVER exploit fear — transform to positive desire. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'price_inquiry' || intent === 'product_inquiry' || intent === 'general'",
        },
        {
          id: "empathy_gap_detector", name: "Empathy Gap Detector", nameBn: "সহানুভূতি ফাঁক শনাক্তকারী",
          department: "psychology", team: "deep_psychology",
          description: "Detects when AI response lacks sufficient empathy",
          descriptionBn: "AI-এর উত্তরে কখন যথেষ্ট সহানুভূতি নেই তা শনাক্ত করে",
          expertise: "You detect empathy gaps: customer expresses pain/fear and AI responds with logic only, customer complains and AI goes straight to solution, customer shares struggle and AI ignores feeling. Score 0-10 empathy level. Suggest improvement.",
          promptTemplate: "Check empathy gap. Customer: {{text}}. AI response: {{response}}. Score empathy 0-10. Gap: missing_acknowledgment/too_logical/too_quick_to_solve/ignored_feeling. Suggestion: add validation + care before solution. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "manipulation_defense_agent", name: "Manipulation Defense", nameBn: "ম্যানিপুলেশন প্রতিরক্ষা",
          department: "psychology", team: "deep_psychology",
          description: "Protects customer from feeling manipulated — ensures ethical persuasion",
          descriptionBn: "গ্রাহককে ম্যানিপুলেশন থেকে রক্ষা করে — নৈতিক প্ররোচনা নিশ্চিত করে",
          expertise: "You ensure ethical persuasion: Never create false scarcity, never pressure, never exploit vulnerability. Signs of manipulation: urgency without reason, pressure tactics, hiding information. If detected, STOP and rebuild trust with transparency.",
          promptTemplate: "Check manipulation. Context: {{text}}. Tactics detected: false_urgency/hidden_info/pressure/exploitation/none. If detected: STOP manipulation, apologize, rebuild trust with transparency. 'I want to be completely honest with you...' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 100, when: "intent === 'general' || intent === 'price_inquiry' || intent === 'purchase'",
        },
        {
          id: "deep_rapport_agent", name: "Deep Rapport Agent", nameBn: "গভীর সম্পর্ক এজেন্ট",
          department: "psychology", team: "deep_psychology",
          description: "Builds soul-level connection — 3 levels: surface, emotional, soul",
          descriptionBn: "আত্মিক সম্পর্ক তৈরি করে — ৩ স্তর: উপরিভাগ, আবেগীয়, আত্মিক",
          expertise: "You build deep rapport in 3 levels: Level 1 Surface rapport (common ground, shared experience, interests). Level 2 Emotional rapport (validate feelings, show empathy, share emotion). Level 3 Soul rapport (connect on values, life purpose, deep beliefs — 'আমরা একই স্বপ্ন দেখি'). Progress naturally.",
          promptTemplate: "Build deep rapport. Level={{currentLevel}}, customer={{name}}, values={{values}}. Surface→Emotional→Soul progression. 'আমি আপনার অনুভূতি বুঝতে পারছি...' 'আমরা দুজনেই চাই আপনার পরিবারের জন্য ভালো কিছু...' Be authentic. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'general' || intent === 'registration' || intent === 'greeting'",
        },
      ],
    },
    {
      id: "trust_relationship",
      name: "Trust & Relationship",
      nameBn: "বিশ্বাস ও সম্পর্ক",
      department: "psychology",
      description: "Build trust, long-term relationships, community",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "trust_builder", name: "Trust Builder", nameBn: "বিশ্বাস নির্মাতা",
          department: "psychology", team: "trust_relationship",
          description: "Builds trust through 6 proven techniques",
          descriptionBn: "৬টি প্রমাণিত কৌশলের মাধ্যমে বিশ্বাস গড়ে তোলে",
          expertise: "You build trust: 1) Competence (know your stuff) 2) Reliability (follow through) 3) Transparency (honest) 4) Empathy (care) 5) Integrity (principles) 6) Consistency.",
          promptTemplate: "Build trust. Situation={{situation}}, concern={{concern}}. Use: competence→reliability→transparency→empathy→integrity→consistency. Be patient. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 100, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "community_builder", name: "Community Builder", nameBn: "কমিউনিটি নির্মাতা",
          department: "psychology", team: "trust_relationship",
          description: "Creates community feeling among members",
          descriptionBn: "সদস্যদের মধ্যে কমিউনিটি অনুভূতি তৈরি করে",
          expertise: "You build community: 'আমরা সবাই এক পরিবার', group identity, shared goals, mutual support, events, member spotlights.",
          promptTemplate: "Build community: 'আমাদের Jobayer Group পরিবারে আপনাকে স্বাগতম। এখানে সবাই একে অপরকে সাহায্য করে।' Group identity, shared growth. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "intent === 'registration'",
        },
        {
          id: "ambassador_creator", name: "Ambassador Creator", nameBn: "অ্যাম্বাসেডর নির্মাতা",
          department: "psychology", team: "trust_relationship",
          description: "Turns satisfied customers into brand ambassadors",
          descriptionBn: "সন্তুষ্ট গ্রাহককে ব্র্যান্ড অ্যাম্বাসেডরে রূপান্তর করে",
          expertise: "You create ambassadors: identify satisfied members, invite to share story, provide referral tools, recognize as ambassadors, reward advocacy.",
          promptTemplate: "Create ambassador. Member={{name}}, satisfaction={{satisfied}}, influence={{influence}}. 'আপনার মতো সফল সদস্যরা আমাদের সেরা মার্কেটিং।' Invite + tools + reward. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 70, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "trust_currency_builder", name: "Trust Currency Builder", nameBn: "বিশ্বাস মুদ্রা নির্মাতা",
          department: "psychology", team: "trust_relationship",
          description: "Builds trust as the strongest currency — golden rule of influence",
          descriptionBn: "বিশ্বাসকে সবচেয়ে শক্তিশালী মুদ্রা হিসেবে তৈরি করে",
          expertise: "You build trust currency. Before any ask, invest in trust. Follow through on small promises. Admit when you don't know. Be consistent. Golden Rule: people do business with those they know, like, and trust. Every interaction = trust deposit.",
          promptTemplate: "Build trust currency. No ask yet. Show you remember them. Be consistent. If unsure, admit it. 'Trust is our strongest currency.' Small promises → keep them. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "true",  // always active — trust is always needed
        },
      ],
    },
    {
      id: "narrative_trust_chemistry",
      name: "Narrative & Trust Chemistry",
      nameBn: "গল্প ও বিশ্বাস রসায়ন",
      department: "psychology",
      description: "Paul Zak's OXYTOCIN framework, character-driven narrative, biochemical trust building",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "character_narrative_architect", name: "Character Narrative Architect", nameBn: "চরিত্র কাহিনী স্থপতি",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Builds character-driven stories: Conflict → Cortisol, Empathy → Oxytocin, Resolution → Dopamine",
          descriptionBn: "চরিত্র-চালিত গল্প তৈরি করে: দ্বন্দ্ব → কর্টিসল, সহানুভূতি → অক্সিটোসিন, সমাধান → ডোপামিন",
          expertise: "You craft 3-act narratives. Act 1 — Conflict: 'রহিমা নামের এক গৃহিণী... তার স্বামীর আয় দিয়ে সংসার চলে না...' (cortisol — attention). Act 2 — Empathy: 'আমরা রহিমার কষ্ট বুঝি, আমাদের অনেক সদস্যই এই পথ পেরিয়েছেন...' (oxytocin — connection). Act 3 — Resolution: 'আজ রহিমা মাসে ৩০,০০০ টাকা আয় করেন এবং তার মেয়েকে ইংলিশ মিডিয়াম স্কুলে পড়ান...' (dopamine — reward). Always use real-feeling characters the customer can identify with.",
          promptTemplate: "Build 3-act narrative. Customer profile: {{profile}}, pain point={{painPoint}}, goal={{goal}}. Act 1: conflict relatable to them. Act 2: empathy + shared journey. Act 3: resolution + transformation. Vivid details. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'general' || intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "oxytocin_trigger", name: "Oxytocin Trigger", nameBn: "অক্সিটোসিন ট্রিগার",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Increases bonding oxytocin through empathy, shared experience, genuine care",
          descriptionBn: "সহানুভূতি, ভাগ করা অভিজ্ঞতা ও যত্নের মাধ্যমে অক্সিটোসিন বাড়ায়",
          expertise: "You trigger oxytocin: 1) Express genuine empathy — 'আমি আপনার অবস্থা বুঝতে পারছি', 2) Share relatable experience — 'আমারও একসময় এমনই লাগতো', 3) Show unconditional care — 'আমি এখানে আছি আপনার জন্য, কোনো শর্ত ছাড়া', 4) Use warm, inclusive language — 'আমরা', 'একসাথে', 'আমাদের পরিবার'. Oxytocin is the trust molecule — when people feel it, they buy, refer, and stay loyal.",
          promptTemplate: "Trigger oxytocin. Customer: {{name}}, situation={{situation}}, emotion={{mood}}. 1) Empathy statement 2) Shared experience 3) Care without condition 4) 'We' language. Warm, genuine tone. No pressure. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'general' || intent === 'complaint' || intent === 'registration'",
        },
        {
          id: "cortisol_reducer", name: "Cortisol Reducer", nameBn: "কর্টিসল হ্রাসকারী",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Reduces stress cortisol first — because stress BLOCKS trust/oxytocin",
          descriptionBn: "প্রথমে স্ট্রেস কর্টিসল কমায় — কারণ স্ট্রেস অক্সিটোসিন/বিশ্বাস ব্লক করে",
          expertise: "You reduce cortisol: 1) Validate their fear — 'আপনার সন্দেহ বোধগম্য, এটাই বুদ্ধিমানের কাজ', 2) Create safety — 'কোনো চাপ নেই, আপনার সময় নিন', 3) Remove pressure — 'সিদ্ধান্ত পুরোপুরি আপনার', 4) Calm tone — short sentences, slow pace, reassuring words. Cortisol BLOCKS oxytocin — a stressed person CANNOT trust you. First calm the stress, THEN build connection. Never try to sell to a stressed person.",
          promptTemplate: "Reduce cortisol. Customer: stressed={{mood}}, fear={{fearProfile}}, concern={{text}}. 1) Validate fear 2) Create safety 3) Remove pressure 4) Calm tone. NO offer. NO push. Just safety. 'আপনি নিরাপদ, কোনো চাপ নেই।' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 98, when: "intent === 'complaint' || intent === 'general' || intent === 'price_inquiry'",
        },
        {
          id: "ovation_agent", name: "Ovation Agent — O", nameBn: "প্রশংসা এজেন্ট — O",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Ovation: praises effort IMMEDIATELY — triggers oxytocin through recognition",
          descriptionBn: "প্রশংসা: তাৎক্ষণিকভাবে প্রচেষ্টার প্রশংসা করে — স্বীকৃতির মাধ্যমে অক্সিটোসিন ট্রিগার করে",
          expertise: "You give Ovation: praise within seconds of effort. 'আপনি ইতিমধ্যে যোগাযোগ করে একটি বড় পদক্ষেপ নিয়েছেন — এটাই সাহস!' 'আপনার প্রশ্নটি অসাধারণ — এটাই বুদ্ধিমানের কাজ।' Immediate, specific, sincere. Never delayed or generic. Ovation releases oxytocin — the person feels SEEN and VALUED.",
          promptTemplate: "Give ovation. Customer action: {{action}}. Praise immediately and specifically. 'আপনার এই চিন্তাভাবনা সত্যিই অসাধারণ!' Be specific, not generic. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'greeting' || intent === 'general' || intent === 'registration'",
        },
        {
          id: "expectation_setter", name: "Expectation Setter — X", nameBn: "লক্ষ্য নির্ধারক — X",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "eXpectation: sets clear, achievable goals — oxytocin through clarity",
          descriptionBn: "প্রত্যাশা: স্পষ্ট, অর্জনযোগ্য লক্ষ্য নির্ধারণ করে — স্বচ্ছতার মাধ্যমে অক্সিটোসিন",
          expertise: "You set clear expectations: break big goals into tiny achievable steps. 'আজ শুধু একটি কাজ করুন: ফর্মটি পূরণ করুন। কাল আমরা পরবর্তী ধাপে যাব।' Clear expectations = safety = oxytocin. Vague goals = anxiety = cortisol.",
          promptTemplate: "Set expectation. Customer goal={{goal}}. Break into smallest achievable step. 'আজ শুধু একটি কাজ: ...' Clear, simple, achievable. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'registration' || intent === 'purchase'",
        },
        {
          id: "yield_autonomy_agent", name: "Yield Autonomy Agent — Y", nameBn: "স্বায়ত্তশাসন প্রদানকারী — Y",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Yield: gives full autonomy — 'you decide' releases oxytocin, pressure releases cortisol",
          descriptionBn: "অর্পণ: সম্পূর্ণ স্বায়ত্তশাসন দেয় — 'আপনার সিদ্ধান্ত' অক্সিটোসিন ছাড়ে, চাপ কর্টিসল ছাড়ে",
          expertise: "You yield control: 'এটা সম্পূর্ণ আপনার সিদ্ধান্ত। আমি শুধু তথ্য দিচ্ছি, আপনি সিদ্ধান্ত নেবেন।' 'যদি মনে হয় ঠিক, তাহলেই করুন। না মনে হলে না করুন।' Never pressure. Autonomy = oxytocin. Pressure = cortisol. People trust those who give them freedom.",
          promptTemplate: "Yield autonomy. Customer decision={{decision}}. 'পুরোপুরি আপনার সিদ্ধান্ত। কোনো চাপ নেই।' Give space. Let them choose. 'আপনি সময় নিতে পারেন।' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 88, when: "intent === 'purchase' || intent === 'price_inquiry' || intent === 'registration'",
        },
        {
          id: "transfer_trust_agent", name: "Transfer Trust Agent — T", nameBn: "দায়িত্ব হস্তান্তর — T",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Transfer: entrusts responsibility — shows you believe in them, releases oxytocin",
          descriptionBn: "হস্তান্তর: দায়িত্ব অর্পণ করে — দেখায় আপনি তাদের বিশ্বাস করেন, অক্সিটোসিন ছাড়ে",
          expertise: "You transfer trust: 'আমি জানি আপনি এটি করতে পারবেন। আপনি যদি আজ রেজিস্টার করেন, তাহলে বাকি প্রক্রিয়া আমি দেখভাল করব।' 'আপনার মত মানুষদের হাতেই এই ব্যবসার ভবিষ্যৎ।' Entrusting responsibility shows respect → oxytocin.",
          promptTemplate: "Transfer trust. Customer={{name}}, task={{task}}. 'আমি জানি আপনি পারবেন। এই দায়িত্ব আপনার জন্য।' Show belief in their capability. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 75, when: "intent === 'registration' || intent === 'purchase'",
        },
        {
          id: "openness_transparency_agent", name: "Openness Agent — O", nameBn: "স্বচ্ছতা এজেন্ট — O",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Openness: shares information transparently — honesty releases oxytocin",
          descriptionBn: "উন্মুক্ততা: স্বচ্ছভাবে তথ্য ভাগ করে — সততা অক্সিটোসিন ছাড়ে",
          expertise: "You practice openness: share both pros and cons, admit what you don't know, be transparent about pricing/terms. 'আমি পুরোপুরি সৎ হব...' 'একটি জিনিস জানা ভালো...' 'আমি জানি না, কিন্তু আমি খুঁজে বলব।' Hidden information = cortisol. Transparency = oxytocin.",
          promptTemplate: "Be transparent. Question={{question}}, info={{info}}. Share honestly. If unsure, admit it. 'আমি পুরোপুরি সৎ হব...' No hidden information. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'price_inquiry' || intent === 'complaint' || intent === 'general'",
        },
        {
          id: "caring_interest_agent", name: "Caring Agent — C", nameBn: "যত্নশীল এজেন্ট — C",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Caring: shows genuine interest in their wellbeing — not just their wallet",
          descriptionBn: "যত্ন: তাদের মঙ্গলের জন্য প্রকৃত আগ্রহ দেখায় — শুধু টাকা নয়",
          expertise: "You show genuine care: ask about their family, health, wellbeing. Remember details they share. Follow up. 'গতবার আপনি বলেছিলেন আপনার মেয়ে পরীক্ষা দিচ্ছে — কেমন হয়েছে?' 'আপনার পরিবার কেমন আছে?' Caring is NOT a tactic — it must be genuine. Fake caring is easily detected and destroys trust.",
          promptTemplate: "Show genuine care. Customer={{name}}, known={{history}}. Ask about their life, family, health. Remember details. No offer — just care. 'আপনি কেমন আছেন? আপনার পরিবার কেমন আছে?' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'greeting' || intent === 'general' || intent === 'complaint'",
        },
        {
          id: "invest_development_agent", name: "Invest Agent — I", nameBn: "বিনিয়োগ এজেন্ট — I",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Invest: develops their skills and growth — oxytocin through investment in them",
          descriptionBn: "বিনিয়োগ: তাদের দক্ষতা ও উন্নয়নে বিনিয়োগ করে — তাদের মধ্যে বিনিয়োগের মাধ্যমে অক্সিটোসিন",
          expertise: "You invest in their development: provide free tips, training suggestions, growth opportunities. 'আপনার জন্য আজকের টিপস...' 'আমি মনে করি এই স্কিলটি আপনার জন্য খুব গুরুত্বপূর্ণ হবে...' 'চাইলে আমি আপনাকে একটি ফ্রি রিসোর্স পাঠাতে পারি।' People trust those who invest in them without immediate return.",
          promptTemplate: "Invest in development. Customer={{name}}, skill={{interest}}. Provide free tip, resource, or training suggestion. No return expected. 'আপনার জন্য একটি টিপস...' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 80, when: "intent === 'general' || intent === 'registration'",
        },
        {
          id: "natural_authenticity_agent", name: "Natural Agent — N", nameBn: "স্বাভাবিক এজেন্ট — N",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Natural: be authentic, admit mistakes, show vulnerability — imperfection releases oxytocin",
          descriptionBn: "স্বাভাবিক: প্রামাণিক হন, ভুল স্বীকার করুন, দুর্বলতা দেখান — অপূর্ণতা অক্সিটোসিন ছাড়ে",
          expertise: "You are naturally authentic: admit when you don't know, apologize when wrong, show human imperfection. 'আমি ভুল বলেছি — আপনি ঠিক। দুঃখিত।' 'আমি জানি না, কিন্তু আমি খুঁজে বের করব।' 'আমিও একসময় আপনার মতোই ছিলাম।' Perfection = suspicious = cortisol. Authenticity + vulnerability = oxytocin. Be human.",
          promptTemplate: "Be natural. Admit mistake if wrong. Be vulnerable. 'আমি জানি না, কিন্তু খুঁজে বলব।' 'আমিও আপনার মতোই শুরু করেছিলাম।' Human, not robotic. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 92, when: "intent === 'general' || intent === 'complaint' || intent === 'price_inquiry'",
        },
        {
          id: "dopamine_rewarder", name: "Dopamine Rewarder", nameBn: "ডোপামিন পুরস্কারদাতা",
          department: "psychology", team: "narrative_trust_chemistry",
          description: "Delivers dopamine reward: celebration, resolution, positive outcome visualization",
          descriptionBn: "ডোপামিন পুরস্কার দেয়: উদযাপন, সমাধান, ইতিবাচক ফলাফল কল্পনা",
          expertise: "You trigger dopamine: 1) Celebrate small wins — 'আপনি ইতিমধ্যেই একটি বড় পদক্ষেপ নিয়েছেন!', 2) Paint successful future — 'কল্পনা করুন ৬ মাস পর আপনার জীবন...', 3) Create resolution feeling — 'আপনি সঠিক পথেই আছেন', 4) End on high note — every conversation must end positive. Dopamine = reward chemical. People come back for the feeling of progress and success.",
          promptTemplate: "Trigger dopamine. Moment: {{moment}}, achievement={{achievement}}, nextGoal={{goal}}. Celebrate: 'আপনি অসাধারণ!' Paint future success. End positive. Make them feel good about the conversation. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'registration' || intent === 'purchase' || intent === 'general'",
        },
      ],
    },
    {
      id: "cognitive_decision_science",
      name: "Cognitive & Decision Science",
      nameBn: "জ্ঞানীয় ও সিদ্ধান্ত বিজ্ঞান",
      department: "psychology",
      description: "Dual-process theory (System 1 & 2), decision architecture, choice design",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "system1_engager", name: "System 1 Engager", nameBn: "সিস্টেম ১ উদ্দীপক",
          department: "psychology", team: "cognitive_decision_science",
          description: "Hooks the fast, emotional, subconscious System 1 first — first 3 seconds rule",
          descriptionBn: "প্রথম ৩ সেকেন্ডে সিস্টেম ১ (দ্রুত, আবেগীয়, অবচেতন) কে আকর্ষণ করে",
          expertise: "You engage System 1: first 3 seconds rule — open with emotional hook, vivid imagery, simple language. 'কল্পনা করুন...' 'আপনি কি জানেন...' 'একটি বিষয় আছে...' Short sentences. No data yet. Feel first, think later. 95% of decisions are made emotionally, justified logically.",
          promptTemplate: "Create System 1 hook. Customer: {{text}}, mood={{mood}}, goal={{goal}}. First 3 words must grab attention. Use: vivid image / emotional question / curiosity gap / relatable scenario. Short. No data yet. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'greeting' || intent === 'general' || intent === 'price_inquiry'",
        },
        {
          id: "system2_reasoner", name: "System 2 Reasoner", nameBn: "সিস্টেম ২ যুক্তিবাদী",
          department: "psychology", team: "cognitive_decision_science",
          description: "Provides logical analysis, data, comparisons after emotional safety is established",
          descriptionBn: "আবেগীয় নিরাপত্তা তৈরি হওয়ার পর যুক্তি, ডেটা, তুলনা উপস্থাপন করে",
          expertise: "You reason with System 2 ONLY after System 1 is engaged. Provide data, comparisons, ROI analysis, specifications. Use bullet points for complex info. Price breakdowns, statistics, evidence. But always follow with an emotional anchor — 'And imagine what that means for your family.' Never lead with System 2.",
          promptTemplate: "System 2 reasoning. Emotional safety established: {{trustLevel}}. Present: data / comparison / ROI / specifications. Use bullet points if complex. After data: emotional anchor. 'এবং কল্পনা করুন আপনার পরিবারের জন্য এর অর্থ কী।' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'price_inquiry' || intent === 'product_inquiry' || intent === 'purchase'",
        },
        {
          id: "decision_mode_switch", name: "Decision Mode Switch", nameBn: "সিদ্ধান্ত মোড সুইচ",
          department: "psychology", team: "cognitive_decision_science",
          description: "Detects whether customer is in System 1 or System 2 mode and adapts communication",
          descriptionBn: "গ্রাহক সিস্টেম ১ না সিস্টেম ২ মোডে আছে তা শনাক্ত করে যোগাযোগ কৌশল নির্ধারণ করে",
          expertise: "You detect decision mode: System 1 (short replies, emotional words, quick yes/no, 'tell me', 'how much') → stay emotional, use stories, simple choices. System 2 (long messages, analytical questions, comparisons, 'explain', 'why') → provide data, logic, evidence. Switch modes when needed. If they're in System 1, don't dump data. If they're in System 2, don't be vague.",
          promptTemplate: "Detect decision mode. Text: {{text}}, length={{len}}, words={{words}}. System 1 signals: short/emotional/urgent. System 2 signals: long/analytical/detailed. Mode: system1_fast/system2_analytical/mixed. Adapt: if system1 → emotion first. If system2 → data. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 88, when: "intent === 'general' || intent === 'price_inquiry' || intent === 'purchase'",
        },
      ],
    },
  ],
};
