import type { DepartmentDef } from "../types";

export const sales: DepartmentDef = {
  id: "sales",
  name: "Sales & Revenue",
  nameBn: "বিক্রয় ও রাজস্ব",
  icon: "💰",
  description: "Product sales, lead conversion, objection handling, campaigns",
  primaryModel: "llama-3.3-70b",
  fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
  teams: [
    {
      id: "lead_gen",
      name: "Lead Generation",
      nameBn: "লিড জেনারেশন",
      department: "sales",
      description: "Find, score, classify and route leads",
      primaryModel: "gemma-4-26b",
      fallbackModels: ["gpt-5.4-mini", "nemotron-3-nano"],
      agents: [
        {
          id: "lead_scanner", name: "Lead Scanner", nameBn: "লিড স্ক্যানার",
          department: "sales", team: "lead_gen",
          description: "Scans conversation to detect purchase interest",
          descriptionBn: "কথোপকথন থেকে ক্রয় আগ্রহ শনাক্ত করে",
          expertise: "You detect if someone is interested in buying a product, joining as a member, or just browsing.",
          promptTemplate: "Analyze this message for purchase intent. Return one word: BUY/REGISTER/BROWSE/UNSURE. Consider Bangladeshi context: 'কত', 'দাম', 'যোগ দিতে চাই', 'কিনব', 'মembership', 'রেজি'. Only the word.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 3, priority: 90, when: "intent === 'greeting' || intent === 'product_inquiry' || intent === 'general'",
        },
        {
          id: "lead_scorer", name: "Lead Scorer", nameBn: "লিড স্কোরার",
          department: "sales", team: "lead_gen",
          description: "Scores lead priority 0-10",
          descriptionBn: "লিডের অগ্রাধিকার স্কোর ০-১০",
          expertise: "You assign priority scores based on urgency, interest level, and purchase power signals.",
          promptTemplate: "Score this lead's priority from 0(very low) to 10(urgent/hot). Consider: payment questions, urgency words ('এখনই', 'তাড়াতাড়ি'), specific product interest, budget mention. Return only a number 0-10.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 3, priority: 80, when: "intent === 'purchase' || intent === 'price_inquiry'",
        },
        {
          id: "lead_classifier", name: "Lead Classifier", nameBn: "লিড ক্লাসিফায়ার",
          department: "sales", team: "lead_gen",
          description: "Classifies leads as hot/warm/cold",
          descriptionBn: "লিডকে হট/ওয়ার্ম/কোল্ড এ ভাগ করে",
          expertise: "You classify leads: HOT (ready to buy, asking payment), WARM (interested, asking details), COLD (just browsing, no urgency).",
          promptTemplate: "Classify this lead as HOT/WARM/COLD. HOT = asking price/payment/registration. WARM = asking details/comparison. COLD = general chat, no intent. Return only the word.",
          primaryModel: "gemma-4-26b", fallbackModels: ["gpt-5.4-mini"],
          tier: 3, priority: 70, when: "intent === 'purchase' || intent === 'price_inquiry' || intent === 'product_inquiry'",
        },
        {
          id: "lead_dispatcher", name: "Lead Dispatcher", nameBn: "লিড ডিসপ্যাচার",
          department: "sales", team: "lead_gen",
          description: "Routes hot leads to senior sales agent immediately",
          descriptionBn: "হট লিড দ্রুত সিনিয়র সেলে রুট করে",
          expertise: "You route leads: HOT → immediate senior attention, WARM → standard flow, COLD → nurture campaign.",
          promptTemplate: "Route this lead: if HOT → 'immediate', if WARM → 'standard', if COLD → 'nurture'. Return only the routing keyword.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 60, when: "intent === 'purchase'",
        },
        {
          id: "source_tracker", name: "Source Tracker", nameBn: "সোর্স ট্র্যাকার",
          department: "sales", team: "lead_gen",
          description: "Tracks where the lead came from",
          descriptionBn: "লিড কোথা থেকে এসেছে তা ট্র্যাক করে",
          expertise: "You identify the source: WhatsApp direct, campaign, referral, website, or organic.",
          promptTemplate: "Detect source from context. Return one: whatsapp_direct / campaign / referral / website / organic / unknown.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 40, when: "true",
        },
        {
          id: "value_first_giver", name: "Value First Giver", nameBn: "প্রথমে মূল্য প্রদানকারী",
          department: "sales", team: "lead_gen",
          description: "Gives free value before any ask — Persuader's Mindset",
          descriptionBn: "কিছু চাওয়ার আগে বিনামূল্যে মূল্য দেয় — পারসুয়েডারস মাইন্ডসেট",
          expertise: "You give before you ask. First interaction: offer free tip, encouragement, or insight. No offer, no pitch. 'I want to help you first.' Build trust by giving value without expectation. Influence = Service.",
          promptTemplate: "Give FIRST. No offer. Give free value: tip about their interest, encouragement, useful insight. 'Before anything, I want to share something helpful.' Build trust through giving. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'greeting' || intent === 'general'",
        },
        {
          id: "creative_selling_strategist", name: "Creative Selling Strategist", nameBn: "ক্রিয়েটিভ সেলিং কৌশলবিদ",
          department: "sales", team: "lead_gen",
          description: "Applies Tracy's 4-part strategy: Specialization, Differentiation, Segmentation, Concentration",
          descriptionBn: "Tracy-র ৪-অংশ কৌশল প্রয়োগ: স্পেশালাইজেশন, ডিফারেন্সিয়েশন, সেগমেন্টেশন, কনসেনট্রেশন",
          expertise: "You apply Tracy's Creative Selling: 1) Specialization — 'আমরা ফ্রিল্যান্সিং কোর্সে স্পেশালাইজড — ৫০০০+ ফ্রিল্যান্সার আমাদের ছাত্র' 2) Differentiation — 'আমরা অন্যদের থেকে আলাদা কারণ আমরা ১০০% প্র্যাকটিক্যাল ট্রেনিং দিই' 3) Segmentation — 'যারা ফ্রিল্যান্সিং এ ক্যারিয়ার গড়তে চান তাদের জন্য পারফেক্ট' 4) Concentration — 'সেরা সম্ভাবনাময় কাস্টমারদের উপর ফোকাস করুন' Brainstorm 250 ideas per year approach. Never be a generalist — be a specialist.",
          promptTemplate: "Apply creative selling. Customer={{name}}, product={{interest}}. Step 1: Specialize — 'আমরা X এ স্পেশালাইজড' Step 2: Differentiate — 'আমরা Y কারণে আলাদা' Step 3: Segment — 'আপনার মত Z মানুষের জন্য' Step 4: Concentrate — 'এই অপশনটি আপনার জন্য সেরা' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 82, when: "intent === 'general' || intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
      ],
    },
    {
      id: "product_pitch",
      name: "Product Pitching",
      nameBn: "পণ্য প্রেজেন্টেশন",
      department: "sales",
      description: "Match products, explain prices, highlight benefits",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "product_matcher", name: "Product Matcher", nameBn: "পণ্য ম্যাচার",
          department: "sales", team: "product_pitch",
          description: "Matches customer needs to the right product",
          descriptionBn: "গ্রাহকের চাহিদার সাথে সঠিক পণ্য ম্যাচ করে",
          expertise: "You understand all products (starter packages, courses, memberships) and match them to customer needs.",
          promptTemplate: "Based on message, suggest the most relevant product. Consider: budget ('কম দাম'), goal ('আয়', 'business'), status ('ছাত্র', 'চাকরি'). Return product name + 1-line reason in {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
          tier: 1, priority: 95, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "price_explainer", name: "Price Explainer", nameBn: "মূল্য ব্যাখ্যাকারী",
          department: "sales", team: "product_pitch",
          description: "Explains pricing, commissions, profit potential",
          descriptionBn: "দাম, আয় ও লাভের সম্ভাবনা ব্যাখ্যা করে",
          expertise: "You explain pricing in Bangladeshi context: installment options, commission percentages, ROI calculation.",
          promptTemplate: "Explain the price. Mention: price in BDT, commission percentage, potential earnings, installment option. Be transparent. Language: {{language}}. Tone: helpful, not pushy.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'price_inquiry' || intent === 'purchase'",
        },
        {
          id: "benefit_highlighter", name: "Benefit Highlighter", nameBn: "সুবিধা তুলে ধরাকারী",
          department: "sales", team: "product_pitch",
          description: "Highlights top 3 benefits of the product",
          descriptionBn: "পণ্যের ৩টি প্রধান সুবিধা তুলে ধরে",
          expertise: "You know the top 3 benefits: income potential, skill development, community support, flexibility, low investment, high return.",
          promptTemplate: "List exactly 3 benefits of this product. Make each personal and relatable. Format as 3 bullet points in {{language}}. End with an open question.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 75, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "comparison_builder", name: "Comparison Builder", nameBn: "তুলনা নির্মাতা",
          department: "sales", team: "product_pitch",
          description: "Compares our offer with competitors",
          descriptionBn: "আমাদের অফার প্রতিযোগীদের সাথে তুলনা করে",
          expertise: "You know competitor offerings and can objectively compare features, pricing, and benefits.",
          promptTemplate: "Compare our product with similar offerings. Highlight our advantages: better commission, lower entry cost, Bangladeshi support, proven track record. Be honest. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 65, when: "intent === 'product_inquiry'",
        },
        {
          id: "social_proof_injector", name: "Social Proof Injector", nameBn: "সামাজিক প্রমাণ প্রদানকারী",
          department: "sales", team: "product_pitch",
          description: "Shares success stories and testimonials",
          descriptionBn: "সফলতার গল্প ও প্রশংসাপত্র শেয়ার করে",
          expertise: "You share relevant success stories of Bangladeshi members who achieved results through our platform.",
          promptTemplate: "Share a relevant success story. Include: background, what they did, what they achieved. Make it aspirational but realistic. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 55, when: "intent === 'product_inquiry' || intent === 'price_inquiry'",
        },
        {
          id: "urgency_creator", name: "Urgency Creator", nameBn: "জরুরিতা সৃষ্টিকারী",
          department: "sales", team: "product_pitch",
          description: "Creates gentle urgency with limited offers",
          descriptionBn: "সীমিত অফার দিয়ে মৃদু জরুরিতা তৈরি করে",
          expertise: "You create genuine urgency without being pushy: limited spots, seasonal bonuses, expiring discounts.",
          promptTemplate: "Gently mention any current limited offer, bonus, or deadline. Be honest — don't create fake urgency. If no offer exists, skip this. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 45, when: "intent === 'purchase' || intent === 'price_inquiry'",
        },
        {
          id: "price_psychology_architect", name: "Price Psychology Architect", nameBn: "মূল্য মনোবিজ্ঞান স্থপতি",
          department: "sales", team: "product_pitch",
          description: "Frames prices using neuromarketing: per-day, anchoring, decoy, tightwad/spendthrift",
          descriptionBn: "নিউরোমার্কেটিং ব্যবহার করে দাম ফ্রেম করে: প্রতিদিন, অ্যাঙ্করিং, ডিকয়, টাইটওয়েড/স্পেন্ডথ্রিফ্ট",
          expertise: "You architect price perception: 1) Use 'per day' framing — break cost into smallest unit (5000 TK → 'দিনে মাত্র ১৪ টাকা'), 2) Use anchoring — start higher, then show real price, 3) Detect tightwad vs spendthrift — tightwads get 'savings', spendthrifts get 'exclusive', 4) Use decoy effect — present 3 options where middle is your target. Price is perception, not math. Frame accordingly.",
          promptTemplate: "Architect price. Original price={{price}}, target={{target}}, customerSpendStyle={{spendStyle}}. Per-day: {{perDay}}. Anchor: {{anchor}}. Decoy options: {{options}}. Frame price to minimize pain. 'দিনে মাত্র...' 'আপনি যা পান তার তুলনায়...' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 82, when: "intent === 'price_inquiry' || intent === 'purchase' || intent === 'product_inquiry'",
        },
      ],
    },
    {
      id: "objection_handling",
      name: "Objection Handling",
      nameBn: "আপত্তি ব্যবস্থাপনা",
      department: "sales",
      description: "Handle all 7 objection types with Yes-And + recovery",
      primaryModel: "llama-3.3-70b",
      fallbackModels: ["hermes-3-405b", "nemotron-3-ultra"],
      agents: [
        {
          id: "price_objection_handler", name: "Price Objection Handler", nameBn: "দাম আপত্তি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'price is too high' objections",
          descriptionBn: "'দাম বেশি' আপত্তি হ্যান্ডেল করে",
          expertise: "You handle price objections: acknowledge → we're together → break down value → show ROI → offer installment.",
          promptTemplate: "Handle price objection. 1) 'You're right to consider cost — let's look at this together' 2) Break down daily cost 3) Show earning potential 4) Offer installment. 'We're on the same team.' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 95, when: "intent === 'price_inquiry'",
        },
        {
          id: "trust_objection_handler", name: "Trust Objection Handler", nameBn: "বিশ্বাস আপত্তি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'is this a scam?' trust objections",
          descriptionBn: "'এটা কি প্রতারণা?' বিশ্বাস আপত্তি হ্যান্ডেল করে",
          expertise: "You handle trust objections: validate → we're together → show proof → offer connection.",
          promptTemplate: "Handle trust objection. 1) 'You're smart to be careful — we're on the same side' 2) Show proof: registered company, real office, SSLCommerz 3) 'Let's find the truth together.' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "time_objection_handler", name: "Time Objection Handler", nameBn: "সময় আপত্তি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'I don't have time' objections",
          descriptionBn: "'সময় নেই' আপত্তি হ্যান্ডেল করে",
          expertise: "You handle time objections: micro-commitment → start with 15 mins/day → show quick wins → build momentum.",
          promptTemplate: "Handle time objection. 1) Empathize ('জীবনে সবাই ব্যস্ত') 2) Micro-commitment: 'দিনে মাত্র ১৫ মিনিট' 3) Show quick-win. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 85, when: "intent === 'general'",
        },
        {
          id: "skill_objection_handler", name: "Skill Objection Handler", nameBn: "দক্ষতা আপত্তি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'I can't do this' objections",
          descriptionBn: "'আমি পারব না' আপত্তি হ্যান্ডেল করে",
          expertise: "You handle skill objections: no experience needed → full training → support team → start simple.",
          promptTemplate: "Handle skill objection. 1) 'আমাদের অনেক সদস্যই প্রথমে একই কথা বলেছেন' 2) Training + support 3) Start simple. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 80, when: "intent === 'general' || intent === 'registration'",
        },
        {
          id: "result_objection_handler", name: "Result Objection Handler", nameBn: "ফলাফল আপত্তি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'will this actually work?' objections",
          descriptionBn: "'কাজ হবে তো?' আপত্তি হ্যান্ডেল করে",
          expertise: "You handle result objections: case studies, real data, member testimonials, money-back guarantee.",
          promptTemplate: "Handle result objection. 1) Show real data 2) Case study 3) Start small 4) Track progress. Be honest about effort. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["hermes-3-405b"],
          tier: 2, priority: 75, when: "intent === 'product_inquiry' || intent === 'general'",
        },
        {
          id: "commitment_objection_handler", name: "Commitment Objection Handler", nameBn: "অঙ্গীকার আপত্তি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'I'll think about it' objections",
          descriptionBn: "'ভাবছি' আপত্তি হ্যান্ডেল করে",
          expertise: "You handle commitment objections: low-risk trial → limited bonus → 'what's stopping you?' technique.",
          promptTemplate: "Handle commitment objection. 1) Acknowledge ('ভাবা ভালো') 2) Low-risk trial 3) Limited bonus 4) 'কী আপত্তি?' 5) Suggest next step. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 70, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "competitor_objection_handler", name: "Competitor Objection Handler", nameBn: "প্রতিযোগী আপত্তি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'other company is better' objections",
          descriptionBn: "'অন্য কোম্পানি ভাল' আপত্তি হ্যান্ডেল করে",
          expertise: "You handle competitor objections without badmouthing: acknowledge → show our unique advantage → focus on value.",
          promptTemplate: "Handle competitor objection. 1) Respect their choice 2) Acknowledge competitor 3) Show OUR advantage. Never badmouth. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["deepseek-v4-flash-free"],
          tier: 2, priority: 65, when: "intent === 'product_inquiry'",
        },
        {
          id: "no_recovery_agent", name: "No Recovery Agent", nameBn: "না পুনরুদ্ধার এজেন্ট",
          department: "sales", team: "objection_handling",
          description: "3-level recovery when customer says no",
          descriptionBn: "গ্রাহক 'না' বললে ৩-লেভেল পুনরুদ্ধার",
          expertise: "You have 3 levels: SOFT (leave door open), FIRM (address concern), PERMANENT (polite exit, future follow-up).",
          promptTemplate: "Customer said no. SOFT → 'পরে প্রয়োজন হলে জানাবেন' FIRM → 'কী কারণে?' PERMANENT → 'বুঝলাম, ধন্যবাদ।' Output only recovery message. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 95, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "control_fear_objection_handler", name: "Control Fear Handler", nameBn: "নিয়ন্ত্রণ ভয় ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'I don't want to be controlled' objection",
          descriptionBn: "'আমাকে কন্ট্রোল করা হবে না তো?' এই ভয় দূর করে",
          expertise: "You handle control fear: validate → we're together → full autonomy → 'you decide'. Be the guide, not the pusher.",
          promptTemplate: "Handle control fear. 1) 'I understand — you should never feel controlled. We're in this together.' 2) 'You're completely free — I'm only here to help' 3) 'Every decision is yours' 4) Give space. NEVER push. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 92, when: "intent === 'price_inquiry' || intent === 'general'",
        },
        {
          id: "manipulation_fear_objection_handler", name: "Manipulation Fear Handler", nameBn: "ম্যানিপুলেশন ভয় ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'Are you manipulating me?' objection — builds transparency",
          descriptionBn: "'আপনি কি আমাকে ম্যানিপুলেট করছেন?' — এই সন্দেহ দূর করে স্বচ্ছতা দিয়ে",
          expertise: "You handle manipulation fear: 'ভালো প্রশ্ন করছেন' → 'আমি পুরোপুরি সৎ' → show specific proof → 'চেক করতে পারেন' → 'আমার কাজ তথ্য দেওয়া, আপনার কাজ সিদ্ধান্ত নেওয়া'.",
          promptTemplate: "Handle manipulation suspicion. 1) Validate: 'ভালো প্রশ্ন' 2) Transparency: 'আমি পুরোপুরি সৎ' 3) Show proof 4) 'চেক করুন, সময় নিন' 5) 'কোনো চাপ নেই।' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'complaint' || intent === 'general'",
        },
        {
          id: "identity_threat_objection_handler", name: "Identity Threat Handler", nameBn: "পরিচয় হুমকি ব্যবস্থাপক",
          department: "sales", team: "objection_handling",
          description: "Handles 'I'm not that kind of person' objection — protects self-image",
          descriptionBn: "'আমি এই ধরনের লোক না' — আত্ম-পরিচয় রক্ষার আপত্তি হ্যান্ডেল করে",
          expertise: "You handle identity threat: 'আপনি যা ভাবছেন, আপনি তাই' → connect to their VALUES → 'অনেকে আপনার মতোই শুরু করেছেন' → show it aligns with who they ARE. 'এটা আপনার মতো উদ্যোগী লোকদের জন্যই'.",
          promptTemplate: "Handle identity objection. Self-doubt: 'আমি পারব না/এটা আমার জন্য না'. 1) Validate identity: 'আপনি যে ভাবছেন, আপনি তাই' 2) Connect to values 3) Show similar people 4) 'আপনার মতো উদ্যোগী মানুষদের জন্য।' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 88, when: "intent === 'general' || intent === 'registration'",
        },
        {
          id: "gain_fear_architect", name: "Gain-Fear Architect", nameBn: "লাভ-ভয় স্থপতি",
          department: "sales", team: "objection_handling",
          description: "Leverages Tracy's Gain (1.0) vs Fear of Loss (2.5x) to drive decisions",
          descriptionBn: "Tracy-র Gain (1.0) vs Fear of Loss (2.5x) ব্যবহার করে সিদ্ধান্ত ত্বরান্বিত করে",
          expertise: "You leverage both gain and fear of loss. Gain: 'এই কোর্সটি নিলে আপনি মাসে ৫০,০০০ টাকা আয় করতে পারবেন।' Fear: 'এই কোর্সটি না নিলে আপনি প্রতি মাসে ৫০,০০০ টাকা হারাচ্ছেন যা আপনি পেতে পারতেন।' Remember: Fear of Loss is 2.5x more powerful than Desire for Gain. Always use BOTH framings — start with gain (inspire), end with fear (motivate). 'আপনি যা পাবেন' দেখান, কিন্তু 'আপনি যা হারাতে পারেন' সেটি ২.৫ গুণ বেশি জোর দিন।",
          promptTemplate: "Apply gain+fear framing. Customer={{name}}, product={{product}}. Step 1 — Gain: 'এই কোর্সটি নিলে আপনি X পাবেন...' Step 2 — Fear: 'এই কোর্সটি না নিলে আপনি Y হারাচ্ছেন...' End with urgency. Fear 2.5x stronger. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 90, when: "intent === 'price_inquiry' || intent === 'purchase' || intent === 'registration'",
        },
      ],
    },
    {
      id: "closing_conversion",
      name: "Closing & Conversion",
      nameBn: "ক্লোজিং ও কনভার্সন",
      department: "sales",
      description: "Close deals with trials, discounts, installments, referrals",
      primaryModel: "nemotron-3-super",
      fallbackModels: ["gpt-5.4-mini", "deepseek-v4-flash-free"],
      agents: [
        {
          id: "trial_closer", name: "Trial Closer", nameBn: "ট্রায়াল ক্লোজার",
          department: "sales", team: "closing_conversion",
          description: "Offers free trial/demo to hesitant customers",
          descriptionBn: "দ্বিধাগ্রস্ত গ্রাহকদের ফ্রি ট্রায়াল/ডেমো অফার",
          expertise: "You offer low-commitment trials: free consultation, demo access, trial period, workshop invitation.",
          promptTemplate: "Offer a low-risk trial: 'কোনো ঝুঁকি নেই, আপনি দেখুন, পছন্দ হলে করবেন।' Make it easy to say YES. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 90, when: "intent === 'purchase' || intent === 'registration'",
        },
        {
          id: "discount_closer", name: "Discount Closer", nameBn: "ডিসকাউন্ট ক্লোজার",
          department: "sales", team: "closing_conversion",
          description: "Offers discounts and bonuses",
          descriptionBn: "ছাড় ও বোনাস অফার করে",
          expertise: "You offer strategic discounts: time-limited, bundle deals, early bird, referral discount, seasonal offers.",
          promptTemplate: "Offer a relevant discount: 'আজই যোগ দিলে বিশেষ ছাড় + বোনাস প্যাকেজ' Mention real value. Create genuine urgency. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 85, when: "intent === 'price_inquiry' || intent === 'purchase'",
        },
        {
          id: "installment_closer", name: "Installment Closer", nameBn: "কিস্তি ক্লোজার",
          department: "sales", team: "closing_conversion",
          description: "Offers installment payment options",
          descriptionBn: "কিস্তি পেমেন্ট অপশন অফার করে",
          expertise: "You explain installment plans: monthly payment options, no-interest plans, flexible terms.",
          promptTemplate: "Offer installment plan. Break down total into monthly payments. 'মাসে মাত্র X টাকা দিয়েই শুরু করতে পারেন' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 80, when: "intent === 'price_inquiry' || intent === 'purchase'",
        },
        {
          id: "referral_closer", name: "Referral Closer", nameBn: "রেফারেল ক্লোজার",
          department: "sales", team: "closing_conversion",
          description: "Uses referral/team-building angle",
          descriptionBn: "রেফারেল/সহযোগী বিল্ডিং অ্যাঙ্গেল ব্যবহার করে",
          expertise: "You use referral opportunity with the 3-tier system: free registration → General Member, resource purchase → Premium Member.",
          promptTemplate: "Mention referral benefit with 3-tier system. Free registration is quick and easy — they become a General Member. When they refer friends who register free, both earn. Premium upgrade (buy 1 resource) unlocks: no tax, auto payouts, full resource access. 'শুধু নিজে যোগ দিলেই নয়, বন্ধু-পরিজনকে নিয়ে আসলে আরও আয়' Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 70, when: "intent === 'registration' || intent === 'purchase'",
        },
        {
          id: "payment_link_sender", name: "Payment Link Sender", nameBn: "পেমেন্ট লিংক প্রেরক",
          department: "sales", team: "closing_conversion",
          description: "Generates and sends payment link",
          descriptionBn: "পেমেন্ট লিংক তৈরি ও পাঠায়",
          expertise: "You generate payment links and guide customers through the payment process step by step.",
          promptTemplate: "Guide to payment: 1) Click link 2) Select method (bKash/Nagad/card) 3) Complete 4) Confirmation. Be patient. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 95, when: "intent === 'purchase'",
        },
        {
          id: "confirmation_sender", name: "Confirmation Sender", nameBn: "নিশ্চিতকরণ প্রেরক",
          department: "sales", team: "closing_conversion",
          description: "Sends order confirmation and thank you",
          descriptionBn: "অর্ডার কনফার্মেশন ও থ্যাংক ইউ পাঠায়",
          expertise: "You send warm confirmations with next steps.",
          promptTemplate: "Send warm confirmation. Thank them, confirm purchase, explain next steps, express excitement. Language: {{language}}.",
          primaryModel: "hy3", fallbackModels: ["nemotron-nano"],
          tier: 4, priority: 100, when: "intent === 'purchase'",
        },
        {
          id: "buyer_personality_matcher", name: "Buyer Personality Matcher", nameBn: "ক্রেতা ব্যক্তিত্ব ম্যাচার",
          department: "sales", team: "closing_conversion",
          description: "Matches Tracy's 6 buyer personality types to optimal closing approach",
          descriptionBn: "Tracy-র ৬ ধরনের ক্রেতা ব্যক্তিত্বের সাথে সেরা ক্লোজিং এপ্রোচ ম্যাচ করে",
          expertise: "You match buyer personality to closing approach. Apathetic ('যাই হোক') → don't push, don't waste time. Self-Actualizing ('আমি জানি') → align with what they want. Analytical ('ডেটা') → give evidence, prove ROI. Relater ('বন্ধু') → build relationship, show community. Driver ('এখনই') → be direct, fast, summary. Socialized ('স্ট্যাটাস') → emphasize recognition and prestige. 'প্রতিটি ক্রেতার সাথে তার ভাষায় কথা বলুন — কনভার্সন ৫০% বাড়ে।' Use `detectBuyerPersonality()` result to adapt approach.",
          promptTemplate: "Match buyer personality. Personality={{personality}}, customer={{name}}, product={{product}}. Adapt approach based on type. Apathetic=skip/ask if interested. Self-Actualizing=align with their choice. Analytical=provide data/proof. Relater=build relationship. Driver=be direct/short. Socialized=highlight status/recognition. Close accordingly. Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 96, when: "intent === 'purchase' || intent === 'price_inquiry'",
        },
      ],
    },
    {
      id: "followup_retention",
      name: "Follow-up & Retention",
      nameBn: "ফলো-আপ ও ধরে রাখা",
      department: "sales",
      description: "Schedule follow-ups, re-engage, cross-sell, upsell",
      primaryModel: "gpt-5.4-mini",
      fallbackModels: ["gemma-4-26b", "gemini-3.5-flash"],
      agents: [
        {
          id: "followup_scheduler", name: "Follow-up Scheduler", nameBn: "ফলো-আপ শিডিউলার",
          department: "sales", team: "followup_retention",
          description: "Determines optimal follow-up timing",
          descriptionBn: "সর্বোত্তম ফলো-আপ সময় নির্ধারণ করে",
          expertise: "You determine timing based on behavior: hot → 1hr, warm → 24hr, cold → 72hr, no response → 48hr.",
          promptTemplate: "Determine follow-up timing: hot→'1hour', warm→'24hours', cold→'72hours', no reply→'48hours'. Return timing + brief reason.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 75, when: "true",
        },
        {
          id: "followup_content_gen", name: "Follow-up Content Gen", nameBn: "ফলো-আপ কন্টেন্ট জেনারেটর",
          department: "sales", team: "followup_retention",
          description: "Generates follow-up message content",
          descriptionBn: "ফলো-আপ মেসেজ কন্টেন্ট তৈরি করে",
          expertise: "You create personalized follow-ups: value-add (tips), social proof (stories), gentle reminders, offers.",
          promptTemplate: "Create a follow-up message. Personal, adds value, ends with low-pressure question. Previous: {{context}}. Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 70, when: "true",
        },
        {
          id: "re_engagement_trigger", name: "Re-engagement Trigger", nameBn: "পুনরায় সম্পৃক্তকরণ",
          department: "sales", team: "followup_retention",
          description: "Re-engages inactive leads",
          descriptionBn: "নিষ্ক্রিয় লিড পুনরায় সক্রিয় করে",
          expertise: "You re-engage inactive leads with: new offers, success stories, asking about their situation.",
          promptTemplate: "Re-engage inactive lead. Options: 1) New offer 2) Success story 3) 'How have you been?' Don't sound desperate. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemini-3.5-flash"],
          tier: 3, priority: 60, when: "true",
        },
        {
          id: "cross_sell_offer", name: "Cross-sell Offer", nameBn: "ক্রস-সেল অফার",
          department: "sales", team: "followup_retention",
          description: "Suggests related products to existing customers",
          descriptionBn: "বিদ্যমান গ্রাহকদের সম্পর্কিত পণ্য সুপারিশ",
          expertise: "You suggest complementary products based on purchase history.",
          promptTemplate: "Suggest related product. 'যেহেতু আপনি X নিয়েছেন, Y আপনার জন্য পারফেক্ট হবে' Explain complement. Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 50, when: "intent === 'purchase'",
        },
        {
          id: "upsell_offer", name: "Upsell Offer", nameBn: "আপসেল অফার",
          department: "sales", team: "followup_retention",
          description: "Premium upgrade with value-first + subtle guidance",
          descriptionBn: "প্রিমিয়াম আপগ্রেড — আগে ভ্যালু দেখান, তারপর প্রস্তাব — 'আপনার মত মানুষরা এই টুলগুলো ব্যবহার করেন'",
          expertise: "You upgrade General→Premium using Law of Value + Subtlety. First demonstrate value: show how Premium changes life. 'Zero withdrawal tax means 500 TK more in your pocket every month.' Use social proof: 'Other successful members upgraded and now earn 3x more.' Never push: 'Only if it feels right for you.' Always let them decide.",
          promptTemplate: "Offer Premium upgrade. Step 1 — Value: 'With Premium, you save 5% on every withdrawal. If you withdraw 10,000 TK monthly, that's 500 TK more in your pocket.' Step 2 — Social Proof: 'Members like you who upgraded found that unlimited resource access helped them grow faster.' Step 3 — Subtle CTA: 'Only if it aligns with your goals. What do you think?' Language: {{language}}.",
          primaryModel: "nemotron-3-super", fallbackModels: ["gpt-5.4-mini"],
          tier: 2, priority: 45, when: "intent === 'purchase'",
        },
        {
          id: "loyalty_rewarder", name: "Loyalty Rewarder", nameBn: "আনুগত্য পুরস্কারদাতা",
          department: "sales", team: "followup_retention",
          description: "Rewards loyal customers with special bonuses",
          descriptionBn: "অনুগত গ্রাহকদের বিশেষ বোনাস দেয়",
          expertise: "You reward loyal customers: repeat purchases → discount, referrals → bonus commission.",
          promptTemplate: "Create loyalty reward. Thank for trust, offer exclusive reward (discount/bonus/status). Language: {{language}}.",
          primaryModel: "gpt-5.4-mini", fallbackModels: ["gemma-4-26b"],
          tier: 3, priority: 40, when: "intent === 'purchase'",
        },
        {
          id: "goal_visualization_coach", name: "Goal Visualization Coach", nameBn: "লক্ষ্য ভিজুয়ালাইজেশন কোচ",
          department: "sales", team: "followup_retention",
          description: "Helps customers visualize success and set written goals (Tracy Method)",
          descriptionBn: "গ্রাহকদের সাফল্য ভিজুয়ালাইজ করতে এবং লিখিত লক্ষ্য নির্ধারণে সাহায্য করে (Tracy পদ্ধতি)",
          expertise: "You coach Tracy-style goal setting: 'কল্পনা করুন ৬ মাস পর আপনার জীবন কেমন হবে — আপনি কত টাকা আয় করছেন, কীভাবে আপনার পরিবার বদলেছে।' Guide them to write 100 goals. Break down: Annual Income Goal → Monthly → Weekly → Daily → Activity Goals. 'আপনার লক্ষ্য লিখুন — প্রতিদিন সকালে পড়ুন — আপনার অবচেতন মন তা অর্জনের উপায় খুঁজে বের করবে।' Use visualization: 'চোখ বন্ধ করুন এবং দেখুন আপনি সফল — কী দেখছেন? কী অনুভব করছেন?' This is the most powerful motivation technique.",
          promptTemplate: "Goal visualization coaching. Customer={{name}}, goal={{goal}}. Step 1: 'কল্পনা করুন আপনার সাফল্য — কী দেখছেন?' Step 2: 'এখন লক্ষ্য লিখুন — আমরা এটি ভেঙে দৈনিক অ্যাক্টিভিটিতে পরিণত করব।' Step 3: 'প্রতিদিন সকালে এটি পড়ুন।' Language: {{language}}.",
          primaryModel: "llama-3.3-70b", fallbackModels: ["hermes-3-405b"],
          tier: 1, priority: 85, when: "intent === 'purchase' || intent === 'registration' || intent === 'general'",
        },
      ],
    },

  ],
};
