import { NextResponse } from "next/server";
import { addKnowledgeEntry } from "@/lib/ai/knowledge-brain";
import { query } from "@/lib/db/queries";
import { ensureDB } from "@/lib/db";

interface Entry {
  category: string;
  title: string;
  content: string;
  sourceType: string;
  sourceName: string;
  tags: string[];
  confidence: number;
}

const SEED_BOOKS: Entry[] = [
  // ── Hooked: How to Build Habit-Forming Products — Nir Eyal ──
  { category:"psychology", title:"The Habit Zone — Why Habits Matter", content:"Habits are automatic behaviors triggered by situational cues, guiding nearly half of our daily actions without conscious thought. Products that create strong habits enjoy: higher Customer Lifetime Value (CLTV), pricing flexibility (customers become less price-sensitive), faster viral growth (shorter Viral Cycle Time), and a sharp competitive edge (users won't switch to 'better' products — old habits die hard). The goal: connect user's problem to your solution frequently enough to form a habit.", sourceType:"book", sourceName:"Hooked: How to Build Habit-Forming Products by Nir Eyal", tags:["hooked","nir-eyal","habits","psychology","product"], confidence:0.9 },
  { category:"psychology", title:"Trigger — External & Internal", content:"Triggers are the actuator of behavior. Two types: EXTERNAL (email, app icon, link — alert the user to take action) and INTERNAL (emotions, routines, situations — automatically cue the behavior). Winning products start as external triggers and, through repeated hooks, become associated with internal triggers. When users feel bored -> open Twitter. Lonely -> scroll Facebook. Question -> query Google. The first-to-mind solution wins. Identify the user's internal trigger (what itch are they scratching?) and build your external trigger to match.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","triggers","psychology"], confidence:0.9 },
  { category:"psychology", title:"Action — Fogg Behavior Model", content:"Behavior = Motivation + Ability + Trigger (all three must be present). MOTIVATION: 3 Core Motivators — seek pleasure/avoid pain, seek hope/avoid fear, seek social acceptance/avoid rejection. ABILITY: Simplicity = the path of least resistance. 6 factors of simplicity: Time, Money, Physical Effort, Brain Cycles, Social Deviance, Non-Routine. To increase likelihood of action, make it EASIER (remove friction) rather than trying to boost motivation. Remove steps until the desired action is as simple as possible.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","action","motivation","ability","fogg"], confidence:0.85 },
  { category:"psychology", title:"Variable Reward — The Craving Engine", content:"What distinguishes a Hook from a plain feedback loop is the ability to create CRAVING. Predictable rewards don't create desire (fridge light). Variable rewards trigger dopamine surges, suppressing judgment/reason and activating wanting/desire. Three types of variable rewards: 1) Tribe (rewards from others — social validation, approval), 2) Hunt (rewards of resources — money, information, goods), 3) Self (rewards of mastery — competence, completion, consistency). The variability, not the reward itself, drives engagement.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","variable-reward","dopamine","psychology"], confidence:0.85 },
  { category:"psychology", title:"Investment — Storing Value", content:"The Investment phase is where the user puts something into the product (time, data, effort, social capital, money). This increases the odds of future passes through the Hook cycle. Investments: invite friends, state preferences, build virtual assets, learn features, create content. These commitments: 1) improve the service for next use, 2) create stored value (the more users invest, the more valuable the service becomes to them), 3) prime users for future triggers. Loading the next trigger: after investment, ask what they want to do next.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","investment","retention","psychology"], confidence:0.85 },
  { category:"psychology", title:"The Morality of Manipulation", content:"Habit-forming technology is a superpower — it can be used for good or evil. The Manipulation Matrix: 2 dimensions — does the creator use the product themselves? (Yes/No) and does the product materially improve users' lives? (Yes/No). Four quadrants: Facilitator (Yes/Yes — use it and it helps), Peddler (No/Yes — don't use but helps), Entertainer (Yes/No — use it but doesn't help), Dealer (No/No — don't use and harms). Aspire to be a Facilitator: build products you use yourself that genuinely improve lives. Use choice architecture to nudge toward better decisions (as judged by the user themselves).", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","ethics","manipulation"], confidence:0.85 },
  { category:"strategy", title:"Habit Testing — 5 Questions", content:"To find habit-forming opportunities, ask: 1) What internal trigger is the user trying to satisfy? (What itch? What need?) 2) What brings users to your service in the first 3 seconds? 3) What is the expected reward? (Tribe/Hunt/Self) 4) What 'bit of work' do users do to increase future value? 5) What makes them come back? Test habit strength: How many users return voluntarily? How often? Do they show up without external prompting? Look for 'aha moments' — the instant users realize the value. The Habit Test: if 5%+ of your users come back daily unprompted, you're on the right track.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","testing","strategy"], confidence:0.85 },
  { category:"psychology", title:"The Bible App Case Study — Hook Model in Action", content:"The Bible App (YouVersion) reached 100M+ downloads through the Hook Model. TRIGGER: Daily reminders (external) -> guilt/desire to connect with God (internal). ACTION: Simple tap — one verse delivered. Extremely low friction. VARIABLE REWARD: Different verse every day, different plans, community reading, social sharing (Tribe reward). INVESTMENT: Highlighting verses, bookmarking, creating reading plans, inviting friends. Result: 80%+ of new users return the next day. Key lesson: even a 3,000-year-old product can be made habit-forming by applying the Hook Model correctly.", sourceType:"book", sourceName:"Hooked by Nir Eyal", tags:["hooked","nir-eyal","case-study","bible-app"], confidence:0.85 },

  // ── This Is Marketing — Seth Godin ──
  { category:"marketing", title:"Marketing Is the Act of Making Change", content:"Marketing isn't selling soap — it's making change happen. When you give a TED Talk, ask for a raise, raise money for a playground, or grow your team, you're marketing. Marketing seeks more (share, customers, work) but is driven by better (service, community, outcomes). It creates culture through status, affiliation, and belonging. The key question: 'Who can you help?' Marketing is the generous act of helping others change — to see a new possibility, to take a step forward, to become who they want to be.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","change"], confidence:0.9 },
  { category:"marketing", title:"The Marketer Learns to See — Empathy First", content:"Before you can change anyone, you must first SEE them. Empathy is the foundation of modern marketing. See people as they really are — their fears, dreams, worldviews, and the stories they tell themselves. Most marketers fail because they start with what they WANT to sell rather than what the customer NEEDS to hear. 'Sonder' — the realization that everyone around you has an inner life as rich and conflicted as yours. Marketing begins when you see the world through their eyes, not yours. Without empathy, you're not marketing — you're just talking to yourself.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","empathy"], confidence:0.9 },
  { category:"marketing", title:"The Smallest Viable Market", content:"Don't market to everyone. Market to the smallest viable audience — the minimum number of people you need to influence to make your effort worthwhile. 'Who's it for?' is the most powerful question in marketing. Choose people based on their WORLDVIEW (psychographics), not demographics. Specific is brave. A clear promise: 'My product is for people who believe ___. I will focus on people who want ___. I promise that engaging with what I make will help you get ___.' Start in a swimming pool, not the ocean. Serve your SVMA so well they can't help but tell others.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","audience","svma"], confidence:0.9 },
  { category:"marketing", title:"In Search of 'Better' — Better Is Subjective", content:"'Better' is not universal. 250+ beers are someone's favorite. People don't believe what you believe, know what you know, or want what you want. Empathy means accepting this. 'Better' depends on the person's worldview, status needs, fears, and desires. Dog food isn't bought by dogs — it's bought by dog owners who want to feel like good caregivers. What's 'better' for one person (cheap, efficient) is worse for another (premium, status). Your job: find a spot on the map that (some) people are looking for. Send up a signal flare so those looking for you can find you.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","better","psychology"], confidence:0.85 },
  { category:"marketing", title:"Beyond Commodities — Status and Belonging", content:"People don't buy commodities — they buy stories that signal status and create belonging. Every purchase is a shortcut: 'People like us do things like this.' Marketing creates culture by establishing what's normal, desirable, and valued. Key drivers: STATUS (dominance, respect, prestige), AFFILIATION (belonging, connection, community), and IDENTITY (this is who I am). Frame your offer in terms of the status it confers and the community it grants access to. People are seeking to belong to a group that shares their worldview — your product is the ticket.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","status","belonging","community"], confidence:0.85 },
  { category:"marketing", title:"Trust and Tension Create Forward Motion", content:"Marketing creates change through a cycle of tension and relief. CREATE TENSION: Show the gap between where they are and where they could be. This tension (dissonance, discomfort) motivates action. RELIEVE TENSION: Offer your product/service as the bridge. Trust is the currency that makes this work — they must trust that you can actually bridge the gap. Without trust, tension feels like manipulation. With trust, tension feels like a path forward. Build trust first (through consistency, transparency, generosity), then introduce productive tension.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","trust","tension"], confidence:0.85 },
  { category:"marketing", title:"Semiotics, Symbols, and Vernacular", content:"Everything communicates. Your logo, colors, words, tone, pricing, packaging, and even what you DON'T say sends signals. Semiotics: the study of signs and symbols. Every marketing choice signals to your audience: 'Are you one of us?' Use symbols that your smallest viable audience recognizes and resonates with. Speak their vernacular — the specific language, references, and cultural touchpoints of your tribe. When you use the wrong symbols, you signal 'this is not for you.' When you use the right symbols, you signal 'people like us belong here.'", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","semiotics","symbols","communication"], confidence:0.8 },
  { category:"marketing", title:"Treat Different People Differently", content:"Mass marketing treats everyone the same — which means it treats no one well. Modern marketing treats different people differently based on their needs, behaviors, and context. Segment your audience and customize your message for each group. The same product, same price, same channel doesn't work for everyone. New users need onboarding. Power users need advanced features. At-risk users need re-engagement. Advocates need ways to spread the word. Personalization at scale is the goal. Every interaction should feel like it was made just for them.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","personalization","segmentation"], confidence:0.85 },
  { category:"marketing", title:"Price Is a Story", content:"Price is not a number — it's a story you tell about value. Price communicates: Is this for the elite or the masses? Is this an investment or an expense? Is this premium or practical? The price signals the status of the buyer and the quality of the product. Four approaches: 1) Commodity (lowest price wins), 2) Premium (quality/exclusivity), 3) Race to the top (innovate to command premium), 4) Race to the bottom (compete on efficiency). Your pricing strategy IS your marketing strategy. Price for the story you want to tell, not the cost you want to cover.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","pricing","story"], confidence:0.85 },
  { category:"marketing", title:"Permission and Remarkability", content:"PERMISSION: Marketing succeeds when you have permission to talk to people who WANT to hear from you. Permission is a precious asset — earned through consistency and generosity over time. REMARKABILITY: Your product/service must be worth remarking about. If it's not remarkable (worth making a remark about), it won't spread. The virtuous cycle: Permission earns attention -> Remarkability earns sharing -> Sharing earns more Permission. Never buy attention (interruption marketing). Earn it through permission and create something worth talking about.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","permission","remarkability"], confidence:0.85 },
  { category:"marketing", title:"Trust Is as Scarce as Attention", content:"In a world of infinite noise, trust is the new scarcity. People don't buy from brands they don't trust. Trust is earned drop by drop and lost in buckets. How to earn trust: 1) Be consistent — show up the same way every time, 2) Be transparent — share your process, your struggles, your real story, 3) Be generous — give before you ask, 4) Be reliable — do what you say you'll do, 5) Be human — admit mistakes, show personality. Trust is the foundation of the entire marketing relationship. Without it, nothing else matters.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","trust","reputation"], confidence:0.85 },
  { category:"marketing", title:"The Funnel — Not Everyone Is Ready", content:"The customer journey is a funnel: from STRANGER (awareness) -> INTERESTED (curiosity) -> COMMITTED (trial) -> CUSTOMER (purchase) -> EVANGELIST (advocacy). At each stage, the marketer's job is different. Strangers: break through with a story that matches their worldview. Interested: provide more depth, social proof, education. Committed: make the first step easy and risk-free. Customer: over-deliver on the promise. Evangelist: give them tools to spread the story. Most marketers fail by treating everyone at the top of the funnel with the same message meant for the bottom.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","funnel","customer-journey"], confidence:0.85 },
  { category:"marketing", title:"Organizing and Leading a Tribe", content:"Marketing is leadership. You're not just selling a product — you're leading a tribe. A tribe is a group of people connected to one another, connected to a leader, and connected to an idea. Your job as a marketer: 1) Find a shared interest or identity, 2) Provide a way for members to connect, 3) Create a goal or challenge to work toward, 4) Give members status and recognition, 5) Make it easy for members to recruit others. The tribe doesn't exist because of you — you exist because of the tribe. Serve them, and they will grow.", sourceType:"book", sourceName:"This Is Marketing by Seth Godin", tags:["godin","marketing","tribe","leadership","community"], confidence:0.85 },

  // ── Influence: The Psychology of Persuasion — Robert Cialdini ──
  { category:"psychology", title:"Weapons of Influence — Click-Whirr Automaticity", content:"Human behavior runs on 'fixed-action patterns' — automatic tapes triggered by specific features (click-whirr). We use shortcuts (stereotypes, rules of thumb) because we can't analyze every situation deeply. The word 'because' alone triggers compliance even without a real reason. The contrast principle: showing an expensive item first makes the next item seem cheaper. These weapons are like jujitsu — they use natural forces (gravity, leverage, momentum) rather than personal force. Compliance professionals exploit these triggers. Awareness is the first defense: recognize when a trigger is being pulled on you.", sourceType:"book", sourceName:"Influence: The Psychology of Persuasion by Robert Cialdini", tags:["cialdini","influence","psychology","automaticity"], confidence:0.9 },
  { category:"psychology", title:"Reciprocation — The Old Give and Take", content:"The rule says: we must repay what someone has given us. This rule is universal across all human cultures and is the foundation of human society (division of labor, trade, cooperation). Even uninvited gifts create obligation. RECIPROCAL CONCESSION (rejection-then-retreat): make a larger request first, get rejected, then make the real (smaller) request — the other person feels obligated to concede. Key insight: give FIRST before asking. Free samples, valuable content, genuine help — the giver sets the terms. The obligation to receive, then repay, is deeply embedded in human nature.", sourceType:"book", sourceName:"Influence: The Psychology of Persuasion by Robert Cialdini", tags:["cialdini","influence","reciprocation","psychology"], confidence:0.9 },
  { category:"psychology", title:"Commitment and Consistency — Hobgoblins of the Mind", content:"People have a deep desire to be CONSISTENT with what they have already said or done. Once we make a choice or take a stand, we encounter personal and interpersonal pressure to behave consistently with that commitment. The trick: get a small initial commitment, and future larger commitments will follow naturally. WRITTEN commitments are more powerful than verbal. PUBLIC commitments are more powerful than private. ACTIVE commitments are more powerful than passive. The foot-in-the-door technique: start with a small request, then escalate. Consistency is seen as a sign of intelligence and stability — we want to appear consistent even to ourselves.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","consistency","commitment","psychology"], confidence:0.9 },
  { category:"psychology", title:"Social Proof — Truths Are Us", content:"People determine what is correct by finding out what other people think is correct — especially people SIMILAR to themselves. The principle applies most strongly under two conditions: UNCERTAINTY (when we don't know what to do) and SIMILARITY (when we see people like us doing it). The more people who do something, the more right it seems. Use social proof ethically: show testimonials from similar customers, share usage statistics, highlight community size. Negative social proof ('look how many people are doing the wrong thing') can backfire — always frame what people SHOULD do, not what they're doing wrong.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","social-proof","psychology"], confidence:0.9 },
  { category:"psychology", title:"Liking — The Friendly Thief", content:"People say YES to people they LIKE. Factors that increase liking: 1) PHYSICAL ATTRACTIVENESS — attractive people automatically get more compliance, 2) SIMILARITY — we like people who are like us (opinions, personality, background, lifestyle), 3) COMPLIMENTS — genuine praise creates affection, 4) CONTACT & COOPERATION — working together toward a common goal builds liking, 5) ASSOCIATION — we like things associated with positive experiences (good news, pleasant environments). The Tupperware party model: host invites friends who buy because they like the host. In sales, build genuine rapport before the ask. Find common ground. Be likable.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","liking","psychology","rapport"], confidence:0.9 },
  { category:"psychology", title:"Authority — Directed Deference", content:"People defer to authority figures. We are conditioned from childhood to obey legitimate authorities (parents, teachers, bosses, experts). The Milgram experiment showed ordinary people will administer apparently dangerous shocks simply because an authority figure told them to. Symbols of authority: TITLES (Dr., Professor, CEO), CLOTHING (uniforms, suits), TRAPPINGS (expensive cars, corner offices, certificates). To use ethically: establish genuine expertise before making requests. Share credentials, experience, testimonials from experts. BUT beware of fake authority — the principle works even when authority is simulated. Always verify before deferring.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","authority","psychology"], confidence:0.9 },
  { category:"psychology", title:"Scarcity — The Rule of the Few", content:"Opportunities seem more valuable when their availability is LIMITED. The principle: people want MORE of what they can have LESS of. Scarcity works because: 1) limited items are perceived as more valuable, 2) when something becomes less accessible, we lose freedom, and we HATE losing freedom (reactance theory). Limited-time offers, limited-edition products, exclusive access, countdown timers — all leverage scarcity. NEW scarcity (something becoming scarce) is more powerful than EXISTING scarcity. COMPETITION for scarce resources magnifies the effect. BUT: never fake scarcity. False scarcity destroys trust permanently. Only use genuine limitations.", sourceType:"book", sourceName:"Influence by Robert Cialdini", tags:["cialdini","influence","scarcity","psychology"], confidence:0.9 },
];

export async function GET() {
  try {
    const db = await ensureDB();
    let inserted = 0;
    let skipped = 0;

    for (const entry of SEED_BOOKS) {
      const existing = await query(
        { DB: db },
        "SELECT id FROM knowledge_entries WHERE title = ? AND category = ? AND is_active = 1",
        [entry.title, entry.category]
      );
      if (existing.length > 0) { skipped++; continue; }

      await addKnowledgeEntry(entry);
      inserted++;
    }

    return NextResponse.json({
      success: true,
      message: `Seeded ${inserted} entries (${skipped} skipped — already exist)`,
      inserted,
      skipped,
      total: SEED_BOOKS.length,
    });
  } catch (e) {
    return NextResponse.json({ error: (e as Error).message }, { status: 500 });
  }
}
